### ISSUE TITLE
MP: Errors with enbling/disabling AI from HUD

### ISSUE THREAD

**Issue by Dzi4d3k** [Mogli12/AIVehicleExtension#10]
After trying to enable/disable AI using AutoTractor HUD there are error on both MP sides:

Server:
dataS2/character/pedestrians/man02.i3d (5.94) ms
Warning (LUA): 'streamWriteUIntN': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (630): expectedType == Value::VoidType
LUA call stack:
  dataS/scripts/vehicles/specializations/events/AIVehicleSetStartedEvent.lua (59) : streamWriteUIntN
  dataS/scripts/network/Connection.lua (88) : writeStream
  dataS/scripts/vehicles/specializations/events/AIVehicleSetStartedEvent.lua (77) : sendEvent
  dataS/scripts/vehicles/specializations/events/AIVehicleSetStartedEvent.lua (48) : run
  dataS/scripts/network/Server.lua (411) : readStream
  dataS/scripts/network/ConnectionManager.lua (28) : func
dataS2/character/pedestrians/man06.i3d (5.13) ms
Warning (LUA): 'streamWriteUIntN': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (630): expectedType == Value::VoidType
LUA call stack:
  dataS/scripts/vehicles/specializations/events/AIVehicleSetStartedEvent.lua (59) : streamWriteUIntN
  dataS/scripts/network/Connection.lua (88) : writeStream
  dataS/scripts/vehicles/specializations/events/AIVehicleSetStartedEvent.lua (77) : sendEvent
  dataS/scripts/vehicles/specializations/events/AIVehicleSetStartedEvent.lua (48) : run
  dataS/scripts/network/Server.lua (411) : readStream
  dataS/scripts/network/ConnectionManager.lua (28) : func

Client:
dataS2/character/pedestrians/man02.i3d (7.36) ms
Warning (LUA): 'streamWriteUIntN': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (630): expectedType == Value::VoidType
LUA call stack:
  dataS/scripts/vehicles/specializations/events/AIVehicleSetStartedEvent.lua (59) : streamWriteUIntN
  dataS/scripts/network/Connection.lua (88) : writeStream
  dataS/scripts/vehicles/specializations/AIVehicle.lua (538) : sendEvent
  =C:/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (472) : stopAIVehicle
  =C:/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/mogliHud.lua (356) : onClick
  =C:/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (339) : mouseEvent
  dataS/scripts/vehicles/Vehicle.lua (2200) : mouseEvent
  =C:/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/mogliHud.lua (325) : superFunc
  dataS/scripts/BaseMission.lua (1415) : mouseEvent
  dataS/scripts/FSBaseMission.lua (2109) : mouseEvent
  dataS/scripts/missions/mission00.lua (320) : mouseEvent
  dataS/scripts/main.lua (1801) : mouseEvent
dataS2/character/pedestrians/man06.i3d (4.77) ms
Warning (LUA): 'streamWriteUIntN': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (630): expectedType == Value::VoidType
LUA call stack:
  dataS/scripts/vehicles/specializations/events/AIVehicleSetStartedEvent.lua (59) : streamWriteUIntN
  dataS/scripts/network/Connection.lua (88) : writeStream
  dataS/scripts/vehicles/specializations/AIVehicle.lua (538) : sendEvent
  =C:/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (472) : stopAIVehicle
  =C:/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/mogliHud.lua (356) : onClick
  =C:/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (339) : mouseEvent
  dataS/scripts/vehicles/Vehicle.lua (2200) : mouseEvent
  =C:/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/mogliHud.lua (325) : superFunc
  dataS/scripts/BaseMission.lua (1415) : mouseEvent
  dataS/scripts/FSBaseMission.lua (2109) : mouseEvent
  dataS/scripts/missions/mission00.lua (320) : mouseEvent
  dataS/scripts/main.lua (1801) : mouseEvent

But actually HUD works yet require two clicks.

**Comment by Dzi4d3k** [comment]
Errors (and debug info) with v 0.2.0.4

Server:
dataS2/character/pedestrians/woman04.i3d (3.25) ms
Stop AI Vehicle: 1
------------------------------------------------------------------------
2: d:/servers/service10705/home/games/FarmingSimulator17/mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (2463): newFunc
3: [string "dataS/scripts/utils/Utils.lua"] (1857): stopAIVehicle
4: [string "dataS/scripts/vehicles/specializations/events/AIVehicleSetStartedEvent.lua"] (72): run
5: [string "dataS/scripts/vehicles/specializations/events/AIVehicleSetStartedEvent.lua"] (48): readStream
6: [string "dataS/scripts/network/Server.lua"] (411): func
7: [string "dataS/scripts/network/ConnectionManager.lua"] (28): 
------------------------------------------------------------------------
dataS2/character/pedestrians/man01.i3d (3.58) ms
Warning (LUA): 'streamWriteBool': Argument 1 has wrong type. Expected: Bool. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (630): expectedType == Value::VoidType
LUA call stack:
  dataS/scripts/vehicles/specializations/events/SetTurnedOnEvent.lua (46) : streamWriteBool
  dataS/scripts/network/Connection.lua (88) : writeStream
  dataS/scripts/network/Server.lua (508) : sendEvent
  dataS/scripts/vehicles/specializations/events/SetTurnedOnEvent.lua (70) : broadcastEvent
  dataS/scripts/vehicles/specializations/TurnOnVehicle.lua (265) : sendEvent
  dataS/scripts/vehicles/specializations/ManureBarrel.lua (381) : superFunc
  =d:/servers/service10705/home/games/FarmingSimulator17/mods/FS17_AIVehicleExtension/AutoSteeringEngine.lua (6202) : setIsTurnedOn
  =d:/servers/service10705/home/games/FarmingSimulator17/mods/FS17_AIVehicleExtension/AIDriveStrategyMogli.lua (271) : checkIsAnimPlaying
  dataS/scripts/vehicles/specializations/AIVehicle.lua (330) : getDriveData
  dataS/scripts/vehicles/Vehicle.lua (2689) : updateTick
  dataS/scripts/network/Server.lua (68) : updateTick
  dataS/scripts/BaseMission.lua (1509) : update
  dataS/scripts/FSBaseMission.lua (2159) : update
  dataS/scripts/missions/mission00.lua (333) : update
  dataS/scripts/main.lua (1862) : update
Warning (LUA): 'streamWriteBool': Argument 1 has wrong type. Expected: Bool. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (630): expectedType == Value::VoidType
LUA call stack:
  dataS/scripts/vehicles/specializations/events/SetTurnedOnEvent.lua (46) : streamWriteBool
  dataS/scripts/network/Connection.lua (88) : writeStream
  dataS/scripts/network/Server.lua (508) : sendEvent
  dataS/scripts/vehicles/specializations/events/SetTurnedOnEvent.lua (70) : broadcastEvent
  dataS/scripts/vehicles/specializations/TurnOnVehicle.lua (265) : sendEvent
  dataS/scripts/vehicles/specializations/ManureBarrel.lua (381) : superFunc
  =d:/servers/service10705/home/games/FarmingSimulator17/mods/FS17_AIVehicleExtension/AutoSteeringEngine.lua (6202) : setIsTurnedOn
  =d:/servers/service10705/home/games/FarmingSimulator17/mods/FS17_AIVehicleExtension/AIDriveStrategyMogli.lua (271) : checkIsAnimPlaying
  dataS/scripts/vehicles/specializations/AIVehicle.lua (330) : getDriveData
  dataS/scripts/vehicles/Vehicle.lua (2689) : updateTick
  dataS/scripts/network/Server.lua (68) : updateTick
  dataS/scripts/BaseMission.lua (1509) : update
  dataS/scripts/FSBaseMission.lua (2159) : update
  dataS/scripts/missions/mission00.lua (333) : update
  dataS/scripts/main.lua (1862) : update
Stop AI Vehicle: 5
------------------------------------------------------------------------
2: d:/servers/service10705/home/games/FarmingSimulator17/mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (2463): newFunc
3: [string "dataS/scripts/utils/Utils.lua"] (1857): stopAIVehicle
4: [string "dataS/scripts/vehicles/specializations/Sprayer.lua"] (620): getHasSpray
5: [string "dataS/scripts/vehicles/specializations/Sprayer.lua"] (376): updateTick
6: [string "dataS/scripts/vehicles/Vehicle.lua"] (2689): updateTick
7: [string "dataS/scripts/network/Server.lua"] (68): update
8: [string "dataS/scripts/BaseMission.lua"] (1509): update
9: [string "dataS/scripts/FSBaseMission.lua"] (2159): update
10: [string "dataS/scripts/missions/mission00.lua"] (333): update
11: [string "dataS/scripts/main.lua"] (1862): 
------------------------------------------------------------------------

Client:
dataS2/character/pedestrians/woman04.i3d (5.08) ms
Stop AI Vehicle: 1
------------------------------------------------------------------------
2: C:/Data/Do pracy/TBE_Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (2463): newFunc
3: [string "dataS/scripts/utils/Utils.lua"] (1857): stopAIVehicle
4: [string "dataS/scripts/vehicles/specializations/AIVehicle.lua"] (236): update
5: [string "dataS/scripts/vehicles/Vehicle.lua"] (2579): update
6: [string "dataS/scripts/network/Client.lua"] (64): update
7: [string "dataS/scripts/BaseMission.lua"] (1512): update
8: [string "dataS/scripts/FSBaseMission.lua"] (2159): update
9: [string "dataS/scripts/missions/mission00.lua"] (333): update
10: [string "dataS/scripts/main.lua"] (1862): <???>
------------------------------------------------------------------------
dataS2/character/pedestrians/man02.i3d (5.17) ms
Stop AI Vehicle: 5
------------------------------------------------------------------------
2: C:/Data/Do pracy/TBE_Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (2463): newFunc
3: [string "dataS/scripts/utils/Utils.lua"] (1857): stopAIVehicle
4: [string "dataS/scripts/vehicles/specializations/events/AIVehicleSetStartedEvent.lua"] (72): run
5: [string "dataS/scripts/vehicles/specializations/events/AIVehicleSetStartedEvent.lua"] (48): readStream
6: [string "dataS/scripts/network/Client.lua"] (431): func
7: [string "dataS/scripts/network/ConnectionManager.lua"] (28): <???>
------------------------------------------------------------------------

**Comment by Mogli12** [comment]
These were only additional warnings. But I removed them.
