### ISSUE TITLE
AIVehicleExtension streikt nach gewisser Zeit

### ISSUE THREAD

**Issue by 81Mario** [Mogli12/AIVehicleExtension#100]
Ich habe ein Problem, dass nach gewisser Zeit der Spurfühler einfach liegen bleibt und der Drescher einfach solange gradeaus fährt, bis er irgendwann entweder am Mapende oder einem Hindernis hängen bleibt. Bildschirmfoto habe ich angefügt. 
MfG Mario Schrimpf
![img_6607](https://user-images.githubusercontent.com/30497767/28669338-39179d96-72d4-11e7-9452-2573d7f4df00.JPG)

**Comment by Dzi4d3k** [comment]
Could you use print screens key to take a screenshoot from ingame please?

**Comment by 81Mario** [comment]
![Uploading fsScreen_2017_07_28_20_05_15.png…]()

**Comment by 81Mario** [comment]
Here a Screanshot of the Issue

![fsscreen_2017_07_28_20_05_15](https://user-images.githubusercontent.com/30497767/28730541-e0027a48-73d0-11e7-8abc-c190aaed53fa.png)

**Comment by 81Mario** [comment]
![fsscreen_2017_07_28_20_05_29](https://user-images.githubusercontent.com/30497767/28730549-ebcb265e-73d0-11e7-8917-54ca292c7245.png)

**Comment by 81Mario** [comment]
Das Problem tritt auf, wenn ich einen Courseplay Abfahrer verwende und ich in den Drescher switche.

**Comment by 81Mario** [comment]
Dasselbe Problem tritt mit 2 Dreschern gleichzeitig auf dem selben Feld ohne Courseplay auf.
![fsscreen_2017_07_29_15_53_55](https://user-images.githubusercontent.com/30497767/28745331-c9277890-7476-11e7-80c6-8a1b91222d49.png)
![fsscreen_2017_07_29_15_54_13](https://user-images.githubusercontent.com/30497767/28745333-c92bbd92-7476-11e7-8a5e-6709b24cb738.png)
![fsscreen_2017_07_29_15_54_36](https://user-images.githubusercontent.com/30497767/28745332-c92a568c-7476-11e7-8eff-0ed3d25138e3.png)
