### ISSUE TITLE
Planting speed

### ISSUE THREAD

**Issue by Malaras** [Mogli12/AIVehicleExtension#101]
Hello, Just downloaded and trying out your mod. when planting, it seems AI only planting at 6mph, is this correct? i thought default AI is around 10mph?

Seems slow regardless than from normal AI

EDIT just check normal is 12

**Comment by Dzi4d3k** [comment]
Do you using moreRealistic mod?

**Comment by Mogli12** [comment]
You can change the speed with buttons 1 and 2. 3 will pause.
