### ISSUE TITLE
Krone BigX cargo

### ISSUE THREAD

**Issue by BigBud1100** [Mogli12/AIVehicleExtension#105]
This combine is not working with last AI version. I downloaded mod from official website: https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=79745&title=fs2017
Do you have time to add script for this mod as well? 
Thank you.

**Comment by Mogli12** [comment]
This mod has an articulated axis and a fixed attacher. The consequence is that the cutter moves if the steering angle changes. AIVE cannot handle this.
