### ISSUE TITLE
Edge detection does not work well

### ISSUE THREAD

**Issue by olavinto** [Mogli12/AIVehicleExtension#106]
These detection problems seem to be very small, like the route/edge is not calculated far enough in advance. The tractor starts to correct it's line too late and ends up constantly overreacting/correcting. This leads to either a turn (which usually ends up it driving all over the place until it stops completely) or to driving zigzag (over the line on one side, then correcting over the opposing side). Driving direction also seems to have an effect and even a straight edge can often work just fine to one direction while being completely messed up to the other and it's not left/right specific and happens either way (could be related to steep slopes?). Normal turns are also very problematic and the correct line is often missed just enough for problems to start, often even with straight 90 degree turns (with all turn modes).

And I'm having these problems on maps like Coldborough Park Farm, with hills, slopes and oddly shaped fields. I do not use the built in maps at all so I can't comment on those and the mod is pretty pointless on those anyway.

**Some example implements:**

_Plows:_
Amazone Cayron 200 generally works quite well although even it can sometimes lose the edge, even when it's close to straight.
Lemken Titan 11 an other similar style plows have so much problems that they are basically unusable.

_Fertilizer sprayers:_
Amazone UF1201 and KUHN DELTIS 1302 MEA3 (KUHN Pack DLC) generally work rather well but Stilla 460 and similar sprayers do not.

_Seeders and cultivators:_
Strangely many seeders work very well, including large, cultivating seeders while similarly sized and built basic cultivators do not. Even smaller cultivators have problems very often.

_Similar problems can be experienced with most implement types, not just those listed above:_
This is not vehicle or implement specific, happens with small and large implements, with plows, fertilizer spreaders and sprayers, cultivators... Smaller ones tend to work much better. Combines generally work well and with them the mod is actually usable but tractors and implements tend to have so much problems and they 'get lost' so much that they are unusable with this mod. AutoTractor worked much, much better in FS15.

**Comment by Mogli12** [comment]
Please try version 1.1 b14
