### ISSUE TITLE
Amazone FT1001, KUHN PF1500 (DLC) and other extension tanks do not work

### ISSUE THREAD

**Issue by olavinto** [Mogli12/AIVehicleExtension#107]
Quite simply when these tanks are attached with a sprayer, AIVehicleExtension does not seem to work at all.

**Comment by Mogli12** [comment]
I think this should be fixed by v1.1 b17

**Comment by olavinto** [comment]
Yep. Seems to work fine now. Thank you! I'm sorry that I haven't responded earlier.
