### ISSUE TITLE
fieldJob ends + AIVE + seasons bug ?

### ISSUE THREAD

**Issue by mngrazy** [Mogli12/AIVehicleExtension#110]
hi mogli

beim abschluss einer mission , bekomm ich folgenden callStack von zuerst AIVE und dann seasons ,,, da es ohne AIVE nicht auftritt , vermute ich das es nicht an seasons mod liegt

AI Vehicle Extension v1.1 b14 (trat in den vorherigen aber auch auf)

data/vehicles/tools/salford/salford8312.i3d (107.31) ms <--- vehicle für fieldJob
data/vehicles/steerable/challenger/challengerMT900E.i3d (72.74) ms <--- vehicle für fieldJob
Warning (Script): Unknown entity id 95288 in method 'unlink'.
LUA call stack:
  =D:/FS17_AIVehicleExtension/AutoSteeringEngine.lua (6761) : unlink
  =[C] (4294967295)
  =D:/FS17_AIVehicleExtension/AutoSteeringEngine.lua (7342) : deleteNode
  =D:/FS17_AIVehicleExtension/AutoSteeringEngine.lua (6771) : deleteTools
  =D:/FS17_AIVehicleExtension/AIVehicleExtension.lua (297) : deleteChain
  dataS/scripts/vehicles/Vehicle.lua (1518) : preDelete
  dataS/scripts/utils/Utils.lua (1870) : oldFunc
  dataS/scripts/missions/FieldJob.lua (84) : delete
  dataS/scripts/missions/FieldJobManager.lua (692) : delete
  dataS/scripts/missions/FieldJobManager.lua (171) : deleteFieldJob
  =D:/FS17_RM_Seasons/src/misc/ssFieldJobManager.lua (31) : superFunc
  dataS/scripts/BaseMission.lua (1712) : update
  dataS/scripts/FSBaseMission.lua (2187) : update
  dataS/scripts/missions/mission00.lua (346) : update
  dataS/scripts/main.lua (1922) : update
Warning (Script): Unknown entity id 95288 in method 'delete'.
LUA call stack:
  =D:/FS17_AIVehicleExtension/AutoSteeringEngine.lua (6763) : delete
  =[C] (4294967295)
  =D:/FS17_AIVehicleExtension/AutoSteeringEngine.lua (7342) : deleteNode
  =D:/FS17_AIVehicleExtension/AutoSteeringEngine.lua (6771) : deleteTools
  =D:/FS17_AIVehicleExtension/AIVehicleExtension.lua (297) : deleteChain
  dataS/scripts/vehicles/Vehicle.lua (1518) : preDelete
  dataS/scripts/utils/Utils.lua (1870) : oldFunc
  dataS/scripts/missions/FieldJob.lua (84) : delete
  dataS/scripts/missions/FieldJobManager.lua (692) : delete
  dataS/scripts/missions/FieldJobManager.lua (171) : deleteFieldJob
  =D:/FS17_RM_Seasons/src/misc/ssFieldJobManager.lua (31) : superFunc
  dataS/scripts/BaseMission.lua (1712) : update
  dataS/scripts/FSBaseMission.lua (2187) : update
  dataS/scripts/missions/mission00.lua (346) : update
  dataS/scripts/main.lua (1922) : update

grüsse grazy

**Comment by Mogli12** [comment]
Hi,

es scheint, dass irgendwo im Game bereits Knoten gelöscht werden, dich AIVE nochmals löschen möchte. Es sind eh nur Warnungen und besser, man versucht einmal zu viel zu löschen.

Viele Grüße

**Comment by mngrazy** [comment]
naja , aber durch den lua fehler in AIVE , löst dann ja noch einen fehler im seasons mod aus 

ohne AIVE keinerlei probleme

**Comment by Mogli12** [comment]
Ich sehe da nur 2 Warnung samt Callstack.
