### ISSUE TITLE
Falsche Arbeitsbreite in Kombination mit dem Fronttank TF1500 Kuhn DLC

### ISSUE THREAD

**Issue by Evilman2517** [Mogli12/AIVehicleExtension#113]
Hallo,

vor dem Update auf die b22 hatte ich die 09 benutzt, in dieser Version hatte der AIVE die korrekte Arbeitsbreite (die der Sämaschiene am Heck, 4m) verwendet, in der neuen Version, wird leider wieder die Breite des Fronttanks (Danke Giants ;-) ) angewendet, somit kann der AIVE nicht mit der Sämaschiene aus Kuhn DLC verwendet werden. Wäre es eventuell möglich, dass man zu der automatischen Erkennung auch die Möglichkeit hat händisch eine Arbeitsbreite eingeben zu können? Dies würde Probleme mit falschen Arbeitsbreiten minimieren. 

Grüße

**Comment by Mogli12** [comment]
Hallo,

vielen Dank. Das sollte mit v1.1 b23 gelöst sein.

Viele Grüße

**Comment by Evilman2517** [comment]
Hallo,

genau so ist es, Problem ist gelöst. Vielen lieben Dank für die schnelle Unterstützung und den schnellen Fix.

Nebenbei, dein AIVE ist wirklich genial, Danke für den tollen Mod.

Grüße
