### ISSUE TITLE
Chain(crawler)Tractor problem

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Mogli12/AIVehicleExtension#114]
With my crawler tractor this is the problem:
mods/FS17_AIVehicleExtension/AutoSteeringEngine.lua:8443: bad argument #1 to 'pairs' (table expected, got nil)
Error: Running LUA method 'update'.

Appeared immediately after purchase.

**Comment by Mogli12** [comment]
I hope it is fixed with v1.1 b26.

**Comment by Gonimy-Vetrom** [comment]
Thank you. Working.
