### ISSUE TITLE
Left out Lanes

### ISSUE THREAD

**Issue by dominiczeth** [Mogli12/AIVehicleExtension#116]
Hi i had an idea and just wanted to communicate it. Is it possible to add an "Free Lane Mode"? 

Would be usefull when you use more then one tractor on a field and don't use circle Mode. Just an Option: Free Lanes "no" "1" "2" "3"
With this in mind the AI will left out these lanes with their work width. So Setting it to one means:

<<6m Width>> <6m free lane>> <<6m width>> ....

The Next helper would start on the free lane with the same setting. Is that possible to do or is it a silly idea?

**Comment by Mogli12** [comment]
AIVE does not know what a lane is. It knows if it should check the border between areas with and w/o fruits on the left or the right side. And it knows what to do at the end of the field.

Did you already check [courseplay six](https://github.com/Courseplay/courseplay)?
