### ISSUE TITLE
problem combine

### ISSUE THREAD

**Issue by ITA-ROCCIA** [Mogli12/AIVehicleExtension#118]
Hi, I have a problem with the mod when I'm going to use the combine. practically the mod does not work, I can use it only with the standard worker, Maybe it's a problem of incompatibility between some mods. I put a picture and also the log.
use courseplay, game extension and more.
How can I solve?

Thanks for the answers 

https://imgur.com/a/912P8 <------ image game 

https://www.dropbox.com/s/okbvj8oi53x2ktm/log.txt?dl=0<----- log

**Comment by Mogli12** [comment]
Did you try a standard header?

**Comment by ITA-ROCCIA** [comment]
yes and it works in standard game

**Comment by Mogli12** [comment]
I close all FS17 problems.
