### ISSUE TITLE
Dismissing worker block vehicle

### ISSUE THREAD

**Issue by Dzi4d3k** [Mogli12/AIVehicleExtension#12]
This happens both SP and MP, and as far as I remember happened also in AutoTractor in FS15.
After siting in vehicle and dismissing helper vehicle is blocked, so truing of and on of engine is required. There is no errors related to this, but this is rather low priority yet annoying.

**Comment by Sythos** [comment]
This is (probably) an issue of FS17 engine, if you use standard helper with manual-turn-on-engine option you need stop&restart the engine once you dismiss the helper. Not tested in MP, but in SP using automatic-engine-start don't cause bad behaviour on vehicles

**Comment by turbostar190** [comment]
Mmh no, After latest patch that problem was solved, with standard helper.
