### ISSUE TITLE
Problem with combines stopping

### ISSUE THREAD

**Issue by MAJ72** [Mogli12/AIVehicleExtension#120]
Hi,

First of all, thx for a great mod, I have been using this in both FS15 and FS17.

I have for some time now experienced a problem with combines stop working and reporting that helper is blocked by an object eventhough there is no object in front of the combine.

It seems the problem is mainly when the combine is working east to west.

I have experienced the matter on several maps and with both standard and modded combines.

Any idea what is causing this?

Thanks in advance for your help.

B. Rgds
Mogens

Here is a printscreen of the issue 
![image](https://user-images.githubusercontent.com/36594861/36351460-9788b64e-14aa-11e8-8308-9f996f6558ec.png)

And below is my log:
GIANTS Engine Runtime 7.0.0 (15681) 64bit (Build Date: Dec  7 2017)
Copyright (c) 2008-2017, GIANTS Software GmbH (giants-software.com), All Rights Reserved.
Copyright (c) 2003-2017, Christian Ammann and Stefan Geiger, All Rights Reserved.
Application: FarmingSimulator2017
Main System
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Memory: 16236 MB
  OS: Windows NT 10.0 64-bit
Physics System
  Version: 5.9.5
  Thread(s): 2
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick enabled
  Force Feedback disabled
  Name: Logitech Cordless RumblePad 2
Audio System
  Driver: OpenAL
  Version: 1.1
  Device: Generic Software
Render System
  Driver: Direct 3D 11
  Card Vendor: NVIDIA Corporation
  Renderer: NVIDIA GeForce GTX 1060
  Version: 22.21.13.8205 (1.5.2017)
  Revision: 161
  Feature level: DirectX 11 ON
Info: Effective window resolution 3840 x 2160
Started 4 threads for threadpool 'Render threadpool'
Hardware Profile
  Level: Very High (forced)
  View Distance Factor: 1.300000
  Shadow Quality: 2.000000 Size: 4096 Filter-Size: 16
  Shader Quality: 3
  Skip Mipmaps: 0
  LOD Distance Factor: 1.300000
  Terrain LOD Distance Factor: 2.000000
  Terrain Normal Mapping: Yes
  Foliage View Distance Factor: 1.600000
  Max dynamic foliage View Distance Factor: 1.600000
  Foliage Density: 0.500000
  Volume Mesh Tessellation Factor: 0.750000
  Tyre Tracks Segments Factor: 4.000000
  Max. Number of Shadow Lights: 5
  Max. Number of Lights: 512
  Max. Number of Lights Per Cluster: 32
  MSAA: 4
Farming Simulator 17 (Steam)
  Version: 1.5.3.1 b1848
  Available Languages: en de jp pl cz fr es ru it pt hu nl cs ct br tr ro kr
  Language: en
  Time: 2018-02-18 11:55:01
  Register configuration 'inputAttacherJoint'
  Register configuration 'attacherJoint'
  Register configuration 'frontloader'
  Register configuration 'motor'
  Register configuration 'baseColor'
  Register configuration 'wheel'
  Register configuration 'rimColor'
  Register configuration 'design'
  Register configuration 'designColor'
  Register configuration 'vehicleType'
Game vehicle types loaded
Load mod: FS17_challengerMT700EFieldViper (Version: 1.0.0.0)
Load mod: FS17_valtraTSeriesCowEdition (Version: 1.0.0.0)
Load mod: AAA_UniversalProcessKit (Version: 17.0.7)
Load mod: courseplay (Version: 5.02.00055)
Load mod: FS17ClaasLexion700New (Version: 2.0)
Load mod: FS17_3050HD (Version: 1.0)
Load mod: FS17_AIVehicleExtension (Version: 1.0.0.0)
Load mod: FS17_BaleCounter (Version: 1)
Warning: Missing l10n for button reset in FS17_BaleCounter
Load mod: FS17_Bales_Autoload_Pack (Version: 1.0.0.0)
Load mod: FS17_BresselundLadeBallengreiferv2 (Version: 2.0.0.0)
Load mod: FS17_DCK_FollowMe (Version: 1.2.1.40)
Load mod: FS17_Fendt1000_steph33_v1_6 (Version: 1.6.0.0)
Load mod: FS17_FlieglFlatbed_UAL (Version: 6.0.0.0)
Load mod: FS17_ForRealModule02_TireDirt (Version: 1.0.2.0)
Load mod: FS17_ForRealModule03_GroundResponse (Version: 1.0.4.0)
Load mod: FS17_JCB_435S_AWS (Version: 1.0.0.0)
Load mod: FS17_Joskin_KTP_2250_BsM (Version: 1.0.0.0)
Load mod: FS17_Joskin_Trans_7000_BsM (Version: 1.0.0.0)
Load mod: FS17_kotteUniversalPack (Version: 1.0.0.8)
Load mod: FS17_lelyJuno150 (Version: 1.0.2.0)
Load mod: FS17_MF_8700_MR_Series (Version: 3.0.1.0)
Load mod: FS17_MF_8700_Series (Version: 3.0.1.0)
Load mod: FS17_Pack_Joskin_Wago_AUTO_BsM (Version: 1.0.0.3)
Load mod: FS17_placeableRefillStation (Version: 1.0.0.1)
Load mod: FS17_RM_Seasons (Version: 1.3.0.0)
Load mod: FS17_Robust_Trailer_Pack (Version: 2.0)
Load mod: FS17_StopMilkSale_1_0 (Version: 1.0.0.0)
Load mod: FS17_teraVitessePackbyStevie (Version: 1.0.0.4)
Load mod: FS17_WheelloaderBalefork_PC (Version: 1.0.0.0)
Load mod: FS17_Wilson_Livestock (Version: 1.0.0.0)
Load mod: Inspect17 (Version: 1.2)
Load mod: NF_Marsch_4fach_oG (Version: 1.4)
Load mod: PlateauCMSautoLoad (Version: 1)
Load mod: US_Trailer_UAL (Version: 2.0.0.0)
Load mod: ZZZ_CommodityPrices (Version: 0.1.50)
Load mod: zzz_Ertrag_V2_0 (Version: 1.7)
Load mod: ZZZ_fastForward (Version: 2.1)
upk debug mode set to 1
### Courseplay: initialized 48/48 files (v5.02.00055)
    ******************************************* WARNING *******************************************
    * You are using a development version of Courseplay, which may and will contain errors, bugs, *
    * mistakes and unfinished code. Chances are your computer will explode when using it. Twice.  *
    * If you have no idea what "beta", "alpha", or "developer" means and entails, remove this     *
    * version of Courseplay immediately. The Courseplay team will not take any responsibility for *
    * crop destroyed, savegames deleted or baby pandas killed.                                    *
    ***********************************************************************************************
  adding Courseplay to "selfPropelledSprayer"
  adding Courseplay to "tractor"
  adding Courseplay to "car_dynamicMountAttacher"
  adding Courseplay to "combine_animated"
  adding Courseplay to "loaderVehicle"
  adding Courseplay to "wheelLoader"
  adding Courseplay to "conveyorTrailerDrivable"
  adding Courseplay to "selfPropelledMixerWagon"
  adding Courseplay to "woodHarvester"
  adding Courseplay to "skidSteer"
  adding Courseplay to "combine_animated_crawler"
  adding Courseplay to "tractor_articulatedAxis"
  adding Courseplay to "car"
  adding Courseplay to "ridingMower"
  adding Courseplay to "woodCrusherTrailerDrivable"
  adding Courseplay to "conveyorTrailerHireable"
  adding Courseplay to "tractor_crawler"
  adding Courseplay to "selfPropelledMower"
  adding Courseplay to "combine_animated_articulatedAxis"
  adding Courseplay to "tractor_foldable"
  adding Courseplay to "loadingTrailerDrivable"
  adding Courseplay to "combine"
  adding Courseplay to "selfPropelledPotatoHarvester"
  adding Courseplay to "telehandler_articulatedAxis"
  adding Courseplay to "telehandler"
  adding Courseplay to "forwarder"
  adding Courseplay to "combine_cylindered"
  adding Courseplay to "tractor_reverseDriving"
### Courseplay: installed into 28 vehicles
AutoSteeringEngine initialized
  Register vehicle type: FS17_Bales_Autoload_Pack.Slow_flieglLoader
  Register vehicle type: FS17_Bales_Autoload_Pack.Slow_baleLoader
  Register vehicle type: FS17_BresselundLadeBallengreiferv2.balefork
Script loaded: FollowMe.lua (v1.2.1.40)
  Register vehicle type: FS17_Fendt1000_steph33_v1_6.Fendt1000vario
  Register vehicle type: FS17_FlieglFlatbed_UAL.transportTrailerUAL
  Register vehicle type: FS17_kotteUniversalPack.kotteUniversal
  Register vehicle type: FS17_kotteUniversalPack.kotteUniversalOverload
  Register vehicle type: FS17_kotteUniversalPack.kotteMilkBarrel
  Register vehicle type: FS17_kotteUniversalPack.kotteMilkBarrelOverload
  Register vehicle type: FS17_kotteUniversalPack.kotteUniversal_mst
  Register vehicle type: FS17_kotteUniversalPack.kotteUniversal_mstOverload
  Register vehicle type: FS17_kotteUniversalPack.kotteUniFuel
  Register vehicle type: FS17_kotteUniversalPack.kotteUniversal_hookLift
  Register vehicle type: FS17_kotteUniversalPack.kotteUniversal_hookLiftOverload
  Register vehicle type: FS17_kotteUniversalPack.kotteUniversal_man
  Register vehicle type: FS17_kotteUniversalPack.kotteUniversal_manOverload
  Register vehicle type: FS17_kotteUniversalPack.kotteUniversalTank
  Register vehicle type: FS17_lelyJuno150.juno150
  Register vehicle type: FS17_Pack_Joskin_Wago_AUTO_BsM.transportTrailerUAL
  Register vehicle type: FS17_Robust_Trailer_Pack.R600SMS
  Register vehicle type: FS17_Robust_Trailer_Pack.R800PT
  Register vehicle type: FS17_WheelloaderBalefork_PC.wheelloaderBalefork
  Register vehicle type: FS17_Wilson_Livestock.livestockTrailer
Warning: 'WILSON' is an unknown brand! Using Lizard instead! (C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/FS17_Wilson_Livestock/Wilson_LiveStock.xml)
  Register vehicle type: FS17ClaasLexion700New.Lexion700
  Register vehicle type: FS17ClaasLexion700New.vario
Script PalettenSammler v3.0.1-107a by Marhu loaded! Support on http://marhu.net
AdditionalMapTypes v1.0.0.5: \__ AdditionalMapTypes V1.0.0.5 by Blacksheep - RC-Devil from 10 Dezember 2016 is loading
AdditionalMapTypes v1.0.0.5: \__ AdditionalMapTypes V1.0.0.5 by Blacksheep - RC-Devil from 10 Dezember 2016 was loaded successful
 ++ loading GasStation Extended - variable fuel price V 1.3.1.0  -  12.01.2017 (by Blacky_BPG)
 ++ loading GasStation Extended V 1.4.0.0  -  10.02.2017 (by Blacky_BPG)
 ++ loading Scale Station with statistics V 1.4.0.0  -  10.02.2017 (by Blacky_BPG)
 ++ loading Scale Statistic Specialization V 1.2.1.1  -  16.11.2016 (by Blacky_BPG)
  Register vehicle type: PlateauCMSautoLoad.transportTrailerUAL
  Register vehicle type: US_Trailer_UAL.transportTrailerUAL
dataS/cameraPath01.i3d (0.09) ms
dataS/cameraPath02.i3d (0.13) ms
dataS/cameraPath03.i3d (0.07) ms
[Seasons] Loading Seasons 1.3.0.0-develop_8c68e48 - e68ac2160f729519a129cc24f24ac24c
data/sky/skyUS_day_night.i3d (8.40) ms
data/sky/rain.i3d (1.35) ms
data/sky/hail.i3d (1.08) ms
data/sky/dust.i3d (0.32) ms
C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/FS17_RM_Seasons/resources/environment/snow.i3d (1.48) ms
C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/NF_Marsch_4fach_oG/maps/map01.i3d (11581.05) ms
FabrikScript v2.1.8.1: FabrikScript.onCreate(59084) load Fabrik
FabrikScript v2.1.8.1: FabrikScript.onCreate(59435) load Holzhacker
FabrikScript v2.1.8.1: FabrikScript.onCreate(59639) load compostMaster2k17
FabrikScript v2.1.8.1: FabrikScript.onCreate(59874) load Klaerwerk
FabrikScript v2.1.8.1: FabrikScript.onCreate(60085) load WeizenMehlfabrik
FabrikScript v2.1.8.1: FabrikScript.onCreate(60284) load GersteMehlfabrik
FabrikScript v2.1.8.1: FabrikScript.onCreate(60473) load RoggenMehlfabrik
FabrikScript v2.1.8.1: FabrikScript.onCreate(60700) load Zuckerfabrik
FabrikScript v2.1.8.1: FabrikScript.onCreate(60966) load Paletten_Fabrik
FabrikScript v2.1.8.1: FabrikScript.onCreate(63210) load BrauereiKasten
FabrikScript v2.1.8.1: FabrikScript.onCreate(64252) load BrauereiFass
FabrikScript v2.1.8.1: FabrikScript.onCreate(65369) load Molkerei
FabrikScript v2.1.8.1: FabrikScript.onCreate(70437) load Zellstoff_Fabrik
FabrikScript v2.1.8.1: FabrikScript.onCreate(71518) load obst_apfel
FabrikScript v2.1.8.1: FabrikScript.onCreate(73098) load obst_birne
FabrikScript v2.1.8.1: FabrikScript.onCreate(74764) load obst_kirsche
FabrikScript v2.1.8.1: FabrikScript.onCreate(76395) load obst_pflaume
FabrikScript v2.1.8.1: FabrikScript.onCreate(78249) load Kartoffelfabrik
FabrikScript v2.1.8.1: FabrikScript.onCreate(84684) load Brennerei_Korn
FabrikScript v2.1.8.1: FabrikScript.onCreate(86769) load Brennerei_Obstler
FabrikScript v2.1.8.1: FabrikScript.onCreate(90893) load HofladenApfel
FabrikScript v2.1.8.1: FabrikScript.onCreate(91011) load HofladenBirne
FabrikScript v2.1.8.1: FabrikScript.onCreate(91129) load HofladenPflaume
FabrikScript v2.1.8.1: FabrikScript.onCreate(91247) load Hofladenkirsche
FabrikScript v2.1.8.1: FabrikScript.onCreate(91381) load Hofladentomaten
FabrikScript v2.1.8.1: FabrikScript.onCreate(91467) load Hofladensalat
FabrikScript v2.1.8.1: FabrikScript.onCreate(91617) load HofladenBlumenkohl
FabrikScript v2.1.8.1: FabrikScript.onCreate(91773) load HofladenRotkohl
FabrikScript v2.1.8.1: FabrikScript.onCreate(91923) load geldboxen
FabrikScript v2.1.8.1: FabrikScript.onCreate(91977) load Pellets_Fabrik
FabrikScript v2.1.8.1: FabrikScript.onCreate(93951) load sand
FabrikScript v2.1.8.1: FabrikScript.onCreate(94051) load kies
FabrikScript v2.1.8.1: FabrikScript.onCreate(94208) load Zementverkauf
FabrikScript v2.1.8.1: FabrikScript.onCreate(95321) load Sandverkauf
FabrikScript v2.1.8.1: FabrikScript.onCreate(95374) load Kiesverkauf
FabrikScript v2.1.8.1: FabrikScript.onCreate(95427) load holz
FabrikScript v2.1.8.1: FabrikScript.onCreate(95587) load Paletten_Fabrik2
FabrikScript v2.1.8.1: FabrikScript.onCreate(97292) load Duenger_Prod
FabrikScript v2.1.8.1: FabrikScript.onCreate(97446) load Saat_Prod
FabrikScript v2.1.8.1: FabrikScript.onCreate(97595) load Fertilizer
FabrikScript v2.1.8.1: FabrikScript.onCreate(97674) load Saatgut
FabrikScript v2.1.8.1: FabrikScript.onCreate(97754) load Schweinefutter
FabrikScript v2.1.8.1: FabrikScript.onCreate(97827) load kartoffellager
FabrikScript v2.1.8.1: FabrikScript.onCreate(97882) load kartoffellager2
FabrikScript v2.1.8.1: FabrikScript.onCreate(97937) load zuckerrueben
FabrikScript v2.1.8.1: FabrikScript.onCreate(98041) load Duenger_Prod2
FabrikScript v2.1.8.1: FabrikScript.onCreate(98225) load Saat_Prod2
FabrikScript v2.1.8.1: FabrikScript.onCreate(99317) load Schweinefutterstation
FabrikScript v2.1.8.1: FabrikScript.onCreate(99532) load potatoWasher
FabrikScript v2.1.8.1: FabrikScript.onCreate(99669) load potatoWasher2
FabrikScript v2.1.8.1: FabrikScript.onCreate(99806) load Schlachterei
FabrikScript v2.1.8.1: FabrikScript.onCreate(102495) load Tomatenzucht
FabrikScript v2.1.8.1: FabrikScript.onCreate(102819) load Salatzucht
FabrikScript v2.1.8.1: FabrikScript.onCreate(103165) load Rotkohlzucht
FabrikScript v2.1.8.1: FabrikScript.onCreate(103496) load Blumenkohlzucht
FabrikScript v2.1.8.1: FabrikScript.onCreate(104090) load Kuerbisfeld
FabrikScript v2.1.8.1: FabrikScript.onCreate(106994) load Weberei
FabrikScript v2.1.8.1: FabrikScript.onCreate(107905) load Mischfutterstation
FabrikScript v2.1.8.1: FabrikScript.onCreate(212772) load compostlager
FabrikScript v2.1.8.1: FabrikScript.onCreate(212865) load compostlager2
FabrikScript v2.1.8.1: FabrikScript.onCreate(212957) load Speiseoel_Fabrik
FabrikScript v2.1.8.1: FabrikScript.onCreate(214536) load Diesel_Raffinerie
FabrikScript v2.1.8.1: FabrikScript.onCreate(214664) load KraftFutterHerstellung
FabrikScript v2.1.8.1: FabrikScript.onCreate(214916) load Backerei_Brot
FabrikScript v2.1.8.1: FabrikScript.onCreate(215057) load Backerei_Backwaren
FabrikScript v2.1.8.1: FabrikScript.onCreate(215300) load Backerei_Kuchen
FabrikScript v2.1.8.1: FabrikScript.onCreate(215609) load Lager_Backwaren
FabrikScript v2.1.8.1: FabrikScript.onCreate(222284) load Lager_Kuchen
FabrikScript v2.1.8.1: FabrikScript.onCreate(228960) load Lager_Papier
FabrikScript v2.1.8.1: FabrikScript.onCreate(240098) load Lager_Karton
FabrikScript v2.1.8.1: FabrikScript.onCreate(241798) load Lager_Leerpaletten
FabrikScript v2.1.8.1: FabrikScript.onCreate(243121) load Lager_Apfel
FabrikScript v2.1.8.1: FabrikScript.onCreate(253071) load Lager_Birne
FabrikScript v2.1.8.1: FabrikScript.onCreate(263021) load Lager_Kirsche
FabrikScript v2.1.8.1: FabrikScript.onCreate(272971) load Lager_Pflaume
FabrikScript v2.1.8.1: FabrikScript.onCreate(282921) load Lager_Bierkasten
FabrikScript v2.1.8.1: FabrikScript.onCreate(291806) load Lager_Bierfass
FabrikScript v2.1.8.1: FabrikScript.onCreate(294460) load Lager_Zucker
FabrikScript v2.1.8.1: FabrikScript.onCreate(299338) load Lager_Mehl
FabrikScript v2.1.8.1: FabrikScript.onCreate(304216) load Lager_Milch
FabrikScript v2.1.8.1: FabrikScript.onCreate(310891) load Lager_Butter
FabrikScript v2.1.8.1: FabrikScript.onCreate(317566) load Lager_Quark
FabrikScript v2.1.8.1: FabrikScript.onCreate(324241) load Lager_Sahne
FabrikScript v2.1.8.1: FabrikScript.onCreate(330916) load Lager_Yogurt
FabrikScript v2.1.8.1: FabrikScript.onCreate(337591) load Lager_Brot
FabrikScript v2.1.8.1: FabrikScript.onCreate(340286) load Lager_kartoffelsack
FabrikScript v2.1.8.1: FabrikScript.onCreate(345164) load Lager_Chips
FabrikScript v2.1.8.1: FabrikScript.onCreate(351839) load Lager_pommes
FabrikScript v2.1.8.1: FabrikScript.onCreate(358514) load Lager_washedPotato
FabrikScript v2.1.8.1: FabrikScript.onCreate(359092) load Lager_oel
FabrikScript v2.1.8.1: FabrikScript.onCreate(365767) load Lager_Wurst
FabrikScript v2.1.8.1: FabrikScript.onCreate(372442) load Lager_Fleisch
FabrikScript v2.1.8.1: FabrikScript.onCreate(379117) load Lager_obstler
FabrikScript v2.1.8.1: FabrikScript.onCreate(385792) load Lager_Korn
FabrikScript v2.1.8.1: FabrikScript.onCreate(392614) load Lager_Blumenkohl
FabrikScript v2.1.8.1: FabrikScript.onCreate(402564) load Lager_Tomaten
FabrikScript v2.1.8.1: FabrikScript.onCreate(412514) load Lager_Salat
FabrikScript v2.1.8.1: FabrikScript.onCreate(422464) load Lager_Rotkohl
FabrikScript v2.1.8.1: FabrikScript.onCreate(432414) load Lager_Pellets
FabrikScript v2.1.8.1: FabrikScript.onCreate(437278) load kaufleerpalette
FabrikScript v2.1.8.1: FabrikScript.onCreate(437417) load kaufkartonpalette
FabrikScript v2.1.8.1: FabrikScript.onCreate(437471) load kaufbretterpalette
FabrikScript v2.1.8.1: FabrikScript.onCreate(437525) load Lager_Fisch
FabrikScript v2.1.8.1: FabrikScript.onCreate(445238) load kaufstahlpalette
FabrikScript v2.1.8.1: FabrikScript.onCreate(447598) load Fischerei
FabrikScript v2.1.8.1: FabrikScript.onCreate(448230) load Lager_Krabben
FabrikScript v2.1.8.1: FabrikScript.onCreate(455943) load Cementfabrik
FabrikScript v2.1.8.1: FabrikScript.onCreate(469977) load Rinderzucht
FabrikScript v2.1.8.1: FabrikScript.onCreate(470660) load Rinderzucht2
FabrikScript v2.1.8.1: FabrikScript.onCreate(471765) load brueckenbau
FabrikScript v2.1.8.1: FabrikScript.onCreate(473748) load Eierhof
FabrikScript v2.1.8.1: FabrikScript.onCreate(488068) load Eierhof2
FabrikScript v2.1.8.1: FabrikScript.onCreate(508830) load Holzscheitwerk
FabrikScript v2.1.8.1: FabrikScript.onCreate(509362) load Saegewerk2
FabrikScript v2.1.8.1: FabrikScript.onCreate(509718) load Holzkohlewerk
## Courseplay: setting up signs
C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/courseplay/img/signs/normal.i3d (0.33) ms
C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/courseplay/img/signs/cross.i3d (0.48) ms
C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/courseplay/img/signs/unload.i3d (0.49) ms
C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/courseplay/img/signs/wait.i3d (0.66) ms
C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/courseplay/img/signs/start.i3d (0.68) ms
C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/courseplay/img/signs/stop.i3d (0.65) ms
## Courseplay: register later loaded mods
  adding Courseplay to "FS17_kotteUniversalPack.kotteUniversal_man"
  adding Courseplay to "FS17_lelyJuno150.juno150"
  adding Courseplay to "FS17_Fendt1000_steph33_v1_6.Fendt1000vario"
  adding Courseplay to "FS17ClaasLexion700New.Lexion700"
  adding Courseplay to "FS17_kotteUniversalPack.kotteUniversal_manOverload"
  adding Courseplay to "FS17_Bales_Autoload_Pack.Slow_baleLoader"
--- loading AI Vehicle Extension v1.0 by mogli ---
-- registering bale counter specialization
adding bale counter to baler
C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/FS17_kotteUniversalPack/materials/unloadingEffects.i3d (13.11) ms
MaterialHolder for Kotte Universal loaded successfull!
MaterialType fluid registered successfull!
Warning (LUA): 'setXMLFloat': Argument 2 has wrong type. Expected: Float. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType
LUA call stack:
  =C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/Inspect17/Inspect17.lua (383) : setXMLFloat
  =C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/Inspect17/Inspect17.lua (16) : loadConfig
  dataS/scripts/BaseMission.lua (557) : loadMap
  dataS/scripts/FSBaseMission.lua (1723) : loadMapFinished
  dataS/scripts/utils/Utils.lua (1870) : oldFunc
--- fast Forward Mod V2.1 loaded --- (by upsidedown)
C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/FS17_RM_Seasons/resources/environment/snow_materialHolder.i3d (5.08) ms
C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/FS17_RM_Seasons/resources/replacementTextures/materialHolder.i3d (207.88) ms
Enabled withering
data/vehicles/tools/suer/suerSB2400.i3d (5.58) ms
[Seasons] Warning: Density map size of fruit 'wheat' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'barley' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'rape' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'sunflower' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'soybean' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'maize' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'potato' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'sugarBeet' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'oilseedRadish' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'poplar' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'grass' is not the same as terrain
[Seasons] Warning: Density map size of fruit 'dryGrass' is not the same as terrain
data/vehicles/tools/bredal/F2WS4000.i3d (21.95) ms
C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/FS17_Joskin_Trans_7000_BsM/Joskin_Trans.i3d (152.56) ms
data/vehicles/tools/agco/agco2300.i3d (5.43) ms
data/vehicles/tools/horsch/horschPronto9DC.i3d (57.85) ms
C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/FS17_MF_8700_Series/MF8700.i3d (468.82) ms
C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AutoCombine.i3d (0.14) ms
C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/FS17ClaasLexion700New/Lexion.i3d (786.15) ms
C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/FS17ClaasLexion700New/Vario1200.i3d (89.48) ms
C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/FS17_placeableRefillStation/seedRefillTank.i3d (44.60) ms
C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/FS17_placeableRefillStation/fertilizerRefillTank.i3d (0.54) ms
dataS2/character/player/player01.i3d (248.84) ms
dataS2/character/pedestrians/man03.i3d (4.05) ms
dataS2/character/pedestrians/woman04.i3d (3.96) ms
C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/FS17ClaasLexion700New/Vario1050.i3d (52.07) ms
dataS2/character/pedestrians/man02.i3d (4.12) ms
C:/Users/Mogens/Documents/My Games/FarmingSimulator2017/mods/FS17ClaasLexion700New/Lexion.i3d (706.64) ms
dataS2/character/pedestrians/man01.i3d (3.83) ms

**Comment by Mogli12** [comment]
Hi,

Can you try version [1.1](https://www.farming-simulator.com/mod.php?mod_id=75936&title=fs2017) or the latest [beta](https://github.com/Mogli12/AIVehicleExtension/blob/master/FS17_AIVehicleExtension.zip?raw=true)?

Thanks,
Stefan

**Comment by MAJ72** [comment]
Hi, the issue continues even if I have updated to version 1.1

But it is only when the combine is working east to west.

Any help would be appreciated

**Comment by Mogli12** [comment]
If this happens only with the class cutter than maybe the AI marker and not at the right position.

**Comment by MAJ72** [comment]
Unfortunately it also happens with standard combines

**Comment by Mogli12** [comment]
I close all FS17 problems.
