### ISSUE TITLE
Engine.lua Problem

### ISSUE THREAD

**Issue by Paul2510** [Mogli12/AIVehicleExtension#122]
Hi hab ein Problem Ingame es kommt folgender Fehler
C:/Users/Nemesis/Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AutoSteeringEngine.lua:7413: attempt to index field 'attacherVehicle' (a nil value)
Error: Running LUA method 'update'.

LG

**Comment by Mogli12** [comment]
Hallo,
kann ich die komplette log.txt haben. Welche Version verwendest Du?
Vielen Dank

**Comment by Paul2510** [comment]
Version die aktuelle hier die log
[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/1887040/log.txt)

**Comment by Mogli12** [comment]
Hallo,
da sind zwar viele Fehler in der log.txt, aber FS17_AIVehicleExtension ist gar nicht geladen.
Viele Grüße

**Comment by Paul2510** [comment]
Sorry mein Fehler hab die Log ohne hochgeladen!

**Comment by Paul2510** [comment]
[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/1887741/log.txt)

**Comment by Mogli12** [comment]
I close all FS17 problems.
