### ISSUE TITLE
Combine question

### ISSUE THREAD

**Issue by tomatoamong** [Mogli12/AIVehicleExtension#123]
Hi Mogli, how can i get the AIVehicleExtension to drive the combine straight in a field instead of going around the square and doing the harvesting.

**Comment by Mogli12** [comment]
Hi, 
Just open the HUD (LCtrl+H) and change the mode.
Regards

**Comment by tomatoamong** [comment]
What mode do i change it to?

**Comment by Dzi4d3k** [comment]
Didn't you really saw any of this king youtube videos?

[![AI Vehicle Extension](https://img.youtube.com/vi/mP0WE0zYzkU/0.jpg)](https://www.youtube.com/watch?v=mP0WE0zYzkU)

**Comment by Mogli12** [comment]
If you press LShift+H a settings dialog opens. Here you can turn off the circular mode via the left setting in row three.
