### ISSUE TITLE
Additional translation of the message

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Mogli12/AIVehicleExtension#124]
Hello Stefan.
Please add this text for translation.
Players see it most often, but I forgot to translate it.
`AIVehicleExtension.showWarning( vehicle, string.format("Field detection is running (%0.3f ha)", hektar), 500 )`
Thank you for your work.

**Comment by Mogli12** [comment]
Hello,
I added two texts in English and German.
Regards,
Stefan

**Comment by Gonimy-Vetrom** [comment]
Thank you.
