### ISSUE TITLE
Randomly Hitting Obstacles

### ISSUE THREAD

**Issue by Anubis074** [Mogli12/AIVehicleExtension#125]
My issue is I start my harvester and then it will randomly hit obstacles that are unseen. Not sure what it is hitting and I can just back up and restart to keep it going. Trying to see if this is a known problem. 

Anubis

**Comment by Mogli12** [comment]
Hi,

Can you send a screen shot with the Hud visible?

Thank

**Comment by Fracking** [comment]
Hi,

I have the same issue. I took some screenshots. Perhaps they are useful.
[Screenshots](https://imgur.com/a/scO83um)
I´ve noticed that it only seems to occur during corn harvest. So perhaps it has something to do with the headers. I´ve set the "collision check [on]" to "off", but it didn´t fix the issue.
When I have the normal worker running, there seems to be no issue. The issue seems map independant, because I had the same issue on a previous map, but with a different header.

Fracking

**Comment by Mogli12** [comment]
Is v1.2 beta 4 better?

**Comment by Fracking** [comment]
Seems better.

**Comment by jdgp31** [comment]
Hello
Having issues with random stops doing fieldwork with unseen obstacles also, using v1.5 build 5. Log reads as follows:

Warning (Script): Unknown entity id 203516 in method 'unlink'.
LUA call stack:
  =C:/Users/GARY/Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AutoSteeringEngine.lua (6783) : unlink
  =[C] (4294967295)
  =C:/Users/GARY/Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AutoSteeringEngine.lua (7307) : deleteNode
  =C:/Users/GARY/Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AutoSteeringEngine.lua (6793) : deleteTools
  =C:/Users/GARY/Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (296) : deleteChain
  dataS/scripts/vehicles/Vehicle.lua (1518) : preDelete
  dataS/scripts/utils/Utils.lua (1870) : oldFunc
  dataS/scripts/network/NetworkNode.lua (70) : delete
  dataS/scripts/network/Server.lua (34) : delete
  dataS/scripts/BaseMission.lua (299) : delete
  dataS/scripts/FSBaseMission.lua (537) : delete
  dataS/scripts/missions/mission00.lua (84) : delete
  dataS/scripts/events.lua (125) : delete
  dataS/scripts/gui/InGameMenu.lua (457) : OnInGameMenuMenu
  dataS/scripts/gui/InGameMenu.lua (614) : leaveCurrentGame
  dataS/scripts/gui/elements/ButtonElement.lua (191) : raiseCallback
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/Gui.lua (270) : mouseEvent
  dataS/scripts/main.lua (1857) : mouseEvent
Warning (Script): Unknown entity id 203516 in method 'delete'.
LUA call stack:
  =C:/Users/GARY/Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AutoSteeringEngine.lua (6785) : delete
  =[C] (4294967295)
  =C:/Users/GARY/Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AutoSteeringEngine.lua (7307) : deleteNode
  =C:/Users/GARY/Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AutoSteeringEngine.lua (6793) : deleteTools
  =C:/Users/GARY/Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (296) : deleteChain
  dataS/scripts/vehicles/Vehicle.lua (1518) : preDelete
  dataS/scripts/utils/Utils.lua (1870) : oldFunc
  dataS/scripts/network/NetworkNode.lua (70) : delete
  dataS/scripts/network/Server.lua (34) : delete
  dataS/scripts/BaseMission.lua (299) : delete
  dataS/scripts/FSBaseMission.lua (537) : delete
  dataS/scripts/missions/mission00.lua (84) : delete
  dataS/scripts/events.lua (125) : delete
  dataS/scripts/gui/InGameMenu.lua (457) : OnInGameMenuMenu
  dataS/scripts/gui/InGameMenu.lua (614) : leaveCurrentGame
  dataS/scripts/gui/elements/ButtonElement.lua (191) : raiseCallback
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/Gui.lua (270) : mouseEvent
  dataS/scripts/main.lua (1857) : mouseEvent
 
Thanks, jdgp31

**Comment by Mogli12** [comment]
Hi,

You can ignore these warnings.

Regards,
Stefan

**Comment by Mogli12** [comment]
I close all FS17 problems.
