### ISSUE TITLE
gras mähen

### ISSUE THREAD

**Issue by iceman234de** [Mogli12/AIVehicleExtension#126]
Hallo, ist es möglich bei feldern die mit gras bepflanzt wurde auch mit aive abfahren zu können, habs versucht mit dem krone big M 500 , hat net so wirklich geklappt, weiß jetzt nicht ob das mal vorgesehen ist oder nicht.

gruß Iceman

**Comment by iceman234de** [comment]
Hallo, ist es möglich bei feldern die mit gras bepflanzt wurde auch mit aive abfahren zu können, habs versucht mit dem krone big M 500 , hat net so wirklich geklappt, weiß jetzt nicht ob das mal vorgesehen ist oder nicht.

gruß Iceman

**Comment by Mogli12** [comment]
Hi Iceman,

I will try to look at it. I think that you have to mow once around the area you want to work on and AIVE can do the inner part.

Regards,
Stefan

**Comment by Mogli12** [comment]
I close all FS17 problems.
