### ISSUE TITLE
AI Vehicle Extension FS17_holmerTerraDosT4_30

### ISSUE THREAD

**Issue by Marcel199013** [Mogli12/AIVehicleExtension#128]
Nabend, 

ich kann bei der Version 1.2 kein Rübenroder einstellen bzw auf Start drücken. 
Leider lässt sich der Helfer nicht einstellen, hoffe, dass es gefixt wird. 

Liebe Grüße

**Comment by Mogli12** [comment]
Hallo,

AIVE unterstützt keine Geräte mit Knicklenkung und fest montiertem Gerät.

Viele Grüße,
Stefan
