### ISSUE TITLE
problem with forage harvester

### ISSUE THREAD

**Issue by Crinouche** [Mogli12/AIVehicleExtension#129]
Hello
I have a problem with AIVE when I use a forage harvester.

When the field ends in a tight triangle, even selecting "backwards with curve" the forage harvester backs up against the trailer and crashes. The trailer does not maneuver to avoid the collision. In fact, the forage harvester works as if I had selected "back in a straight line", while I selected "back with curve".
I tried everything: change the steering angle ... but nothing to do.
I do not have this problem with combine harvesters.

Thank you,
Crinouche

**Comment by Mogli12** [comment]
Hi,

Can you please add a screen shot?

Thanks,
Stefan

**Comment by Mogli12** [comment]
Hi Crinouche,

I see. The AIVE is in 90° turn mode. Before turning it will check the direction of the next border. The vehicle will then go back in a 90° angle relative to the next border. I guess the angle between old and new border is just about 45°.

I am not sure what would be the best turn mode for your situation.

Regards,
Stefan

**Comment by Crinouche** [comment]
Hello,

Thank you for your reply. I will test a lower angle.
I didn't understand that an angle of 50% corresponded to 90 °

Thanks again
Regards,
Crinouche

**Comment by Mogli12** [comment]
Hi Crinouche,

The harvester has to go back in a rectangular direction relative to the direction after the turn. Currently, I see no alternative for it.

Maybe you can increase the distances in courseplay, e.g. a little more to the left and a little more to the front.

Regards,
Stefan

**Comment by Mogli12** [comment]
I close all FS17 problems.
