### ISSUE TITLE
AIVehicleExtension FS2019

### ISSUE THREAD

**Issue by Roby1164** [Mogli12/AIVehicleExtension#131]
Runs on some sites, version 2019, as here, http://www.farming2015mods.com/farming-simulator-19-mods/fs-19-other/fs19-aivehicleextension-v1-0-0-0/
But I do not think it's regular and working, as well as being released by you, can you confirm that it's not your job?
Roby

**Comment by Mogli12** [comment]
Hi Roby, 
This is not my job.
Regards, Stefan

**Comment by fudoido** [comment]
@Mogli12 any plans to make a fs19 version? or allow other creators to do so?
your mod has become one of the "must have" mods in fs games, the kind of functionality that should  be in the game originaly.

**Comment by omegaMV6** [comment]
Hello Mogli12,
maybe you "continue to work on this mod only for your own purpose" ;) just like you do with your VehicleControlAddon. 
I think many Users would be happy to have this mod in there mods folder.  I know about your problems with Giants but you don´t do it for them, you do it for people like me who never can create such a greatfull mod! 

Regards
Peter

And sorry for my bad english!

**Comment by iwan4672** [comment]
http://www.farming2015mods.com/farming-simulator-19-mods/fs-19-other/fs19-aivehicleextension-v1-0-0-0/
This is fake
Thanks Stefan

**Comment by Mogli12** [comment]
This is not fake:
https://github.com/Mogli12/AIVehicleExtension/blob/master/FS19_AIVehicleExtension.zip?raw=true

It is not yet working so well. But I was able to harvest a field in circular mode.

**Comment by Roby1164** [comment]
I'm trying it, but I can't get it to do anything ...
When I press Left CTRL + H, the writing below appears, it abilities the pointer, but nothing else ....
But the nice menu as it was in 17, isn't it any more?

**Comment by Mogli12** [comment]
LShift + H => Settings menu
H to start the hired worker

**Comment by iwan4672** [comment]
Goot work Mogli12. Applause :)
