### ISSUE TITLE
Stutter Issue After Unhooking Implement

### ISSUE THREAD

**Issue by stangman04** [Mogli12/AIVehicleExtension#134]
Noticed when I was using a 9RX that when I unhooked a plow or seeder that I was getting stutters while driving the tractor. Looking in my log file I see errors pointing to AIVehicleExtension (I was not using the mod while this was occuring).  I disabled the mod and restarted the map and no more stuttering when unhooking implements. I saw this a bit a combine as well but much worse with the tractor. @Mogli12 

[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/3025974/log.txt)

**Comment by cabmac** [comment]
hi... same here, i had this stuttering with the plough, i had to restart the game...

**Comment by stangman04** [comment]
> hi... same here, i had this stuttering with the plough, i had to restart the game...

Yeah the restarting the game fixes it but it comes back whenever you unhook a implement again. I just updated to the recent release and it still remains.

**Comment by Mogli12** [comment]
Please do NOT past the log.txt in the issue. Please upload the COMPLETE log.txt in gist. There is a button in the upper right corner.

I assume that you are not using the latest version.

**Comment by stangman04** [comment]
> Please do NOT past the log.txt in the issue. Please upload the COMPLETE log.txt in gist. There is a button in the upper right corner.
> 
> I assume that you are not using the latest version.

I am using the latest version. Attached the log
