### ISSUE TITLE
cruise control

### ISSUE THREAD

**Issue by Williwillswisse** [Mogli12/AIVehicleExtension#135]
If the harvester has to turn at an acute angle, AIVE will set the cruise control to 0 and the combine will break off. Then I have to turn up the cruise control again and restart the helper. No log entries.

**Comment by Mogli12** [comment]
Please upload the COMPLETE log.txt in GIST. Please upload a screen shot.

**Comment by Williwillswisse** [comment]
Hallo Stefan,
mit GIST bin ich nicht fit aber ich probiere es mal so.

Das Verhalten scheint mit den Abfahrern zusammen zu hängen. Ich habe einen Abfahrer mit Courseplay laufen. Tritt jetzt der Fall ein das an einer Feldecke der Abfahrer kommt, setzt der Drescher den Tempomat auf 0 (danach springt die Anzeige zwischen 0 und 2) und fährt rückwärts.
Ist der Abfahrer wieder weg bleibt der Tempomat auf 0 und der Drescher fährt ruckelnd wieder vorwärts.
Nach einem keinen Wegstück bleibt er dann stehen und wirft entweder die Meldung Blockiert, oder er bricht mit Unbekannt ab.

Aber sonst finde ich den Mod schon mal super und freue mich, dass du für den FS19 weiter machst.

[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/3026376/log.txt)
![K1600_fsScreen_2019_03_31_10_33_24](https://user-images.githubusercontent.com/47098121/55287152-a5ed1c80-53a5-11e9-970c-3a452e7949a4.JPG)
![K1600_fsScreen_2019_03_31_10_33_33](https://user-images.githubusercontent.com/47098121/55287153-a685b300-53a5-11e9-9cb9-a5b0d04aa8bc.JPG)
![K1600_fsScreen_2019_03_31_10_32_03](https://user-images.githubusercontent.com/47098121/55287154-a685b300-53a5-11e9-8b27-9bd684f17294.JPG)
![K1600_fsScreen_2019_03_31_10_32_15](https://user-images.githubusercontent.com/47098121/55287155-a685b300-53a5-11e9-946c-6612e72de4a6.JPG)
![K1600_fsScreen_2019_03_31_10_32_32](https://user-images.githubusercontent.com/47098121/55287157-a71e4980-53a5-11e9-998a-daf317abf838.JPG)
![K1600_fsScreen_2019_03_31_10_33_09](https://user-images.githubusercontent.com/47098121/55287158-a71e4980-53a5-11e9-95d2-4f48d204d1db.JPG)

**Comment by Mogli12** [comment]
Hast Du es mal ohne AAA_HiredHelperTool probiert? AIVE ändert eigentlich nichts am Tempomaten.

**Comment by Mogli12** [comment]
Falls das Problem auch ohne AAA_HiredHelperTool, dann drücke bitte auf "Reopen...".
