### ISSUE TITLE
Fehler beim einsteigen in Fahrzeug

### ISSUE THREAD

**Issue by Paul2510** [Mogli12/AIVehicleExtension#136]
Guten Morgen! Hab mir die neueste version heruntergeladen! Nach dem start des Spiel sobald ich in ein Fahrzeug einsteige kommt ein Fehler und das Spiel friert ein!
2019-03-31 07:25 C:/Users/Nemesis/Documents/My Games/FarmingSimulator2019/mods/FS19_AIVehicleExtension/AutoSteeringEngine.lua:6887: attempt to index field 'aiTurningRadiusLimitation' (a nil value)
2019-03-31 07:25 Error: Running LUA method 'update'.
LG

**Comment by Mogli12** [comment]
Bitte lade die KOMPLETTE log.txt in GIST hoch. In welches Fahrzeug bist Du eingestiegen?

**Comment by Paul2510** [comment]
Sorry muss mich korregieren es passiert schon nach dem start des game!

LG
[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/3026281/log.txt)

**Comment by 15lp** [comment]
habe das selbe Problen mein spiel hängt sich komplett auf

**Comment by 15lp** [comment]
[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/3026670/log.txt)

**Comment by Mogli12** [comment]
@15lp In der log.txt tauche FS19_AIVehicleExtension gar nicht auf.

**Comment by Paul2510** [comment]
Bei mir läufts wieder!! LG und vielen Dank für deine tolle Arbeit! Lg

**Comment by Mogli12** [comment]
Danke für die Rückmeldung.

**Comment by 15lp** [comment]
Ja war dann die falsche log ist der Fehler behoben?
