### ISSUE TITLE
Error AutoSteeringEngine

### ISSUE THREAD

**Issue by 3lronMcBong** [Mogli12/AIVehicleExtension#137]
Hello,
i have a problem with the new version.
V0.0.0.4 went without problems.

![fsScreen_2019_03_31_19_46_48](https://user-images.githubusercontent.com/5399009/55292791-326ffd00-53ef-11e9-8fe7-c9b9add389cd.png)

[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/3026966/log.txt)

**Comment by 3lronMcBong** [comment]
the next mistake as soon as I attach something
![Uploading fsScreen_2019_03_31_21_43_48.png…]()
[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/3027072/log.txt)

**Comment by Mogli12** [comment]
Please upload the COMPLETE log.txt in Gist.

**Comment by Paul2510** [comment]
Hi! Bei mir taucht das Problem mit Säämaschienen auf! LG
[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/3027086/log.txt)

**Comment by Mogli12** [comment]
@Paul2510 bitte prüfe bitte vorher, ob Du auch die aktuelle Version verwendest / please check if you already use the latest version

**Comment by Mogli12** [comment]
log is in #138

**Comment by Mogli12** [comment]
Unfortunately, Giants renamed almost every variable of the game. This makes is so difficult to migrate complex scripts to FS19. It should be fixed with version 0.0.1.7. But it is only a question of time until we reach the next renamed variable.

**Comment by Paul2510** [comment]
Sorry hab ich verschlafen! Danke!! :-)

**Comment by Mogli12** [comment]
@Paul2510 da Du ja die komplette log.txt hochgeladen hattest, konnte ich es schnell erkennen. Probier mal 0.0.1.7.

**Comment by 3lronMcBong** [comment]
thanks now it is running again.
except for this one

2019-04-02 20:22 Error in FS19_AIVehicleExtension.AutoSteeringEngine.checkTools2
2019-04-02 20:22 F:/Users/Jens Bender/Documents/My Games/FarmingSimulator2019/mods/FS19_AIVehicleExtension/AutoSteeringEngine.lua:7162: attempt to call method 'getAttacherVehicle' (a nil value)

**Comment by Paul2510** [comment]
Bei mir Läufts sehr gut! Das einzige was kommt ist 
FarmingSimulator2019/mods/FS19_AIVehicleExtension/AIDriveStrategyCollisionOtherAI.lua:91: attempt to index field 'currentHelper' (a nil value)
LG

**Comment by Mogli12** [comment]
Are these issues fixed now? I guess so. If not please reopen the issue. Thanks.
