### ISSUE TITLE
Error Also AutoSteeringEngine

### ISSUE THREAD

**Issue by Caamo** [Mogli12/AIVehicleExtension#138]
I really wanted to let you know about this, cause it's very important.
You can't connect any balers now.
Game freezes as soon as you connect the baler to tractor,  and your log is full of error:
2019-03-31 22:23 Error: Running LUA method 'update'.
2019-03-31 22:23 C:/Users/Caamo/Documents/My Games/FarmingSimulator2019/mods/FS19_AIVehicleExtension/AutoSteeringEngine.lua:8474: attempt to index a nil value

**Comment by Mogli12** [comment]
Please upload the COMPLETE log.txt in Gist.

**Comment by Caamo** [comment]
<script src="https://gist.github.com/Caamo/079f2e8586ba404c9b9a7f12dc2acacd.js"></script>

**Comment by Caamo** [comment]
[<script src="https://gist.github.com/Caamo/079f2e8586ba404c9b9a7f12dc2acacd.js"></script>](url)

**Comment by Caamo** [comment]
[https://gist.github.com/Caamo/079f2e8586ba404c9b9a7f12dc2acacd](url)

**Comment by Caamo** [comment]
Actually you can't connect anything to tractors, as much as I have tested now...
[log.txt](https://gist.github.com/Caamo/079f2e8586ba404c9b9a7f12dc2acacd)

**Comment by Caamo** [comment]
Actually you can't attach anything to tractors, as much as I have tested now...
[log.txt](https://gist.github.com/Caamo/079f2e8586ba404c9b9a7f12dc2acacd)

**Comment by Mogli12** [comment]
This error was already reported in #137
