### ISSUE TITLE
AIVehicleExtension

### ISSUE THREAD

**Issue by Fachputzer** [Mogli12/AIVehicleExtension#139]
Halloo Mogli ...habe folgendes Problem. Mir friert jedesmal das Spiel ein ,wenn ich mit einen Pflug arbeite ! Ohne dein Skript funktioniert es !!
[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/3030358/log.txt)

Vielen Dank mal !!!

**Comment by Fachputzer** [comment]
Hallo Mogli ...
vielen Dank jetzt funktioniert es super !!!!

Danke schön !!

**Comment by Mogli12** [comment]
Danke für die Rückmeldung
