### ISSUE TITLE
unknown specialization 'AIVehicleExtension'!

### ISSUE THREAD

**Issue by phil2sat** [Mogli12/AIVehicleExtension#140]
Error: Vehicle type 'xerionclass' has unknown specialization 'AIVehicleExtension'!
Error: Vehicle type '500generation' has unknown specialization 'AIVehicleExtension'!
Error: Vehicle type 'hookLiftTruckMan' has unknown specialization 'AIVehicleExtension'!
Error: Vehicle type 'MBTrac' has unknown specialization 'AIVehicleExtension'!
Error: Vehicle type 'Mitnahmestapler' has unknown specialization 'AIVehicleExtension'!
Error: Vehicle type 'T150kTO25' has unknown specialization 'AIVehicleExtension'!

Muss ich bei jedem Fremdmod irgendwie AIVehicleExtension reinwurschteln oder muss der Vehicletype in deinem Mod drinstehen? Habe reichlich Mods drin, die alle error free sind

Ansonsten funzt der Helfer genial, oh da fällt mir ein kann man die Wendemanöver etwas beschleunigen, der fährt bei mir so ca 5 km/h. Oder besser einstellbar je nach Fahrzeug

Danke
Phil2Sat

**Comment by Mogli12** [comment]
Bitte laden die komplette log.txt in Gist hoch.

**Comment by phil2sat** [comment]
https://gist.github.com/phil2sat/0f93168a930e7dce63d5e57791f970b0

**Comment by Mogli12** [comment]
Please check version 0.0.2.2. If the problem is fixed then close the issue please.
