### ISSUE TITLE
LUA Call Stack

### ISSUE THREAD

**Issue by powL889** [Mogli12/AIVehicleExtension#141]
Moin, danke erstmal für deine Arbeit an diesem tollen Mod. Hab ihn früher schon genutzt und freue mich, dass er für FS19 verfügbar ist! Danke.

Habe folgendes in der Log zu stehen.

> 2019-04-03 16:48 Warning (script): Unknown entity id 233552 in method 'unlink'.
> 2019-04-03 16:48 LUA call stack:
> 2019-04-03 16:48   =E:/Paul/Documents/My Games/FarmingSimulator2019/mods/FS19_AIVehicleExtension/AutoSteeringEngine.lua (6837) : unlink
> 2019-04-03 16:48   =[C] (4294967295)
> 2019-04-03 16:48   =E:/Paul/Documents/My Games/FarmingSimulator2019/mods/FS19_AIVehicleExtension/AutoSteeringEngine.lua (7360) : deleteNode
> 2019-04-03 16:48   =E:/Paul/Documents/My Games/FarmingSimulator2019/mods/FS19_AIVehicleExtension/AutoSteeringEngine.lua (6847) : deleteTools
> 2019-04-03 16:48   =E:/Paul/Documents/My Games/FarmingSimulator2019/mods/FS19_AIVehicleExtension/AIVehicleExtension.lua (283) : deleteChain
> 2019-04-03 16:48   dataS/scripts/vehicles/SpecializationUtil.lua (30)
> 2019-04-03 16:48   dataS/scripts/vehicles/Vehicle.lua (818) : raiseEvent
> 2019-04-03 16:48   dataS/scripts/utils/Utils.lua (393) : oldFunc
> 2019-04-03 16:48   dataS/scripts/network/NetworkNode.lua (68) : delete
> 2019-04-03 16:48   dataS/scripts/network/Server.lua (36) : delete
> 2019-04-03 16:48   dataS/scripts/BaseMission.lua (249) : delete
> 2019-04-03 16:48   dataS/scripts/FSBaseMission.lua (328) : delete
> 2019-04-03 16:48   dataS/scripts/utils/Utils.lua (381) : oldFunc
> 2019-04-03 16:48   dataS/scripts/missions/mission00.lua (69) : delete
> 2019-04-03 16:48   dataS/scripts/events.lua (145) : delete
> 2019-04-03 16:48   dataS/scripts/gui/InGameMenu.lua (389) : OnInGameMenuMenu
> 2019-04-03 16:48   dataS/scripts/gui/InGameMenu.lua (494) : leaveCurrentGame
> 2019-04-03 16:48   dataS/scripts/gui/base/TabbedMenu.lua (443) : buttonCallback
> 2019-04-03 16:48   dataS/scripts/gui/base/TabbedMenu.lua (478) : onMenuActionClick
> 2019-04-03 16:48   dataS/scripts/gui/elements/ScreenElement.lua (203) : onClickCancel
> 2019-04-03 16:48   dataS/scripts/gui/elements/GuiElement.lua (637) : inputEvent
> 2019-04-03 16:48   dataS/scripts/gui/base/Gui.lua (660) : inputEvent
> 2019-04-03 16:48   dataS/scripts/gui/base/Gui.lua (687) : notifyControls
> 2019-04-03 16:48   dataS/scripts/input/InputEvent.lua (100) : callback
> 2019-04-03 16:48   dataS/scripts/input/InputBinding.lua (3156) : notifyInput
> 2019-04-03 16:48   dataS/scripts/input/InputBinding.lua (2891) : updateInput
> 2019-04-03 16:48   dataS/scripts/main.lua (1835) : update

**Comment by Mogli12** [comment]
Da steht doch Warning..., oder?

**Comment by powL889** [comment]
Richtig. 
Dachte nur, ich melde es trotzdem mal, weil es einen Call Stack verursacht hat. :)

Danke!
