### ISSUE TITLE
aiTurningRadiusLimitation error

### ISSUE THREAD

**Issue by stangman04** [Mogli12/AIVehicleExtension#142]
Issue starts when I attach my plow and I start driving it makes my camera freeze in spot and makes the game become unresponsive. 

Attached my log.
[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/3041008/log.txt)

**Comment by Mogli12** [comment]
You are using version 0.0.1.2. If you find an error please verify that it still exists in the latest version, Thanks!
