### ISSUE TITLE
attempt to index field 'acDimensions' (a nil value)

### ISSUE THREAD

**Issue by phil2sat** [Mogli12/AIVehicleExtension#143]
C:/Users/phil2/Documents/My Games/FarmingSimulator2019/mods/FS19_AIVehicleExtension/AIVehicleExtension.lua:1153: attempt to index field 'acDimensions' (a nil value)
2019-04-04 08:42 Error: Running LUA method 'update'.

https://gist.github.com/phil2sat/44391aa1210ce985d6367b02f7dfd3cb

**Comment by phil2sat** [comment]
Das passiert auf der "Irgendwo in Thüringen II" Map, gerade auf der Map würde der Helfer richtig Sinn machen, da kein Feld rechteckig ist.

**Comment by Mogli12** [comment]
Bitte probiere Version 0.0.2.2. Falls das Problem gelöst ist, dann schließe bitte den Incident.
Danke

**Comment by gigilal** [comment]
I also get this message when running the mod on my mutiplayer server, and whn pressing "H" everything freezes.

**Comment by Mogli12** [comment]
@gigilal Sorry, but I do not get this. Please read the complete readme.MD. It is visible on the first page of AIVE. Please post the version number and upload the complete log.txt in Gist.

**Comment by gigilal** [comment]
VERSION NUMBER: v0.0.2.3
On dedicated / rented server only

2019-04-06 09:29 Error: Running LUA method 'update'.
2019-04-06 09:29 C:/Users/Espen/OneDrive/Dokumenter/My Games/FarmingSimulator2019/mods/FS19_AIVehicleExtension/AIVehicleExtension.lua:1151: attempt to index field 'acDimensions' (a nil value)
2019-04-06 09:29 Application exit request forced.

https://imgur.com/gnSbOdX
https://imgur.com/gnSbOdX

If you need WHOLE log.txt let me know

**Comment by Mogli12** [comment]
Plesae try version 0.0.2.4

**Comment by gigilal** [comment]
Its working, well done Mogli and what a good job.
