### ISSUE TITLE
Worker during mission?

### ISSUE THREAD

**Issue by MetalGovy** [Mogli12/AIVehicleExtension#144]
Hello,

With the missions system in FS19 is it supposed to that with the AiVehicleExtension enabled the hired worker does not work?

As i did try it with a beet harvester but the hired worker doesn't pop up?

Version 0.0.2.3 is used

**Comment by Mogli12** [comment]
The beet harvester has an articulated axis and this is not supported by AIVE if the tool (e.g. cutter) is not mounted on trailer or trailer_low attacher.
