### ISSUE TITLE
Detect harvester

### ISSUE THREAD

**Issue by gigilal** [Mogli12/AIVehicleExtension#145]
Hey. this is not a BUG or wrong in the script I am not sure where to write an suggestion (or if you want suggestions) but I will try it here.

When running multiple harvesters on one field, is it possible to make the harvesters detect each other if they come to close to each other? so that they do not crash into each other?

And the stay away distance to etc 15 to 20 meters? Or even make the distanst to be an option to us players to decide 

https://imgur.com/HJ3dqo1

Please guide me if this post can be posted another place.

**Comment by Mogli12** [comment]
The collision check is part of commit version 0.0.1.8. But I think it can only work in circular mode.
