### ISSUE TITLE
Don't detect collision on AutoDrive unloaders

### ISSUE THREAD

**Issue by Stephan-S** [Mogli12/AIVehicleExtension#149]
Currently the AutoDrive mode 'Unload combine' doesn't work with AI VehicleExtension due to the driver causing the combine to stop in a wide radius around them. So both, the parked drivers waiting to be called to the driver at the edge of the field as well as the active unloader stop the combine without the following modification in "AIDriveStrategyCollisionOtherAI:getDriveData":

			if bool and otherAI.spec_aiVehicle.isActive then
->			if bool and (otherAI.spec_aiVehicle.isActive and (otherAI.ad == nil or (otherAI.ad.isActive == false)))  then

That way active AutoDrive drivers won't be detected as collsion and can still use the "aiVehicle.isActive" flag.
By the way, the collision setting was turned off in the settings menu and the vehicle was registered as collision on a rather wide distance (~20 meters).

Greetings,
Stephan

**Comment by Mogli12** [comment]
Hi Stephan, Please check version 0.0.2.6. Thanks, Stefan

**Comment by Roby1164** [comment]
I tried, and now there seems to be no problem, the combine does not stop any longer, when it is near the trailer, and even after unloading it starts again ...

**Comment by Stephan-S** [comment]
As Roby said, it works great now. Thank you for the fast integration into your great mod :-)
