### ISSUE TITLE
Ropa und Holmer

### ISSUE THREAD

**Issue by Bigdaddy-KP** [Mogli12/AIVehicleExtension#150]
Moin, Die Rübenerntemaschinen lassen lassen sich nicht mit dem aive oder dem Standard Helfer nutzen.

**Comment by Mogli12** [comment]
Ja, das ist so, weil es Knicklenker sind.

**Comment by Roby1164** [comment]
But it is not possible to do that, the mod does not block at least the standard helper. Ok it can't work with AI, but at least you can use the standard one ...
