### ISSUE TITLE
Map freezes when using more than 3 combines

### ISSUE THREAD

**Issue by gigilal** [Mogli12/AIVehicleExtension#151]
Hi Stefan, Simply here just to help out with things I find while using the AIVE.
Which is a mod I love and would like to helpout as much as I can for you to make it even better.

I am more than grateful that you are making and updating this great mod.

I just started playing on "Midwest Horizon" And I own field 62 a pretty big field, I have done the field running AIVE 2 combines + 2 tractors ploging without anyproblems I can run multiple workers on AIVE and dont notice anything. But Yesterday I bought my 3rd harvester to simply get the field done more quickly, and then after a few minutes it started to freeze for upto 30-40 secounds and then it got back to "normal operation" and then freeze again and so on. The game never crashed. 

I tried to look for it into the logfile but I am not sure if detects when the server freezes ? 

If there is anything you want me to do or check up for you to get you a better feedback on this please let me know and I will gladly do it.

Looking forward to your response.

Thank you :)

**Comment by Mogli12** [comment]
Hi,

This is normal and happens (with less FPS drop) already with the normal hired worker. Just one example: https://forum.giants-software.com/viewtopic.php?f=955&t=145565

Regards,
Stefan
