### ISSUE TITLE
Frage nach einem neuen Feature

### ISSUE THREAD

**Issue by taylorfx** [Mogli12/AIVehicleExtension#152]
Hallo Stefan, 
ich hoffe an dieser Stelle mal die Frage nach einem neuen Feature stellen du dürfen ? :-)
an sich ist "aive" schon ziemlich perfekt. Was ich aber ganz gut finden würde, wäre ein Modus, der beim Erntestart nur einmal um das Feld herum erntet und dann den Modus  wechselt auf rauf-runter. Dabei würde ich mir gar keine besondere Bedienung und Parameter wünschen, da Startpunkt und Startrichtung schon alles bestimmen können. Quasi ein Moduswechsel, wenn der Drescher wieder auf die Startgerade eingebogen ist.
Ich bin auf eine Antwort gespannt.

Gruß

Frank

**Comment by Mogli12** [comment]
Hallo Frank,

AIVE kennt keine Bahnen und weiß auch nicht, ob man wieder am Startpunkt angekommen ist. AIVE schaut lediglich, ob auf einer Seite des Geräts nicht zu tun ist, und auf der anderen Seite genug zu tun ist. Falls keine Arbeit gefunden wird, dann wird eine 90° oder 180° Wende gemacht. Das war's.

Viele Grüße,
Stefan
