### ISSUE TITLE
Drescher werden nicht langsamer wenn Tank fast voll

### ISSUE THREAD

**Issue by SledgeHammer75** [Mogli12/AIVehicleExtension#153]
Hallo Stefan, 

die Drescher werden nicht langsamer, wenn sich der Füllstand 100% nähert. Sie fahren bis 100% Vollgas, heben dann das Schneidwerkzeug und bremsen. Dadurch bleibt je ein Fleck ungemähten Korns stehen. Dieser Fleck wird dann beim nächsten Umlauf korrekt erkannt und wirft dadurch den Helfer aus der Bahn.

**Comment by Mogli12** [comment]
Hallo,

mit Version v0.0.2.8 sollte es behoben sein.

Vielen Dank, Stefan
