### ISSUE TITLE
Kein Helfer beim Roder

### ISSUE THREAD

**Issue by FSM-Chefkoch** [Mogli12/AIVehicleExtension#154]
Moin,

wäre schön, wenn das noch hinzu käme.
Wenn ich den AI auf einem Roder aktiviere funktioniert kein Helfer mehr, nicht mal der Regulärer!

Mach weiter so :)

cu
Cheffe

**Comment by Mogli12** [comment]
Moin,

die Roder habe eine Knicklenkung. Das wird von AIVE nicht unterstützt.

Viele Grüße
