### ISSUE TITLE
Typo or not?

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Mogli12/AIVehicleExtension#156]
I get this error before I choose the turn mode.
```
Error: Running LUA method 'mouseEvent'.
FarmingSimulator2019/mods/FS19_AIVehicleExtension/AIVehicleExtension.lua:339: bad argument #1 to 'pairs' (table expected, got nil)
```
Found that in the file AIVehicleExtension.lua there are TWO entries AIVE_TURN_MODE_ 
But in the translation file there is an entry without underscore AIVE_TURN_MODE

**Comment by Mogli12** [comment]
There should be texts with AIVE_TURN_MODE_O etc.

**Comment by Gonimy-Vetrom** [comment]
There is no more error. It's good.
![fsScreen_2019_05_30_19_53_52](https://user-images.githubusercontent.com/8200153/58649597-2a600b00-8315-11e9-9d6c-956507c565f6.png)
But the explanation for the icon has not yet appeared. This is a situation where the turn mode has not been selected yet, but only launched the HUD.

**Comment by Mogli12** [comment]
The vehicle is not in AIVE mode  (1st icon from left). I guess it cannot calculate the turn mode in this situation.

**Comment by Gonimy-Vetrom** [comment]
With the choice of mode, everything is fine. I can click on the icon and it will change. That's just until I made a choice, it does not suggest that under this empty button.

**Comment by Gonimy-Vetrom** [comment]
If I add the string <text name="AIVE_TURN_MODE_" text="Form des Wendemanövers"/>(AIVE_TURN_MODE_ with underscore) to the translation file, then everything is fine.

**Comment by Mogli12** [comment]
Good idea
