### ISSUE TITLE
Mouse function stays cursor when tabbing from a vehicle with interface open to one with interface closed.

### ISSUE THREAD

**Issue by prjndigo** [Mogli12/AIVehicleExtension#158]
If I tab from a tractor/vehicle with the interface (ctrl-h) open to one with it closed the mouse cursor carries over and I have to open and close the interface to return to camera mode.

**Comment by Mogli12** [comment]
Version? log.txt?

**Comment by prjndigo** [comment]
Every version since mid FS17 through downloaded today, doesn't appear in log or you'd have found and fixed it.    Implement a "close on tab" or some per-vehicle value.

**Comment by Mogli12** [comment]
I cannot reproduce it.

**Comment by Mogli12** [comment]
I think this is a mod conflict. Can you reproduce it with FS19_AIVehicleExtension as only mod?
