### ISSUE TITLE
ctrl-h stops helper as well as closes window

### ISSUE THREAD

**Issue by prjndigo** [Mogli12/AIVehicleExtension#159]
when the helper has been running and I tab to another vehicle with the interface open and hit ctrl-h to close the interface, the helper is also cancelled

**Comment by Mogli12** [comment]
Version? log.txt?

**Comment by prjndigo** [comment]
0 0 3 1     does not appear in log, reading description indicates will not appear in log

**Comment by Mogli12** [comment]
I cannot reproduce it.

**Comment by Mogli12** [comment]
I think this is a mod conflict. Can you reproduce it with FS19_AIVehicleExtension as only mod?
