### ISSUE TITLE
AIVehicleExtension and Curspeplay conflicting

### ISSUE THREAD

**Issue by janka116** [Mogli12/AIVehicleExtension#160]
Hi,

Ther is some problems AIVehicleExtension and Courseplay .

When using combine  (AIVehicleExtension) and tractor and trailer (Courseplay) , AIVehicleExtension worker in combine stops working when ofloading in trailer and showing blocked buy any object , and if i get in tractor and stoping Courseplay AI driver then comebine  (AIVehicleExtension AI driver) starts again working .

AIVehicleExtension v0.0.3.1 

Courseplay v6.01.00227

Soory fro my bad ENG.

**Comment by Mogli12** [comment]
It does not work with patch 1.4 and I am not able to make it run again => project is stopped
