### ISSUE TITLE
Sorry sowas darf nicht sein

### ISSUE THREAD

**Issue by Mannie313** [Mogli12/AIVehicleExtension#161]
# 154
Sorry @Mogli12 .

Ein Mod wo bei einem fahrzeug das über den Originalen Helfer verfügt aber dein script diesen komplett aus diesem fahrzeug aushebbelt darf nicht sein. Dein script müsste es zulassen das der normale Giantshelfer bei diesen fahrzeugen funktioniert.

Ich werde diesen wieder bei mir deaktivieren weil es so keinen sinn für mich ergibt.

MFG Mannie313

**Comment by Mogli12** [comment]
Du kannst doch den alternativen Helfer jederzeit ausschalten. (LShift+H)
