### ISSUE TITLE
Not working with the new Patch 1.4

### ISSUE THREAD

**Issue by ole22143** [Mogli12/AIVehicleExtension#162]
Not working with the new Patch 1.4 had that issue that the alternative helper doesent do anything anymore since the patch

**Comment by Dusan4WD** [comment]
Same problem here, was working fine before parch.

**Comment by Roby1164** [comment]
I confirm, it doesn't work, on the contrary, pay attention that when it starts up it starts taking money from the account ...

**Comment by Roby1164** [comment]
I believe the problem is in this entry, in fact it is missing in the game: <text name = "AIVE_TURN_MODE"
![Screenshot_6](https://user-images.githubusercontent.com/24955554/59743244-f327ae80-926f-11e9-97e9-d65a5366eeb5.jpg)

**Comment by rickyralph89** [comment]
Same problem. Also when you do activate the helper you lose money extremely quickly but they don't actually do any work.

**Comment by Mogli12** [comment]
log.txt? -> [Gist](https://gist.github.com/)

**Comment by Mogli12** [comment]
Please try version 0.0.3.3

**Comment by Roby1164** [comment]
Ok, now it works ..... great

**Comment by Dusan4WD** [comment]
![20190620192927_1](https://user-images.githubusercontent.com/27623105/59870820-878c3100-9396-11e9-8e26-0c9e2c18e20e.jpg)

**Comment by Dusan4WD** [comment]
![20190620192927_1](https://user-images.githubusercontent.com/27623105/59871007-d8038e80-9396-11e9-8eda-ca3167ab4afc.jpg)

On some places during corn harvest it makes these skips.
Also when combine stops when bunker is full, makes small skip when starts again.

Thanks for fixing mod for us! Respect!

**Comment by Roby1164** [comment]
> ![20190620192927_1](https://user-images.githubusercontent.com/27623105/59871007-d8038e80-9396-11e9-8eda-ca3167ab4afc.jpg)
> 
> On some places during corn harvest it makes these skips.
> Also when combine stops when bunker is full, makes small skip when starts again.
> 
> Thanks for fixing mod for us! Respect!

I think that the problem is more than anything else, due to the vehicity of the combine and / or the distance of the trailer, if too close, or if the combine is too fast, as in some Mods, then it creates that problem, but due to the fact that, when it is full, it takes too long to stop, and when it starts again it has skipped a piece of culture, not to use the AIVE ...

**Comment by Denhalen** [comment]
With version 0.0.3.3 the combine harvester doesn't maintain a straight line while going in circle mode. He drives in a slight angled line, which can result in him ending up too much to the side of yet to harvest crop. 
I haven't discovered this issue with a tractor and a cultivator. Just the combine. While he starts with a green indicator.

**Comment by ReallyNotBad** [comment]
> With version 0.0.3.3 the combine harvester doesn't maintain a straight line while going in circle mode. He drives in a slight angled line, which can result in him ending up too much to the side of yet to harvest crop.
> I haven't discovered this issue with a tractor and a cultivator. Just the combine. While he starts with a green indicator.

I experienced the same issue only with combines.
But tractors are also a bit buggy. they driving slower (7km/h)  than the Giants Helper (18km/h)

**Comment by brownsfan12** [comment]
With version 3.7 I am still having issues that the AI doesn't maintain a straight line when going in circle mode, by the end of a long row the AI is only taking maybe a 1/8 of the row, I notice that the information bar is flashing between green and yellow really fast. It also doesn't top speed.

**Comment by Mogli12** [comment]
I agree that it is not working. But I cannot fix it. AIVehicleUtil.getAIFruitArea or AIVehicleUtil.getAIDensityHeightArea seem to make problems, which I cannot fix.

=> please do not use AIVE anymore

**Comment by Mogli12** [comment]
As workaround you can now use the standard hired worker or only AIVE workers of the same kind. So you can have multiple combines at the same time but not one combine and one tractor with cultivator.

**Comment by brownsfan12** [comment]
Thanks, I reverted to steam patch 1.3 and it’s been working great as well...

**Comment by HacMacDynamite** [comment]
Hey, first of all thank you for your work.
Is AIVE now working with Patch 1.4? I don`t want to play without it...

**Comment by brownsfan12** [comment]
> Hey, first of all thank you for your work.
> Is AIVE now working with Patch 1.4? I don`t want to play without it...

I have not tested it, I am still on 1.3 and having no issues.

**Comment by Mogli12** [comment]
Please test the latest version. It should work with patch 1.4

**Comment by Denhalen** [comment]
Currently running a small test with a rectangle field. The combine goes in a straight path, keeping the color green.  Seems patch 1.4.1 helped your mod a great deal. Thanks for updating this mod. This makes harvesting good again, for me. Haven't tried a misshapen field, as my current map has none.

**Comment by brownsfan12** [comment]
> Please test the latest version. It should work with patch 1.4

Mogli:
I have been testing for 2 days now and here is what I have found:
 - Rectangular Fields; Everything runs great haven't had any issues.
 - Circular Fields; Had 2-3 times where my workers would slowly run off course and eventually stop, but after getting them on course again it fixed the issue and didn't do it again.
The biggest "issue" (not a deal-breaker) is if the worker comes close to any point of the fiel that isn't straight it will slow down significantly. For example: if regular work speed is 15 mph the worker will slow down to 5-6 mph if on any curvature area of the field, but will speed up after getting to a straight run.

Thanks for all the effort you put into this Mod, I couldn't farm without it.

Thanks,

**Comment by Mogli12** [comment]
Hi,

AIVE slows down if it has problems to find a good path. This was already the case in older versions. 

The problem is that AIVE is called in every frame. So there are 16.7 ms between two frames at 60 FPS. 15 mph are about 6.67 m/s. This means that the vehicle will move 11 cm per frame or 0.36 ft. That is why the AIVE slows down the vehicle in difficult situations.

Regards,
Stefa

**Comment by brownsfan12** [comment]
Mogli12,
Thanks for clarifying, that makes sense.

I haven't had any issue after playing over 24 hours! 👍 

Thanks!

**Comment by brownsfan12** [comment]
Mogli12,
I noticed that the AIVE doesn't work for Cotton Harvesters. Is this a bug or intended?

Thanks,
