### ISSUE TITLE
Erntemaschinen laufen nur noch 7 km/h

### ISSUE THREAD

**Issue by schudor** [Mogli12/AIVehicleExtension#164]
Moin allerseits,
seit dem FS19-Update auf 1.4 laufen die Erntemaschinen nur noch mit 7 km/h und nicht mit der Geschwindigkeit, die in den entsprechenden xml.dateien der Maschinen angegeben sind.
Es wäre nett, wenn das korrigiert werden könnte.
Gruß
Bernd
PS: Mein System: iMac; MacOS 10.14.5; FS19 for Mac, AIVehicleExtension 0.0.3.6

**Comment by Mogli12** [comment]
Hallo Bernd,
AIVE reduziert die Geschwindigkeit automatisch auf 7 km/h, wenn es Probleme mit der Berechnung hat. Ich habe diese Problem aber nicht. Und mit so wenig Details kann ich dazu auch nichts sagen. Bitte schick mal die komplette log.txt (-> [Gist](https://gist.github.com/)) und mehrere ScreenShots.
Danke,
Stefan

**Comment by schudor** [comment]
![Erntemaschine-7-kmh](https://user-images.githubusercontent.com/46317064/60187699-4a102380-982e-11e9-9204-34496ef1a9ca.jpg)
[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/3330472/log.txt)

**Comment by ReallyNotBad** [comment]
Hi;

ich habe das selbe Problem.

![20190626161107_1](https://user-images.githubusercontent.com/52174629/60188044-ee926580-982e-11e9-885b-2e95fc0e8485.jpg)
![20190626161131_1](https://user-images.githubusercontent.com/52174629/60188112-0e298e00-982f-11e9-90d3-b9f56ae2b9a7.jpg)
Ist auf allen Stufen der Präzision so. Immer 7km/h. Auch Traktoren mit z.b. Sämachine.
Auch steuert der Drescher immer weiter aus dem Feld raus und die Linie wird grau. Liegt auch vielleicht an den Berechnungsproblemen die du angesprochen hast.

Im einem zweiten Save habe ich nochmal die Ravenport genommen und nur deinen Mod aktiv:
![20190626162008_1](https://user-images.githubusercontent.com/52174629/60188414-855f2200-982f-11e9-9780-4526c3694b53.jpg)

Selbiges Problem auch wieder 7km/h und auf Abwegen. Er fährt nur ca 20m mit dem grünen Strich.

Log mit allen Test Saves und Szenarien aus den Screenshots
https://gist.github.com/ReallyNotBad/91e29a86dea96b5da8d05d000b3248de

Hoffe ich kann dir damit weiter helfen. Wenn du noch mehr Infos brauchst kann ich dir die auch hochladen.

Grüße
Tim

**Comment by Mogli12** [comment]
Ich habe ein neues Spiel begonnen und konnte es jetzt reproduzieren.

**Comment by ReallyNotBad** [comment]
Sehr gut.
Solltest du dennoch noch Hilfe oder Infos brauchen, melde dich.

Danke für die gute Arbeit und den tollen Mod.

**Comment by Mogli12** [comment]
Es scheint, dass manchmal nach einer Kurve AIVE nicht mehr aus dem Suchmodus heraus kommt. Das müsste eigentlich nach wenigen Sekunden passieren. Eventuell ist es mit 0.0.3.7 besser.

**Comment by ReallyNotBad** [comment]
Dank für die schnelle Rückmeldung.
Leider sind beide beschriebenen Fehler auch in der 0.0.3.7 vorhanden.
- Alle Fahrzeuge maximal 7km/h
- Drescher berechnet nach 20m den Feldrand nicht mehr. (Driftet vom Feld ab)

**Comment by Mogli12** [comment]
So lange die Schrift im Hud nicht grün wird, fährt das Fahrzeug nur 7 km/h. Da diese Diskussion aber nirgendwo hin führt, mache ich den Incident jetzt zu.

**Comment by ReallyNotBad** [comment]
Hi Stefan,

Ich will nur ungern die Diskussion wieder eröffnen, will aber auch nicht ein neuen issue auf machen.
Liegt es an einem Fehler von meiner Seite das ich die Schrift eben nicht grün bekomme? Ein Kollege von mir kämpft mit selbigen Problem

Danke nochmal

Grüße
Tim

**Comment by Mogli12** [comment]
Ich vermute, dass es an der Karte oder einem Mod-Konflikt liegt.
