### ISSUE TITLE
AutoSteeringEngine.lua:7066: attempt to index global 'spec_aiImplement' (a nil value)

### ISSUE THREAD

**Issue by stangman04** [Mogli12/AIVehicleExtension#165]
Receiving this error when trying to use a db60 planter. Attached log.

[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/3364281/log.txt)

**Comment by Mogli12** [comment]
I guess db60 planter is the FS19_JD_DB60?

**Comment by stangman04** [comment]
That is it

**Comment by stangman04** [comment]
Latest version appears to have resolved my issue. Thanks.
