### ISSUE TITLE
0.0.4.5 harvester loses crop-edge and drifts left from crop

### ISSUE THREAD

**Issue by prjndigo** [Mogli12/AIVehicleExtension#167]
Bizon Super Z056 Clone combine (spec/mechanical same), also happens with stock game combines in FS19-1.4.1

Once the harvester completes a turn (with any turn type) it lines up and then suddenly stops sensing the location of crop and continues on without turning like how it finishes the end of an edge before it implements a turn.

![fsScreen_2019_07_11_10_41_28](https://user-images.githubusercontent.com/35308408/61060396-74361980-a3c8-11e9-9c47-9082198824b5.png)
 It ends up cutting a 5° from aligned course till it stops.

no output to log, no errors in log, it simply failed to look for crop when it resumed from unloading

!   There is a distinct difference in behavior of the "autosteer" function and the AIVeEx automatic function both in rapidity and accuracy.   The Autosteer is NOT having errors.

!  Error is symmetrical, drifts right when set to run left around field.

**Comment by Mogli12** [comment]
I know that AIVE is not working anymore since patch 1.4.

**Comment by prjndigo** [comment]
issue resolved with 0.0.4.8
