### ISSUE TITLE
0.0.4.5 harvestor fails to see crop after turn, harvests into field momentarily then corrects

### ISSUE THREAD

**Issue by prjndigo** [Mogli12/AIVehicleExtension#168]
fs19-1.4.1
![fsScreen_2019_07_11_10_39_15](https://user-images.githubusercontent.com/35308408/61060468-90d25180-a3c8-11e9-9787-91417d358774.png)

Harvester made turn at corner and continued rate of turn past alignment with crop then engaged in harvesting, after visible cut into field the harvester then suddenly realized it was nosed-into field and backed-up out of crop, turned to align with re-detected edge and continued on normally

no output to log, no errors in log; image was taken when AI said "wait a minute, where's the crop??"

**Comment by Mogli12** [comment]
I know that AIVE is not working anymore since patch 1.4.

**Comment by prjndigo** [comment]
issue resolved with 0.0.4.8
