### ISSUE TITLE
0.0.4.5 harvester suddenly does donut, stops because can't see crop

### ISSUE THREAD

**Issue by prjndigo** [Mogli12/AIVehicleExtension#169]
fs19-1.4.1

![fsScreen_2019_07_10_09_49_51](https://user-images.githubusercontent.com/35308408/61060635-d858dd80-a3c8-11e9-8dfa-060998f8e49c.png)

Title says all, it spun almost "xbox" then stopped, when I started it and nosed into the crop edge it completed a full circuit of the field and harvested right through the circle and tuft without error

![fsScreen_2019_07_10_09_54_23](https://user-images.githubusercontent.com/35308408/61060754-0ccc9980-a3c9-11e9-8930-81f08dd2b85c.png)

no output to log, no errors to log

**Comment by Mogli12** [comment]
I know that AIVE is not working anymore since patch 1.4.

**Comment by prjndigo** [comment]
Issue resolved with 0.0.4.8
