### ISSUE TITLE
V0.2.0.0 combine issue (detected on CR10.90 equipped flex45)

### ISSUE THREAD

**Issue by Sythos** [Mogli12/AIVehicleExtension#17]
Version in sbj need each combine to set "reverse work mode" manually before, or the combine will drift outside the field. Maybe due previous point, the turning not work properly in any of 3 options (external rounds cause a 315° degree turn, heading the combine outside the field; back&turn cause the combine move back on a line without turn, this made the combine destroy the crop while turn moving forward, same the 3 movement turn)

not get time to test other headers or combine

**Comment by BrandonD01** [comment]
I am getting the same issue with the Massey Ferguson combine, will follow the line until turn.  Then the combine will make large circle even with back-up mode selected, or will continue straight when turn is to left but rest of field is to right.  Really loved the Autocombine in 15, hope this mod can get back to working as well as it did in 15.  Especially with the how much I dislike the new hired helpers in 17.

**Comment by sootysax** [comment]
you realize this mod is in beta right?

**Comment by Mogli12** [comment]
Hi,
Versions 0.1.x.x were more or less just conversion of AutoTractor. Now with Version 0.2.0.0 on I adjusted the mod to the new AIVehicle structure in FS17. The main effort was to separate the normal driving from the turning maneuver. Now I can start to implement special maneuvers for combine harvesters.
So you have to wait some time. I just started...
Regards

**Comment by Sythos** [comment]
@sootysax yes i know, is exactly for this purpose i've reported, due it's a beta is the right time to help Mogli pointing all bugs to made him able to fix everything, otherwise what should people do? sit and just blame "not work!!!"?

**Comment by sootysax** [comment]
@sythos sorry i was referring to the "i hope we can get it working like it did in fs15" comment.   obviously this is in the earliest stage of beta, and its not going to work perfect at all

**Comment by BrandonD01** [comment]
Yes, I understand its beta version.  And I'm not trying to sound like the mod is crap, everything else other wise works great.  It is a great mod so far, and I'm sure the creator will get it fixed, I was just letting him know a little more detail of the errors I'm having as well while it's still in beta.
