### ISSUE TITLE
Helper Stopping

### ISSUE THREAD

**Issue by stangman04** [Mogli12/AIVehicleExtension#171]
Having an issue that the harvester is stopping (helper stopping) when my semi pulls up to offload the combine. It only occurs when the offloading trailer is being controlled by courseplay. When I stop courseplay the combine continues. Is there anything that can be tuned? I toggle the "collision check [on]" to off but it has no impact.

**Comment by prjndigo** [comment]
iirc courseplay changes some game parameters so would be the cause of the stoppage?

**Comment by stangman04** [comment]
> iirc courseplay changes some game parameters so would be the cause of the stoppage?

No idea, just annoying having to stop courseplay each time the offload finishes so the harvester can move

**Comment by janka116** [comment]
> 
> 
> Having an issue that the harvester is stopping (helper stopping) when my semi pulls up to offload the combine. It only occurs when the offloading trailer is being controlled by courseplay. When I stop courseplay the combine continues. Is there anything that can be tuned? I toggle the "collision check [on]" to off but it has no impact.

The same problem i have.

**Comment by Mogli12** [comment]
Please test AIVE 0.0.5.0
