### ISSUE TITLE
Mouse arrow stays shown when tabbing to another vehicle

### ISSUE THREAD

**Issue by FuturisticMC** [Mogli12/AIVehicleExtension#175]
When i tab from a vehicle with the interface open the Mouse arrow stays shown when tabbing to another vehicle or when I exit. It is not a mod conflict I have enabled only AIVE and it still happens.

**Comment by Mogli12** [comment]
Sorry, but I cannot reproduce it.

**Comment by FuturisticMC** [comment]
Base game, no other mods except AIVE
https://vimeo.com/351826839

**Comment by Mogli12** [comment]
Hi,
It is fixed with 0.0.5.2
Regards
