### ISSUE TITLE
Not faster then 7km/ph with Seasons

### ISSUE THREAD

**Issue by Tijson** [Mogli12/AIVehicleExtension#176]
Hi,

Since im using Seasons the AI doesnt go any faster then 7km/ph. Any fix for this?

Thnx in advance.

**Comment by Mogli12** [comment]
No screen shot, not detailed problem description, no log.txt => no fix

**Comment by Tijson** [comment]
> No screen shot, not detailed problem description, no log.txt => no fix

![fsScreen_2019_08_06_09_29_21](https://user-images.githubusercontent.com/33165965/62520021-faf5df00-b82c-11e9-822c-21da42b15eb4.png)
[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/3470890/log.txt)
