### ISSUE TITLE
doesn't see the field boundary

### ISSUE THREAD

**Issue by MacedonskyAlex** [Mogli12/AIVehicleExtension#177]
At such corners of the field, AI does not know where to go and stops
![fsScreen_2019_08_08_12_27_41](https://user-images.githubusercontent.com/52257646/62691807-16e9b400-b9d8-11e9-9251-043a9104bda2.png)

**Comment by Mogli12** [comment]
Hi,

It is not clear, which version of AIVE you use, if you were in circular or up/down mode, if headland was activated, etc.

What do you think should I do with this screen shot?

Regards
