### ISSUE TITLE
Lifts implement in the middle of a straight course

### ISSUE THREAD

**Issue by dudethekid** [Mogli12/AIVehicleExtension#18]
I've noticed that while harvesting and fieldwork seems to work fine, seeding and fertilizing has some issues. Mainly that they will lift/turn off the implement in the middle of a straight course or when switching from seeded/fertilized ground to cultivated ground it won't turn on. It doesn't have any errors or warnings pop up in the log.
Thanks for the great work! Keep it up.

**Comment by Mogli12** [comment]
I disabled the "raise no fruits" function
