### ISSUE TITLE
works Perfect but two problems

### ISSUE THREAD

**Issue by Randywes** [Mogli12/AIVehicleExtension#182]
the v0.0.5.5 version works fine for me but i found 2 issues 
1, In cricle mode it turning in small radius It would be better with turning radius options
![Farming Simulator 19 Screenshot 2019 08 12 - 07 25 10 17](https://user-images.githubusercontent.com/54022592/62856110-ad7de400-bcfc-11e9-902e-f9dfd06dc001.png)

2. When you run more than two tools it causes lags drop fps

**Comment by Mogli12** [comment]
Hi,

Please make the same screen shot with 0.0.5.6.

Thanks

P.S.: the FPS drops are normal

**Comment by Randywes** [comment]
Yeah its turning much better thanks alot for fixing this issue 👍
![Farming Simulator 19 Screenshot 2019 08 13 - 14 06 21 52](https://user-images.githubusercontent.com/54022592/62937912-96132980-bdd6-11e9-9a7e-d13f8db4f1e0.png)
![Farming Simulator 19 Screenshot 2019 08 13 - 14 21 16 26](https://user-images.githubusercontent.com/54022592/62937958-b2af6180-bdd6-11e9-8f63-56e9e34126ae.png)

Thanks.

**Comment by Mogli12** [comment]
Great and thanks for the screen shots!
