### ISSUE TITLE
fs19 0.0.4.8  helper in around mode needs about 0.6m longer detection reach on combine

### ISSUE THREAD

**Issue by prjndigo** [Mogli12/AIVehicleExtension#183]
When completing a near-but-less than 90° turn on field in "around mode" the combine harvester either overshoots start of turn breadcrumb point or needs additional forward crop detection:   Harvester stops while lined up with crop and just short of detecting crop.

Happens in all turn forms.

Code is looking good on much now.

**Comment by Mogli12** [comment]
Can you please at least at a screen shot?

**Comment by Randywes** [comment]
It happens to me too sometimes. the combine stops in strting line  i did screen shot
![Farming Simulator 19 Screenshot 2019 08 14 - 16 10 12 62](https://user-images.githubusercontent.com/54022592/63074012-08e5e700-bf34-11e9-80b4-023b18352e28.png)
![Farming Simulator 19 Screenshot 2019 08 14 - 16 45 21 82](https://user-images.githubusercontent.com/54022592/63074036-2adf6980-bf34-11e9-93e1-fc693c47a40d.png)

**Comment by Mogli12** [comment]
Ah ok. it seems that the time out period is too short.

**Comment by Mogli12** [comment]
Please try version 0.0.5.7

**Comment by Randywes** [comment]
version 0.0.5.7 working much better so far. buI i found one more issue when you run two or more 
 the space between is too small in the middle when one turns its Blocking
![Farming Simulator 19 Screenshot 2019 08 15 - 18 18 14 56](https://user-images.githubusercontent.com/54022592/63107315-6c503300-bf8d-11e9-89ad-7c694b98c9e6.png)

**Comment by prjndigo** [comment]
Still doing the short-stop in 0.0.5.7

![fsScreen_2019_08_15_22_02_56](https://user-images.githubusercontent.com/35308408/63151063-9712a980-bfd6-11e9-863b-4bb565cb2dee.png)
![fsScreen_2019_08_15_22_03_12](https://user-images.githubusercontent.com/35308408/63151066-9843d680-bfd6-11e9-96d5-f78651cfbc18.png)

**Comment by prjndigo** [comment]
0.0.5.7 additional screenshot machine stopped while I was away, when I entered vehicle and pressed H to restart it went right in and continued working
![fsScreen_2019_08_16_04_28_17](https://user-images.githubusercontent.com/35308408/63154409-89f9b880-bfde-11e9-826d-49cfd347c541.png)

**Comment by Mogli12** [comment]
Hi,
This can be a problem with courseplay.
Regards,
Stefan

**Comment by prjndigo** [comment]
Suddenly today on the same field there's no problems and the harvester ran perfectly without massive lag.  NO change in any mods occured between gaming sessions.   Perceptibly the game itself seems to be working better.

It wasn't courseplay.  I'm betting the game version number changed XD
