### ISSUE TITLE
0.0.5.8 code behavior observation: detection of headders as obsticles

### ISSUE THREAD

**Issue by prjndigo** [Mogli12/AIVehicleExtension#188]
On two mod harvesters I've had situations on post-unloading return to field where the AI.V.E. has claimed to be blocked by the harvester's own header.  I have the feeling (instinct) that this behavior may be connected to the failure to re-enter fields after turns with the possibility that if the AI.V.E. is no longer aware that it is operating on the dimensions of the header it may be attempting to complete the re-entry to crop erroniously with the actual vehicle body.

Mod harvesters are the "Fortschritt KS6" root harvester and the "Don 680"  forage harvester.

But the behavior and positioning of the failures is visually identical to the harvester refusal/failures with standard game harvesters.

The solution I found to get these systems moving again is to detach the header and re-attach it.  A classic "have you tried unplugging and then plugging it back in again".   Which indicates the code somehow dropping the correct order of machinery.

While not parallel to the harvester unexpected stop, it is using the same code and may indicate the disconnect in the code.

**Comment by prjndigo** [comment]
This event - being blocked by its own header - seems to be related with an overflow of objects, it seems to be in relation to objects close to the machine during the stages of a turn.

**Comment by Mogli12** [comment]
Hi,

AIVE uses the same collision detection as the normal hired worker. Can you reproduce it with a standard vehicle. In some cases the collision box of the header is too big,

Regards
