### ISSUE TITLE
Distance keeper in the middle of two tools is too short

### ISSUE THREAD

**Issue by Randywes** [Mogli12/AIVehicleExtension#189]
Hallo Stefan.
I had a small problem not critical but If you can fixit It would be much better
when I start working with two or more tractors or combines in one field 
there is not enough distance when one turns and it blocks each other
![Farming Simulator 19 Screenshot 2019 09 19 - 01 55 16 80](https://user-images.githubusercontent.com/54022592/65276082-b188f700-db2f-11e9-9867-797f25fd7b76.png)
![Farming Simulator 19 Screenshot 2019 09 19 - 01 56 55 15](https://user-images.githubusercontent.com/54022592/65276125-c6fe2100-db2f-11e9-9de6-ddd51b0f0f20.png)

**Comment by Mogli12** [comment]
I think I can increase the distance. If there is enough space than the turn in shape of a loop might work better.

**Comment by Randywes** [comment]
Yeah i tested all conditions (O shape turn, straight revers, reverse with curve,) and all the distances are more or less same, anyway it's not a big issue for me, but I think if it's not complicated, it would be better increase the distances.

**Comment by Randywes** [comment]
![Farming Simulator 19 Screenshot 2019 09 22 - 08 06 55 29](https://user-images.githubusercontent.com/54022592/65382664-439d2500-dd13-11e9-9960-fbd8f49e9e8b.png)
![Uploading Farming Simulator 19 Screenshot 2019.09.22 - 08.27.23.07.png…]()

**Comment by Randywes** [comment]
![Farming Simulator 19 Screenshot 2019 09 22 - 08 06 55 29](https://user-images.githubusercontent.com/54022592/65382696-83fca300-dd13-11e9-86aa-97b560f70b91.png)

**Comment by Randywes** [comment]
![Farming Simulator 19 Screenshot 2019 09 22 - 08 27 23 07](https://user-images.githubusercontent.com/54022592/65382706-9f67ae00-dd13-11e9-8a73-74ea5f38f567.png)

**Comment by Mogli12** [comment]
Did you try version 0.0.6.0 or higher? If yes and if it does not yet work please re-open this issue.
