### ISSUE TITLE
Fehler in der Neuen Version

### ISSUE THREAD

**Issue by Bandesss** [Mogli12/AIVehicleExtension#191]
Hallo bekomme den Fehler 
Error in FS19_AIVehicleExtension.AutoSteeringEngine.checkTools2
[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/3677565/log.txt)

**Comment by Mogli12** [comment]
Hallo,
ich gehe mal davon aus, dass das Problem mit v0.0.6.1 gelöst wurde.
LG
