### ISSUE TITLE
Error: Running LUA method 'update' auf der Hof Bergmann 1.0.0.4

### ISSUE THREAD

**Issue by wallsingham** [Mogli12/AIVehicleExtension#195]
Lässt sich dieser Fehler beheben? Was brauchst Du noch für Angaben?
Das Spiel hängt sich mit dieser Fehlermeldung an bestimmte Stellen der Map, reproduzierbar auf.

2019-10-18 22:34 C:/Users/user/Documents/My Games/FarmingSimulator2019/mods/FS19_AIVehicleExtension/AutoSteeringEngine.lua:625: attempt to index a nil value
2019-10-18 22:34 Error: Running LUA method 'update'.

**Comment by Mogli12** [comment]
Ich benötige immer die komplette log.txt. Woher soll ich sonst wissen, welche Version Du verwendest? Ein Screen Shot wäre auch immer hilfreich, selbst bei so einer Log-Meldung.

**Comment by wallsingham** [comment]
Hallo Stefan,
ersteinmal vielen Dank für die tolle Mod. Ich habe sie schon im 17-ner sehr gern benutzt. 
Anbei die log.txt und zwei Screenshots. Ich probiere jetzt mal das das Mähen auf Feld 16 bei der Hof Bergmann 1.0.0.4
Viele Grüße
Hektor
![fsScreen_2019_10_19_15_04_21](https://user-images.githubusercontent.com/56741972/67145656-6cb5c480-f283-11e9-94dd-060987440ec5.png)
![fsScreen_2019_10_19_15_05_11](https://user-images.githubusercontent.com/56741972/67145657-6cb5c480-f283-11e9-86ba-d428bdc5454e.png)
[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/3746703/log.txt)

**Comment by wallsingham** [comment]
beim Grasmähen auf Feld 16 schaft er sogar diese sehr scharfe Kurve ohne Fehlermeldungen. 
Lediglich am Anfang als die zu mähende Fläche vor ihm unregelmäsig war, kam er nicht klar und hat ein paar Mal genau die obige Fehlermeldung gebracht.
Nachdem ich händisch die Spur begradigt habe und er sauber loslegen konnte, gings problemlos weiter.
![fsScreen_2019_10_19_15_45_26](https://user-images.githubusercontent.com/56741972/67146131-1eef8b00-f288-11e9-8f72-ed675c983235.png)

**Comment by Mogli12** [comment]
Was genau hast Du gemacht, so dass es zu den Fehlermeldungen kommt? Passiert das nach dem Speichern? Oder ist ein bestimmtes Fahrzeug betroffen? Hast Du den Helfer gerade gestartet oder trat das erst später auf?

**Comment by wallsingham** [comment]
Es waren untenstehende Geräte im Einsatz:
Drescher + Schneidwerk:
"F19_ClaasLexion700Serie_v4" filename="$moddir$F19_ClaasLexion700Serie_v4/Vario1200.xml"
modName="F19_ClaasLexion600Series" filename="$moddir$F19_ClaasLexion600Series/Lexion650.xml"
Traktor + Mähwerk:
1. filename="data/vehicles/fendt/fendt700/fendt700.xml"
2. "FS19_Mowerpack" filename="$moddir$FS19_Mowerpack/xml/poettingerNovaCatX8.xml"
3. filename="data/vehicles/poettinger/poettingerNovaCat301/poettingerNovaCat301.xml"


Der Fehler tritt an bestimmen Stellen des Feldes auf. Ich sehe keinen Zusammenhang mit dem Speichervorgang oder mit der bereits abgelaufenen Spielzeit. 
Für mich sieht es so aus, als dass er bei ungeraden / unregelmäßigen Kanten des Frucht-Bereiches den Fehler produziert. Ich werde nachher mal testen wie es sich verhält wenn ich die Genauigkeit umstelle oder das Ganze auf einer anderen Map mit ähnlicher Kantenführung mache. Ich habe die Hof Bergmann 1.0.0.4 erst seit kurzem und es ist denkbar dass es auch an der Karte liegt.

**Comment by Mogli12** [comment]
Das passiert also mitten drin, wenn der Helfer schon länger arbeitet. Das hilft mir bereits.

**Comment by Mogli12** [comment]
Ich konnte das Problem zwar nicht reproduzieren. Aber ich hoffe, dass ich den Fehler trotzdem beheben konnte.

**Comment by wallsingham** [comment]
Wow. Danke erstmal. Ich werde morgen testen. Der Fehler trat übrigens bei verschiedenen Versionen auf. v0.0.4.9 v0.0.5.6 v0.0.6.1, auf .
Allerdings immer die Map Hof Bergmann 1.0.0.4 und Farming Simulator 19 (Steam)
  Version: 1.4.1.0 b5334

**Comment by wallsingham** [comment]
Ich kann bestätigen dass der Fehler bei mir mit der Version 0.0.6.2 beseitigt ist!
In diesem Sinne; Applaus, Danke und einen schönen Sonntag.

Anbei 3 Screenshots von gerade eben. 

1x mit aive V. 0.0.6.2 > Der Drescher passiert problemlos die "Problemzone". 
![aive0 0 6 2_fsScreen_2019_10_19_23_57_57](https://user-images.githubusercontent.com/56741972/67151923-c9d66800-f2cd-11e9-89de-b35996d1a2f1.png)

2x mit aive V. 0.0.5.6 > Der Fehler tritt reproduzierbar an der Nord-West Ecke vom Feld 1 der Hof Bergamann 1.0.0.4
![aive0 0 5 6_fsScreen_2019_10_19_23_28_21](https://user-images.githubusercontent.com/56741972/67151921-c9d66800-f2cd-11e9-83ba-18e8e4988d2d.png)
![aive0 0 5 6_fsScreen_2019_10_19_23_50_36](https://user-images.githubusercontent.com/56741972/67151922-c9d66800-f2cd-11e9-8272-bfcfbce490d3.png)

**Comment by Mogli12** [comment]
Danke fürs Testen.
