### ISSUE TITLE
Einstellungen Helferlohn

### ISSUE THREAD

**Issue by Yoshi-01** [Mogli12/AIVehicleExtension#196]
Hallo, ich hab generell den Helferlohn auf 0 eingestellt.
Mit diesem Mod wird diese Einstellung aber ignoriert und Geld für die Helfer abgezogen.
Kann/Muss ich das in diesem Mod irgendwo einstellen?

**Comment by Mogli12** [comment]
AIVE macht gar nichts mit dem Helferlohn.

**Comment by Yoshi-01** [comment]
Sorry hast recht. Die Änderung dürfte mit dem 1.5.1 Patch des Spieles gekommen sein.
Konnte es schon wieder beheben. 
Dennoch danke schön!!
