### ISSUE TITLE
Drescher auf/zuklappen

### ISSUE THREAD

**Issue by cythux** [Mogli12/AIVehicleExtension#20]
Drescher auf/zuklappen (Taste X) funktioniert nicht mehr nachdem AIVE Aktiviert war, leider habe ich keine log mehr! Jedoch als Info kann ich sagen das nur Standartfahrzeuge verwendet wurden

**Comment by Mogli12** [comment]
Wenn der Korntank nicht leer ist, dann kann man den Drescher nicht zuklappen.

**Comment by cythux** [comment]
Der war leer ansonsten hätte ich kein Issue geöffnet,
