### ISSUE TITLE
AIVehicleExtention blocks woolpallets

### ISSUE THREAD

**Issue by MrMazzony** [Mogli12/AIVehicleExtension#200]
As said. AIVE has some big detectionbox infront of vehicles that bloks wool pallets from spawning (no more room to spawn pallet).
After moving vehicle or deactivating mod will resolve this.

Tested on basegame patch 1.5.1 with v0.0.6.2 . basegame sheep pasture.

**Comment by Dzi4d3k** [comment]
AFAIK that is used for collision detection. Also now when you know the limitation of mod, simply don't park in front of spawning area. At the end of the day this is just a game and we have to deal with some simplifications.

**Comment by Mogli12** [comment]
The same problem happens if one wants to place a new building. But triggers are tricky. So right now I just move them out of the way. 

Please test version 0.0.6.3

**Comment by MrMazzony** [comment]
Goy around testing now. Problem solved in 0.0.6.4 and woolpallets spawn even if vehicles are near.
