### ISSUE TITLE
Issues with withered patches with Seasons v1.1.0.0

### ISSUE THREAD

**Issue by bigtommert** [Mogli12/AIVehicleExtension#203]
When harvesting using AIVE 0.0.6.5 and Seasons v1.1.0.0, when the harvester hits a withered patch, it now treats it like its harvestable and will follow the path around the patch. This means it no longer mainly follows the crop line. This only happens since the new version of Seasons was released

**Comment by Mogli12** [comment]
You cannot harvest withered grain. That's why AIVE ignores that area.

**Comment by bigtommert** [comment]
I know that! But before the Seasons update, the harvester would ignore the withered crop and carry on on the same path in a line to where it's not withered. I'll try get a picture. What I'm saying now is that the vehicle will move around the outside of the withered area.

Lets say you are driving down the field and you hit a withered patch. This patch is half in the area being harvested, and half in the row beside (for convenience, I manually cut the row beside to have a straight line). Now when the harvester gets to the withered patch (lets say the left side of the harvester is the one following the line), the harvester will turn to attempt to cut the withered patch in the already harvested line. It used to just carry on straight and ignore the withered part for controlling the steering. Does that make sense? It doesn't ignore the area any more since Seasons updated their mod.

**Comment by Mogli12** [comment]
Sorry, but detecting fruit areas is standard functionality. Maybe seasons adjusted it somehow. And maybe this creates a new mod conflict between seasons and AIVE. But as AIVE uses the standard functions to count the number of fruit areas in a region there is nothing I can do.

**Comment by bigtommert** [comment]
Ah OK. That's disappointing as the helper will no longer follow the harvestable path, and the swaths will follow the crop - withered or not. Which makes it look very messy. It's totally down to the change Seasons made as I upgraded that yesterday and then seen this issue and was wondering why the helper wasn't working as he was on Tuesday. It looks like he falls asleep driving!

Anyway, I've let you know and you are aware. Perhaps you might have a solution in the future. Not to worry.

Happy Christmas, and thanks for a great mod.
