### ISSUE TITLE
Fehler im MP

### ISSUE THREAD

**Issue by Bandesss** [Mogli12/AIVehicleExtension#208]
Hallo was ganz neues, schade das dieser Mod nicht mehr geht.
Log im Anhang
[game.log](https://github.com/Mogli12/AIVehicleExtension/files/4260464/game.log)

**Comment by Mogli12** [comment]
Hallo,
ich denke, dass es hier einen Mod-Konflikt gibt. Du hast einen anderen Mod mit fehlerhaftem MP Code.
Viele Grüße
