### ISSUE TITLE
breite Schneidwerke werden nicht erkannt

### ISSUE THREAD

**Issue by V8Bolle** [Mogli12/AIVehicleExtension#21]
AIVehicleExtension (alle Versionen) funktioniert bei mir nur mit Schneidwerken bis 10,60m.
Bei breiteren SW dreht der Helfer nach links ab und bleibt außerhalb des Feldes stehen.
V 0.2.0.2:
Anklicken der Schaltfläche "normaler Helfer" ändert nicht die Schaltfläche zu "Auto".
Dies geschieht erst, nachdem der Helfer aktiviert wird.
Schneidwerksbreiten werden unten nicht mehr angezeigt.
Keine Änderung mit V 0.2.0.3.

**Comment by genen** [comment]
Seen same problem of turning left outside field with large headers.

**Comment by V8Bolle** [comment]
Neues Fahrverhalten mit V 0.2.0.4:
https://abload.de/img/awipky8.jpg
Starkes Ruckeln mit SW 10,60m im spitzen Winkel:
https://abload.de/img/aw20iltx.jpg

**Comment by E36Styler** [comment]
Das Problem liegt nicht an der Breite der Schneidwerke sondern an den Ketten (Terra Trac). Hab das ganze mal ausprobiert mit zwei Claas Lexion 780 mit 12m Schneidwerk, einer mit Rädern vorn und einer mit Ketten.. Der mit Rädern funktioniert einwandfrei aber der mit Ketten macht nur Probleme. Es liegt also an den Ketten! 
MfG

**Comment by V8Bolle** [comment]
Mit der V0.2.1.1 ist nun alles bestens!
Auch die Drescher mit Crawler und breitem Schneidwerk arbeiten.
Danke dafür, Mogli12!
