### ISSUE TITLE
Auto Drive Intergration

### ISSUE THREAD

**Issue by andrenrei** [Mogli12/AIVehicleExtension#215]
Hallo gibt es die möglich keit das man  Mogli12 /
AIVehicleExtension mit in Auto drive integrirt das die zwei komuniziren können und man vlt sogar sähmachinen usw. nachfüllen lassen kann von Autodrive.

**Comment by Mogli12** [comment]
AIVE is nur eine Erweiterung des normalen Helfers. Wenn AutoDrive den Helfer unterbrechen will, dann sollte das über [AIVehicle](https://gdn.giants-software.com/documentation_scripting_fs19.php?version=script&category=70&class=10462) geschehen.
