### ISSUE TITLE
Problem Grund Unbekannt, beim Start

### ISSUE THREAD

**Issue by Babene03** [Mogli12/AIVehicleExtension#217]
Hi Mogli,

wir haben versucht den **LS19 AIVehicleExtension Version 0.0.7.0** auf der Map "NF Marsch 4fach V1.7" im Multiplayer zu nutzen, doch beim Starten bricht der direkt wieder ab (Ingame) "Grund Unbekannt". 

Auszug aus der Client  Log:

> 2020-04-20 00:06 Warning (script): 'setTranslation': Argument 1 has wrong type. Expected: Int. Actual: Nil
> 2020-04-20 00:06   ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (882): expectedType == Value::VoidType || expectedType == Value::ClassType
> 2020-04-20 00:06 LUA call stack:
> 2020-04-20 00:06   dataS/scripts/vehicles/specializations/AIVehicle.lua (702) : setTranslation
> 2020-04-20 00:06   dataS/scripts/utils/Utils.lua (381) : oldFunc
> 2020-04-20 00:06   dataS/scripts/vehicles/specializations/AIVehicle.lua (1072) : stopAIVehicle
> 2020-04-20 00:06   dataS/scripts/input/InputEvent.lua (100) : callback
> 2020-04-20 00:06   dataS/scripts/input/InputBinding.lua (3202) : notifyInput
> 2020-04-20 00:06   dataS/scripts/input/InputBinding.lua (2924) : updateInput
> 2020-04-20 00:06   dataS/scripts/main.lua (1868) : update

Gerne helfen wir mit weiteren Informationen

Client-Log:
[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/4500416/log.txt)

Server-Log:
[Server.log](https://github.com/Mogli12/AIVehicleExtension/files/4500418/Server.log)

**Comment by Bandesss** [comment]
Hallo Mogli, selbern fehler haben wir auch mit der 0.7 die anderen gehen .....
Danke für den Mod

**Comment by Mogli12** [comment]
Der Fehler tritt im Vanilla-Code in [AIVehicle.lua](https://gdn.giants-software.com/documentation_scripting_fs19.php?version=script&category=70&class=10462) auf. Die Zeilennummern passen aber nicht. 

setTranslation wird nur bei `spec.aiTrafficCollision` verwendet. Ich denke mal, dass das Fahrzeug nicht korrekt auf Helfer vorbereitet ist.

**Comment by Bandesss** [comment]
Okey vielen dank, was kann man da tun ?

**Comment by Axelboss2010** [comment]
Hallo Stefan,

wir haben dieses Problem auch auf dem Server, benutzen aber keine Modtraktoren. 
Ich habe versucht zu Kalken mit dem Standardstreuer ---> Grund Unbekannt
Zettern und Schwaden geht auch nicht (alles Giants Maschinen)

Soll ich dir irgendwas zukommen lassen?

Liebe Grüße

**Comment by Mogli12** [comment]
Der Fehler tritt in AIVehicle auf, nicht in AIVehicleExtension. Was soll ich da machen?

**Comment by Bandesss** [comment]
Also ein Giants Problem ok

**Comment by Babene03** [comment]
Hi Mogli,

bin da gerade nicht so in der Materie, AIVehicle ist also von Giants und an der hapert es?
Kann es sein das es ein Multiplayer Problem ist?

@Bandesss ist es bei dir auch auf dem Server gewesen oder im Singleplayer?

Denn aktuell sind es ja 2 bestätigte fälle beim Multiplayer.

Denn wenn ich das so sehe müsste das Problem ja viel weiter verbreitet sein, da es dies ja anscheinend nicht ist, stellt sich mir halt die frage ob im Multiplayer Code von Giants etwas schief läuft, oder ob es sogar ein Problem mit einer anderen Mod besteht.

**Comment by Axelboss2010** [comment]
Sorry wenn ich nochmals dazwischen Krätsche,

wenn wir den Giants Helfer springen lassen funktioniert das auch. Nur wenn wir auf AI umstellen kommt die Meldung ---> Grund unbekannt. 
Und das ist mir beim Kalkstreuen, zettern, schwaden aufgefallen. (alles was der Giants Helfer ja kann und macht) (aber halt nur hoch und runter - was ne katastrophe ist)

Also bitte nicht falsch verstehen Stefan, wir lieben deinen Mod und der ist auch nicht wegdenkbar von unserem Server)

Was mir noch aufgefallen ist, dass AI mit mähen im Kreis probleme hat. (Ich erinnere mich vom LS17, dass man einmal außenherum fahren soll und dann kann man AI springen lassen) Leider macht er
das nur sporadisch. Vielleicht ist dir das bekannt. Oder ist das ein Map Problem?

Liebe Grüße

**Comment by Mogli12** [comment]
Laut log.txt ist der Fehler in AIVehicle.lua in Zeile 702. Diese Datei ist von Giants und man kann sie sich hier anschauen: https://gdn.giants-software.com/documentation_scripting_fs19.php?version=script&category=70&class=10462.

Die Zeile 702 ist laut Script-Doku also irgendwo zwischen dem Ende von getDirectionSnapAngle und dem Anfang von getAINeedsTrafficCollisionBox. Da ist aber normalerweise nichts, vor allem kein Aufruf von setTranslation.

Dafür gibt es nur eine Erklärung: die veröffentliche Version entspricht nicht der Version im aktuellen Patch. Und genau hier endet meine Lust, sich mit dem Problem auseinander zu setzen. 

Also selbst, wenn der Fehler durch AIVE verursacht wird, kann ich ihn nicht korrigieren, weil Giants nicht die aktuelle Version der Datei AIVehicle.lua veröffentlich.

**Comment by Babene03** [comment]
Danke für die Antwort, das ist schade, weil es ja dann heißt, das im aktuellen zustand AIVehicleExtension komplett Nutzlos außer beim Dreschen ist.

**Comment by Bandesss** [comment]
Wie gesagt mit der alten Version des Mods.
Gab es die Probleme nicht nur woher bekommt man ihn ?

**Comment by Mogli12** [comment]
Nimm doch den Standard-Helfer oder Courseplay.

**Comment by Bandesss** [comment]
Courseplay im Multipalyer ein no Go
Woher bekommt man die alten mods von dir ?

**Comment by Bandesss** [comment]
> Hi Mogli,
> 
> bin da gerade nicht so in der Materie, AIVehicle ist also von Giants und an der hapert es?
> Kann es sein das es ein Multiplayer Problem ist?
> 
> @Bandesss ist es bei dir auch auf dem Server gewesen oder im Singleplayer?
> 
> Denn aktuell sind es ja 2 bestätigte fälle beim Multiplayer.
> 
> Denn wenn ich das so sehe müsste das Problem ja viel weiter verbreitet sein, da es dies ja anscheinend nicht ist, stellt sich mir halt die frage ob im Multiplayer Code von Giants etwas schief läuft, oder ob es sogar ein Problem mit einer anderen Mod besteht.

Multipalyer
