### ISSUE TITLE
Default activation key should change

### ISSUE THREAD

**Issue by genen** [Mogli12/AIVehicleExtension#22]
5 is used by the game itself, and ctrl-5 has been used by drive control for 17 since Nov. 
Using right control as modifier would be much better.

**Comment by Mogli12** [comment]
Go and change the keyboard settings in the game options as you want.

**Comment by genen** [comment]
Obviously I changed them. The suggestion is not to default to key that has already been used for the last 3 months by a very popular mod. I'm not trolling, trying to be helpful

**Comment by Mogli12** [comment]
I use the same keys as in AutoTractor UpsideDown never cared if there was a key clash. I changed the keys in another mod once several years ago and I never got a thank you from UpsideDown. I won't do that again.

**Comment by Mogli12** [comment]
I changed the key settings now.

**Comment by genen** [comment]
Yes I saw that! Thanks! I had already remapped drivecontrol, but I think your new key combo is more logical! 
I download beta versions every week from here and the last one I got on Sunday seemed to break sunflower harvesting. I'll post a bug report after the next version I download if that is still a problem. Thanks.
