### ISSUE TITLE
main cultivation after stubble cultivation

### ISSUE THREAD

**Issue by paul-dotcom** [Mogli12/AIVehicleExtension#228]
Hi, I'm using the stubble cultivation mod to play as realistic as possible. My issue is, that the AI won't really work with this mod. It seems like the field is already cultivated for the AI, so it won't cultivate it again.
Is there a version in progress, where this issue is fixed?

thank you for answering and for this great mod

**Comment by Mogli12** [comment]
Hi,
I think that this is not possible. The field is already cultivated. I do not know if it would work with courseplay.
Best regards
