### ISSUE TITLE
[Feature request] Option to turn on/off Straw Swaths if fruit allows it

### ISSUE THREAD

**Issue by Dennizzzzz** [Mogli12/AIVehicleExtension#230]
It would be a nice feature to be able to set an options to turn on or off if you want the Straw Swaths option to be enabled or not. Now before I start AIVE I always need to check if the Combine has the right option for Straw Swaths.

And if you switch from to fields where one field with fruit that has no swaths, to a field with fruit that has swaths, you need to 're-enable' the swath option. So if AIVE will do this for me at start, i'll not forget it.

**Comment by Mogli12** [comment]
Hi,

This is standard functionality of the vanilla game. AIVE cannot change it. The straw swath key binding is disabled if the vehicle is operated by the hired worker.

BR
