### ISSUE TITLE
Install (Question)

### ISSUE THREAD

**Issue by 0tompa0** [Mogli12/AIVehicleExtension#239]
How do i install the mod? I downloaded the mod and drag the mod in to the mod folder but when i tried to start the game i can't select the mod. (can't see it). Can you help me?

**Comment by Mogli12** [comment]
How did you download the mod? Is there a number in brackets at the end?

**Comment by 0tompa0** [comment]
I used the link. It’s said the latest beta version

**Comment by Mogli12** [comment]
I am sorry, but I need more details if I should help you.

**Comment by 0tompa0** [comment]
First i downloaded the latest beta version and after that I took the ziped file and I drag it to my mod folder. I started the game and i couldn't see the mod in the mod and dlcs list.

**Comment by bgo1973** [comment]
You have to activate it in the mods list if you start an existing savegame.

**Comment by 0tompa0** [comment]
But i can't see it in the mod list.

**Comment by bgo1973** [comment]
You should post your log file.

**Comment by 0tompa0** [comment]
where do i found that?

**Comment by 0tompa0** [comment]
Can you tell how you install it? so i know if did right or not?

**Comment by 0tompa0** [comment]
I fixed it!

**Comment by 0tompa0** [comment]
its working now

**Comment by 0tompa0** [comment]
And I don't want to talk about what i did wrong. Thank you for the help!
