### ISSUE TITLE
Mit irgendwas nicht kompatibel?

### ISSUE THREAD

**Issue by SnyderAnrw** [Mogli12/AIVehicleExtension#241]
Hi

Irgendwie spinnt der mod rum bei mir. Manchmal kann ich nur 3 manchmal aber 6 oder mehr Helfer gleichzeitig fahren lassen. Ist da irgendwas bekannt? Dann startet ich Ls19 neu und kann dann plötzlich nur 2 gleichzeitig oder deutlich mehr gleichzeitig arbeiten lassen. Ist dann immer zu erkennen  dass im F1Fenster nicht mehr der "Helfer einstellen" Reiter da ist.

**Comment by Mogli12** [comment]
AIVE ändert nichts am Einstellen der Helfer. Das ist Standard-Coding.
