### ISSUE TITLE
REVERSE_DISTANCE_AFTER_STOPPED

### ISSUE THREAD

**Issue by Williwillswisse** [Mogli12/AIVehicleExtension#242]
Hallo Stefan,
wäre es möglich den Wert für REVERSE_DISTANCE_AFTER_STOPPED als Parameter in den Einstellungen hinzuzufügen ?
Wir vom Autodrive Team hatten ja schon mal den Wert bei Dir hier auf 0.25 ändern lassen (der baloo) , aber mit der 0.0.7.2 ist er jetzt wieder auf 1 m. Das macht bei den AD Abfahren beim Häckseln Probleme.
Als Parameter könnte dann jeder einstellen was er benötigt.

Gruß Willi

**Comment by Mogli12** [comment]
Hallo Willi,

auf 0.25 läßt AIVE leider Getreide stehen. Das geht auch nicht.

Viele Grüße, Stefan

**Comment by Williwillswisse** [comment]
Deswegen dachte ich ja den Wert als Parameter einstellbar zu machen.
Die Voreinstellung kann ja 1 m sein, aber man könnte sie dann bei Bedarf anpassen.

**Comment by Mogli12** [comment]
Das kapiert doch niemand. Und es ist auch keinem geholfen, wenn man man AutoDrive nicht weit genug zurück fährt. Dann bleibt was stehen und in de nächsten Runde kommt AIVE dann dadurch aus dem Konzept.

**Comment by Mogli12** [comment]
Probier mal Version 0.7.0.3

**Comment by Williwillswisse** [comment]
Hallo Stefan,
vielen Dank. Funktioniert bei mir prima 🙂

Hast du zur #211 von mir noch eine Idee ? 🙈

Gruß Willi

**Comment by Williwillswisse** [comment]
Ich mache diesen Issue mal zu weil : Funktioniert 😉
