### ISSUE TITLE
changing max speed of AIVE when harvesting

### ISSUE THREAD

**Issue by kf6shc** [Mogli12/AIVehicleExtension#247]
Hello, currently the max speed of header is 80kmh and my combines is 85kmh. when manually harvesting i can reach these speed, however, when using AIVE the max harvesting speed of my combine only reaches 15mph. can you tell me how to change the AIVE limitation to allow for increased speed?

thank you and thank you for this incredible mod!!

**Comment by Mogli12** [comment]
Hi,

AIVE reduces the speed automatically, because it cannot react fast enough on the calculated direction changes.

Best regards
