### ISSUE TITLE
Beim starten eines fünften Helfers kommt ein Error

### ISSUE THREAD

**Issue by Dbilas-MachVRTTuning** [Mogli12/AIVehicleExtension#249]
Hallo.

Ich nutze die AIV und mir ist aufgefallen das ich beim starten eines fünften Dreschers einen Error bekommen. Es ist egal ob ich mit dem AIV Helfer starte oder mit dem normalen LS. Die Version ist von hier, die letzte aktuelle Version LS19.

`2021-09-06 21:49 Error: Running LUA method 'update'.
2021-09-06 21:49 dataS/scripts/vehicles/specializations/AIVehicle.lua(596) : attempt to index field 'currentHelper' (a nil value)`

**Comment by Dbilas-MachVRTTuning** [comment]
Wenn der Mod deaktiviert ist und nur im Mod Ordner liegt kommt die Fehlermeldung beim 9 Helfer. Version ist die 0.0.7.5

**Comment by Dbilas-MachVRTTuning** [comment]
Trotzdem der Mod nicht mehr im Mod Ordner ist und auch beim laden der Map nicht mehr angezeigt wird kommt der Error.
`2021-09-10 10:16 Error: Running LUA method 'update'.
2021-09-10 10:16 dataS/scripts/vehicles/specializations/AIVehicle.lua(596) : attempt to index field 'currentHelper' (a nil value)`

**Comment by jason0611** [comment]
FS19_TowingChain im Modordner? Falls ja, versuche es mal probeweise ohne.
Ansonsten ist die Logdatei hilfreich. ;-)

Da der Fehler auch ohne AIVE auftritt, dürfte die Ursache in einem Modkonflikt liegen.

**Comment by Dbilas-MachVRTTuning** [comment]
Den Mod habe ich nicht. Ich habe jetzt mal einen anderen Spielstand geladen, Map und auch andere Mods, und da ja AIV nicht mehr im Ordner ist meckert er am Anfang das es nicht da ist. Nach dem Laden der Map und versuch den neunten Helfer zu starten passiert nichts, kein Error und aber auch kein Helfer startet. Es gehen nur 8 Helfer maximal. Ich versuche jetzt mal noch einen Spielstand in dem ich AIV nicht genutzt hatte.

**Comment by Dbilas-MachVRTTuning** [comment]
Also in einem Spielstand indem ich AIV noch nicht genutzt habe kann ich ohne Probleme mehr als 9 Helfer aktivieren.

**Comment by Mogli12** [comment]
Hallo,
leider muss ich das Problem hier zumachen. Das hat nichts mit AIVE zu tun. Die Stelle ist das Coding vom normalen Helfer:
https://gdn.giants-software.com/documentation_scripting_fs19.php?version=script&category=32&class=319
LG
