### ISSUE TITLE
Fehler

### ISSUE THREAD

**Issue by Paul2510** [Mogli12/AIVehicleExtension#252]
Guten Morgen

Erstmal danke das du deinen tollen Scripts na LS 22 bringst! 
Hab eine problem in der log!

LG
[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/7732485/log.txt)

**Comment by Mogli12** [comment]
Das sollte in der aktuellen Version nicht mehr auftreten. Allerdings hast Du auch einen Fehler in FS22_additionalFieldInfo. Der könnte der Auslöser gewesen sein.

**Comment by Paul2510** [comment]
Hallo
Ja hab ich auch schon gesehen! Vielen Dank"
