### ISSUE TITLE
FS22 Dedicated Error - german thread

### ISSUE THREAD

**Issue by alexanderweide** [Mogli12/AIVehicleExtension#255]
Hi Mogli,

ich habe die neue Beta 0.004 auf dem dedi getestet. Musste leider feststellen das die Mod wirklich gut im single player läuft aber in keinster Weise auf dem Dedi.

Was ist mir aufgefallen:

- Wenn VCA RC6 installiert ist und die Funktion aktiviert ist das die Helfer die Getriebe einstellungen auch nutzen in VCA, verliert der Helfer beim Stoppen des Helfers, oder beim Verlassen des AI helper menüs alle settings. 
Es werden keine Settings gespeichert beim verlassen des Servers, oder beim Stoppen des Helfers wenn die Getriebe VCA übernahme an ist.

- das einschalten im Menü des AI helpers ist buggy mal geht es mal nicht.
- AI Info Hud wird nicht angezeigt.
- Offset Werte werden nicht übernommen.
- Kreisfahrt mit Flug oder Mähdrescher funktioniert nicht.

-> ich kann nichtmal sagen ob es überhaupt funktioniert. Da das Verhalten stark unterscheided zum Singleplayer nehme ich an das die AIvehicle Extension auf dem Dedi einfach nicht läuft, weil die Settings irgendwie nicht gespeichert werden oder es keine synchronisation mit dem Server gibt. 

Dennoch echt geil wie es im singleplayer läuft. 

Alex

**Comment by alexanderweide** [comment]
Update: 
feste anbaugeräte also keinen grubber sondern einen festen 3.2 meter pflug funktioniert auch nicht.
Auch habe ich herausgefunden das On screen menü zu öffnen mit ALT + H wenn man dort alles einstellt scheint es zu die settings zumindest im strg H menü zu halten Leider wird der Helfer nicht grün und fährt immer nur gerade hoch und runter wie der standard helfer.

Auch könnte es sein das mein Custom Feld einfach probleme gemacht hat oder das Grubber probleme haben gepflügte stellen zu erkennen. 

ich werde weiter testen

**Comment by Mogli12** [comment]
Wie habt ihr den Dialog für die Einstellungen geschlossen? ESC oder ENTER?

**Comment by alexanderweide** [comment]
> Wie habt ihr den Dialog für die Einstellungen geschlossen? ESC oder ENTER?

ich habe esc genutzt bzw eigentlich alle verschiedenen varianten, da ich es mehrfach probiert habe, kann leider nicht genau sagen wie oft oder wann. kann aber sagen das VCA mit sicherheit irgendwie die Mod beeinflusst. Zumindest erscheint es so. Wenn man das VCA getriebe auf die Helfer überträgt lässt sich die Settings nur noch via alt + H und die on screen einstellungen speicher.

desweiteren ist mir ein neuer bug aufgefallen:

Wenn man die Auto Lenkung aktiviert bei fahrendem Helfer also wenn der Helfer schon aktiv ist, hängt das spiel sich im Dedi komplett auf bzw friert ein für alle beteilligten auf dem Server. Sobald man die Lenkung wieder frei gibt ruckelt es gewalltig die fahrzeuge fliegen umher und es läuft wieder normal.

,mfg

**Comment by Mogli12** [comment]
Auto Lenkung funktioniert in diesem frühen Stadium wohl noch nicht.

**Comment by alexanderweide** [comment]
@Mogli12 alles klar.

Ich habe jetzt version 0.005 getestet und die Bugs bestehen weiterhin, auch kann ich jetzt mit sicherheit sagen das ich immer mit OK bestätigt habe. Vorallem der Lenkwinkel setzt sich immer auf 0 grad zurück und auch wenn der AI helfer mal grün geworden ist und das Feld erkannt hat fährt er nur gerade aus, selbst wenn man den Helfer am Rand des Feldes gestartet hat.

für Grubbern Pflügen eventuell noch unbrauchbar, muss man über längere sicht sehen oder wie es anderen testern ergeht.

**Comment by EGUltraTM** [comment]
Sadly the problem with the not working new AI is still there in 0.0.0.6
it gets deactivated back to normal when trying to start.

**Comment by alexanderweide** [comment]
> Sadly the problem with the not working new AI is still there in 0.0.0.6 it gets deactivated back to normal when trying to start.

had this issue in 0.005 and 0.004 too. It gets deactivated when the steering angle is not set multiple times... in my experience but i am not sure if thats the true cause for that.

**Comment by Mogli12** [comment]
@EGUltraTM Can you give some more details? Sreen shots? What did you do? Did you choose the correct side? Screen shots?

**Comment by EGUltraTM** [comment]
> @EGUltraTM Can you give some more details? Sreen shots? What did you do? Did you choose the correct side? Screen shots?

Also ich mache alles wie im Tutorial von Mario Hirschfeld. habe die gleiche Map im SP und MP getestet im SP geht es wunderbar. 
Versuche ich das gleiche Feld mit gleichen Einstellungen als Test zu Dreschen geht es aber im MP nicht und der Helfer ist im strg h menü immer wieder auf AUS gestellt.

**Comment by Mogli12** [comment]
Hast Du mal Version 0.0.0.8 oder höher probiert?

**Comment by EGUltraTM** [comment]
Hallo,

0.0.0.8 hatten wir getestet und es ging auch im MP nicht. Die neue Version können wir später Abends gerne testen.

**Comment by Mogli12** [comment]
Ging auch im MP nicht - was bedeutet das? Gibt es Fehler?

**Comment by alexanderweide** [comment]
Hi, also ich kann nur bestätigen das der Mod im Multiplayer nicht funktioniert. Mittlerweile kann ich zumindest aus meiner Erfahrung sagen, das Weder Grubbern, Sähen, Ernten oder Pflügen geht, das spiel jumped immer auf den standard helfer. Auch funktioniert die Feldrand oder sonstige erkennungs algorythmen nicht, erkennbar das AI helper nicht grün leuchtet -> immer gelb oder rot.

**Comment by Mogli12** [comment]
Leute, das ist keine brauchbare Feherbeschreibung. Wie sieht es mit Screenshots oder Videos aus? Wurde überhaupt die richtige Seite ausgewählt?
Wenn ihr keine Details nennen könnt oder wollt, dann macht dieses Issue einfach zu.

**Comment by EGUltraTM** [comment]
Hallo,

ich werde mich heute Abend mal hinsetzen und das ganze nochmal testen und auch die client/server logs ansehen und berichten. Bisher muss ich zugeben ist es mir auch immer nur passiert das der AIVE helfer sich immer wieder auf Aus stellt wenn man ihn einschaltet. Später mehr dazu.

**Comment by EGUltraTM** [comment]
So ich habe mich nochmal versucht. 

Der alternative Helfer bleibt auf AN auf dem Dedi. Alles ist eingestellt wie im SP auch das gleiche Savegame genutzt. 

Der alternative Helfer wird nicht grün (also die Schrift) obwohl er aktiv ist. 
Leider keine Errors in den Clients oder Server Logs.

Ich wüsste nicht wie ich das noch beschreiben sollte oder ein Video machen sollte. man schaltet ihn auf alt+h im Menü auf an und drückt dann H für den Helfer und es wird nicht grün und der normale Helfer legt los.

**Comment by alexanderweide** [comment]
Verzeihung, ich weiß auch nicht wie ich das besser beschreiben soll. Aber ich muss mich meinem Vorredner anschließen. Es gibt keine error logs, nichts, er geht einfach nicht an. Er wird weder Grün noch folgt er der Außenkante des Feldes. Wenn ich auf Lenkrad AI gehe, also das Lenkrad anklicke, passiert da auch nichts. Es werden weder Settings gelesen noch geschrieben auf dem Dedi server. Einfach ausgedrückt, der Helfer geht nicht auf dem Dedi server. Warum kann ich nicht sagen.

**Comment by timmi4026** [comment]
Nabend, bei mir klappt die Kreisfahrt nicht im Multiplayer. Folgendes passiert. Ich setze ihn links unten am Feld an, er fährt auch die Bahn hoch und am Rand setzt er rückwärts zurück in einer rechtskurve in die Frucht und fährt dann die nächste Bahn wieder runter, verhalten wie der Standard Helfer. Einstellungen, Kreisfahrt  und rückwärts nur gerade.  Aber er ignoriert komplett die Krerisfahrt. Drescher Claas Torion 750. Settings sind auch jedesmal zurück gesetzt. Lenkwinkel auf 0 und Felderkennung auf minimal. Fehler in der log gibt es keine. 
LG TImmi

**Comment by Mogli12** [comment]
@timmi4026 Welche Version?

**Comment by timmi4026** [comment]
die aktuelle, 0.1.0

**Comment by BeckerCodeing** [comment]
Hallo Mogli, ich habe jetzt versucht das Selbst auf meinem server nachzuvollziehen. Grundsätzlich mach der Alternative Helfer schon was und auch besser als der Standard helfer. Allerdings passt das was man einstellt nicht zu dem was er macht, soll Heißen:

- einstellungen die im Menu übernommen werden übernimmt er garnicht -> z.B: overlay von der AI anzeige (schrift gelb grün.)
- einstellungen in dem alt+h menu werden zum teil übernommen aber vollkommen nicht nachvollziehbar.

Ich habe wirklich versucht ein muster zu finden um dir etwas brauchbares berichten zu können, allerdings habe ich es nicht geschafft. 

Alternativ kann ich dir aber anbieten ein neues Savegame für die auf einem Server laufen zu lassen damit du es selbst testen kannst? Wenn ich dich damit unterstützen kann, kann ich dir das gerne einrichten.

**Comment by Mogli12** [comment]
Probiert bitte einmal Version 12 und schickt mit die Logs von Server und Client per Gist oder Pastebin.

Ein Screenshot wäre auch hilfreich.

**Comment by timmi4026** [comment]
Mogli ich glaube Du bist auf dem richtigen Weg, habe die Version 12 gerade auf dem Server getestet, er fährt das erste mal tatsächlich so wie es eingestellt ist. Habe mal die Server und Client log hochgeladen und hier ist noch ein link zu meiner Cloud zu einem Video wie er die erste Runde auf dem Feld fährt. Er scannt noch ein wenig holpfig den Rand aber macht seine Arbeit. Super !
LG Timmi
Das Video: https://1drv.ms/u/s!AiReB39Hw6NKiYY0eDgSWZMugnHwcw?e=3GV3dz
[clientlog.txt](https://github.com/Mogli12/AIVehicleExtension/files/7865967/clientlog.txt)
[serverlog.txt](https://github.com/Mogli12/AIVehicleExtension/files/7865969/serverlog.txt)

**Comment by Mogli12** [comment]
Hmm, ich kann nicht wirklich beurteilen, was AutoDrive selber bei Abtanken macht. Klappt es denn, wenn der Drescher beim Abtanken nicht anhält?

**Comment by timmi4026** [comment]
nein, er bleibt da stehen und wartet dann wieder auf ruf vom drescher. das wiederholt sich dann immer wieder. müsste mal testen wenn man dem Drescher sagt das ad wärend der fahrt abtankt. Zu diesem Zeitpunkt kann man glaub ich nicht erkennen von wo das Problem kommt.

**Comment by Mogli12** [comment]
Leider nutze ich kein AutoDrive. Ich kann da nur wenig weiterhelfen.

**Comment by alexanderweide** [comment]
> nein, er bleibt da stehen und wartet dann wieder auf ruf vom drescher. das wiederholt sich dann immer wieder. müsste mal testen wenn man dem Drescher sagt das ad wärend der fahrt abtankt. Zu diesem Zeitpunkt kann man glaub ich nicht erkennen von wo das Problem kommt.

Hast du die aktuelle version von github von Autodrive? 2.0.3? Denn das klingt wie ein Problem von eines der ersten Versionen von Autodrive. Auch hat Autodrive generell probleme beim Abtanken, man muss für jedes Fahrzeug den richtigen Rohr Abstand einstellen, in der Regel 1.25m bis 3.5m abhängig vom gewählten Hänger. Leider kann ich das gerade noch nicht testen da noch nichts fertig gewachsen ist auf dem server. Dauert noch 2 Monate.

**Comment by ole1510** [comment]
Gerade nochmal mit der Aktuellen version getestet, Server übernimmt die Einstellung nicht und schickt den normalen Helfer.
Im Test mit einem grubber
Gestern Abend getestet, wenn man selbst den server hostet funktioniert es, aber mit dedicated server gerade nicht.
Falls irgendwelche infos weiterhelfen gerne bescheid sagen

[SERVERlog.txt](https://github.com/Mogli12/AIVehicleExtension/files/7871114/SERVERlog.txt)
[Clientlog.txt](https://github.com/Mogli12/AIVehicleExtension/files/7871115/Clientlog.txt)
![image](https://user-images.githubusercontent.com/19856157/149534965-f481234e-6e4a-4b23-a8ec-6dfa8dbe012e.png)

**Comment by Mogli12** [comment]
Den Fehler hatte ich auch schon in VCA. Die LUA-Laufzeit sortiert auf dem Dedi die Tabellen um. Warum in FS22 die Tabellen überhaupt umsortiert werden, das kann ich nicht sagen.

**Comment by Mogli12** [comment]
Probiert mal Version 13. Mein Dedi-Server läuft auch wieder und da sah es gut aus.

**Comment by ole1510** [comment]
jo, nun nimmt er meine ich alle einstellungen an. hat gut geklappt. Danke

**Comment by alexanderweide** [comment]
Das ist super werde ich demnächst mal probieren... Ab montag.. Vielen Dank für die bisherige Arbeit.

**Comment by alexanderweide** [comment]
Soweit ich das sagen kann. Grubbern und Mähen läuft soweit absolut reibungslos. Fantastisch Arbeit ! Bin gespannt ob es Bugs gibt.

**Comment by Mogli12** [comment]
Danke fürs Testen und fürs Feedback. Ich mache dieses schon recht lange Issue mal zu.
