### ISSUE TITLE
Error Running LUA methode "update"

### ISSUE THREAD

**Issue by headhunter84** [Mogli12/AIVehicleExtension#256]
Hi mogli.

AIVE Beta 0.0.0.4 wirft nach einige Zeit beim Ernten mit einem Drescher ständig LUA Errors in die Log. Die LUA Error begannen beim Überladen während der Drescher erntet.

Error: Running LUA method 'update'.
C:/Users/****/Documents/My Games/FarmingSimulator2022/mods/FS22_AIVehicleExtension/AITurnStrategyMogliDefault.lua:170: attempt to call method 'stopAIVehicle' (a nil value)
Error: Running LUA method 'update'.
C:/Users/*****/Documents/My Games/FarmingSimulator2022/mods/FS22_AIVehicleExtension/AITurnStrategyMogliDefault.lua:166: attempt to call method 'stopAIVehicle' (a nil value)
[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/7738956/log.txt)

**Comment by headhunter84** [comment]
Noch ein weiterer LUA Error ist vereinzelt aufgetreten.

Error: Running LUA method 'update'.
C:/Users/*****/Documents/My Games/FarmingSimulator2022/mods/FS22_AIVehicleExtension/AIDriveStrategyCollisionOtherAI.lua:141: attempt to index field 'REASON_TEXT_MAPPING' (a nil value)

**Comment by Mogli12** [comment]
Hi,
This should be fixed in the latest version.
Best regards
