### ISSUE TITLE
Combine Hired Worker, V. 0.2.0.4

### ISSUE THREAD

**Issue by BrandonD01** [Mogli12/AIVehicleExtension#26]
Version 2.0.4
  Combine, when AIVehicleExtension is activated the combine will turn to slight right then left to edge of crop, stop then reverse outside of field until the combine either hits an object or I deactivate the AI.  Just to be sure there were no mod conflicts I removed all other mods except AIVehicleExtension, with same results.  Thank You for all your hard work!

  I really wish Giants would have left well enough alone as far as the hired workers go.  To me FS-15 AI's worked great, with or without AutoCombine.

**Comment by budgej** [comment]
Is this with the Nee Hillan CR 10.90?

**Comment by BrandonD01** [comment]
Yes with the CR 10.90 and the 35 or 40 foot header

**Comment by Beevster** [comment]
Hi, I have exact same problem, Map is Coldbourgh combine is 41 feet New Holland with 10.90 New Holland.

**Comment by Sythos** [comment]
i've found a workaround, i set "reverse" button in AIExtension and combine start work fine, happen just with 40ft or more headers

**Comment by Mogli12** [comment]
Hi,

It sounds like one of the direction nodes is pointing into the wrong direction Thanks for this valuable hint!

Regards, Stefan

**Comment by Mogli12** [comment]
It should be fixed now. I was able to harvest with the NH CR10.90.
