### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Roby1164** [Mogli12/AIVehicleExtension#27]
Hello Stefan, I'm trying AIVehicleExtension, but I continue to have problems, do not work, takes strange roads not following the camp, nol log there are no errors. It might be a conflict with some Mod? Type, GPS, CoursePlay, etc ..
This is a screen, where you see what happens, and it's just one example:
http://prntscr.com/dtp9of
Roby

**Comment by hoefti10** [comment]
Hello, i have the same Problems and issues. My fps Drops down 3 or 4 fps sometimes when i hired a helper. I watch it since the rollout from the second Version.

**Comment by Mogli12** [comment]
Hi,
Can you test another turn mode, not the one with the shape of a C?
Regards, Stefan
