### ISSUE TITLE
kleine "Unschönheiten" im Mod

### ISSUE THREAD

**Issue by 112TEC-Chris** [Mogli12/AIVehicleExtension#279]
Hallo Mogli, 
ich hab in Build 10 2 kleine Sachen festgestellt. Zum einen kommt immer eine Warning, dass die Autocombine.i3d ein altes shapeFormat enthält und die folgende Warnung:   Warning: Missing l10n 'input_AIVE_PAUSE' in mod 'FS22_AIVehicleExtension'

**Comment by BullFlag** [comment]
<text name="input_AIVE_PAUSE"              text="ALT AI: Pause ..."/>

**Comment by 112TEC-Chris** [comment]
Hallo Mogli

mit deinen Änderungen funzt es jetzt wunderbar.
