### ISSUE TITLE
Log Error im SP

### ISSUE THREAD

**Issue by Scaniaman580** [Mogli12/AIVehicleExtension#28]
Hi, i become some log Errors when i shut off the helper. It's on every machine, Combine, cultivator...

> Stop AI Vehicle: nil
------------------------------------------------------------------------
2: E:/Datenauslagerung/Dokumente/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (2463): newFunc
3: [string "dataS/scripts/utils/Utils.lua"] (1857): stopAIVehicle
4: E:/Datenauslagerung/Dokumente/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (650): onClick
5: E:/Datenauslagerung/Dokumente/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/mogliHud.lua (356): mouseEvent
6: E:/Datenauslagerung/Dokumente/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (336): mouseEvent
7: [string "dataS/scripts/vehicles/Vehicle.lua"] (2200): superFunc
8: E:/Datenauslagerung/Dokumente/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/mogliHud.lua (325): mouseEvent
9: [string "dataS/scripts/BaseMission.lua"] (1415): mouseEvent
10: [string "dataS/scripts/FSBaseMission.lua"] (2109): mouseEvent
11: [string "dataS/scripts/missions/mission00.lua"] (320): mouseEvent
12: [string "dataS/scripts/main.lua"] (1801): <???>
------------------------------------------------------------------------

I use the newest 2.0.0.5 version from aivehicleextension and the 1.3.1 patch of the game.

**Comment by Mogli12** [comment]
This is not an error message. Or did you find the key word "error" anywhere?

**Comment by Jaguar95** [comment]
Can it be deactivated? It fills up the log.

**Comment by Mogli12** [comment]
Yes, you can essily deactivate it: just remove FS17_AIVehicleExtension from the mods folder.

**Comment by Jaguar95** [comment]
That´s not the best solution. ;) Is it really necessary to log all the entries?
