### ISSUE TITLE
Lua error dedicated server

### ISSUE THREAD

**Issue by turbostar190** [Mogli12/AIVehicleExtension#30]
On a dedicated server in both server and clients logs appears a lot of error and in the meantime fps drops.
This is the log: [https://gist.github.com/turbostar190/a3e4fffa1c616063a8d504605560fc73](https://gist.github.com/turbostar190/a3e4fffa1c616063a8d504605560fc73)

*TurboStar*

**Comment by Mogli12** [comment]
Hi,

This beta version of my mod writes log entries. This is nothing you have to be worried about. 

Regards, Stefan

**Comment by turbostar190** [comment]
Oh thanks for the answer.
Good work!

*TurboStar*
