### ISSUE TITLE
problem grimme

### ISSUE THREAD

**Issue by spectrum69** [Mogli12/AIVehicleExtension#32]
Does not work with the 415 and 620 grimme and works poorly with a articulated tractor reach of articulated seeder

**Comment by SuperMaic** [comment]
Same here. I have seen your post today, posting the same issue in german above...

**Comment by Mogli12** [comment]
Yes, this mod cannot handle changes to the vehicle geometry. So articulated axis and rotation of attacher joints does not work.

**Comment by Mogli12** [comment]
There is a problem in the configuration of the Grimme Rooster. It should be fixed with 1.0 beta 1. But articulated tractors are currently not supported.
