### ISSUE TITLE
Lua Fehler

### ISSUE THREAD

**Issue by BlackWolve** [Mogli12/AIVehicleExtension#33]
Hi Stefan
bei mir läuft seit der letzten Version im SP
[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/722047/log.txt)
 ein Lua Fehler auf:
dataS2/character/pedestrians/woman01.i3d (9.10) ms
Stop AI Vehicle: 2
------------------------------------------------------------------------
2: C:/Users/BlackWolve/Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (2463): newFunc
3: [string "dataS/scripts/utils/Utils.lua"] (1857): stopAIVehicle
4: [string "dataS/scripts/vehicles/specializations/AIVehicle.lua"] (338): updateTick
5: [string "dataS/scripts/vehicles/Vehicle.lua"] (2689): updateTick
6: [string "dataS/scripts/network/Server.lua"] (68): update
7: [string "dataS/scripts/BaseMission.lua"] (1509): update
8: [string "dataS/scripts/FSBaseMission.lua"] (2159): update
9: [string "dataS/scripts/missions/mission00.lua"] (333): update
10: [string "dataS/scripts/main.lua"] (1862): <???>
------------------------------------------------------------------------
dataS2/character/pedestrians/man01.i3d (8.32) ms
Stop AI Vehicle: 2
------------------------------------------------------------------------
2: C:/Users/BlackWolve/Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (2463): newFunc
3: [string "dataS/scripts/utils/Utils.lua"] (1857): stopAIVehicle
4: [string "dataS/scripts/vehicles/specializations/AIVehicle.lua"] (338): updateTick
5: [string "dataS/scripts/vehicles/Vehicle.lua"] (2689): updateTick
6: [string "dataS/scripts/network/Server.lua"] (68): update
7: [string "dataS/scripts/BaseMission.lua"] (1509): update
8: [string "dataS/scripts/FSBaseMission.lua"] (2159): update
9: [string "dataS/scripts/missions/mission00.lua"] (333): update
10: [string "dataS/scripts/main.lua"] (1862): <???>
------------------------------------------------------------------------
dataS2/character/pedestrians/man02.i3d (8.67) ms
Stop AI Vehicle: 2
------------------------------------------------------------------------
2: C:/Users/BlackWolve/Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (2463): newFunc
3: [string "dataS/scripts/utils/Utils.lua"] (1857): stopAIVehicle
4: [string "dataS/scripts/vehicles/specializations/AIVehicle.lua"] (338): updateTick
5: [string "dataS/scripts/vehicles/Vehicle.lua"] (2689): updateTick
6: [string "dataS/scripts/network/Server.lua"] (68): update
7: [string "dataS/scripts/BaseMission.lua"] (1509): update
8: [string "dataS/scripts/FSBaseMission.lua"] (2159): update
9: [string "dataS/scripts/missions/mission00.lua"] (333): update
10: [string "dataS/scripts/main.lua"] (1862): <???>
------------------------------------------------------------------------
Stop AI Vehicle: 2
------------------------------------------------------------------------
2: C:/Users/BlackWolve/Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (2463): newFunc
3: [string "dataS/scripts/utils/Utils.lua"] (1857): stopAIVehicle
4: [string "dataS/scripts/vehicles/ai/AIDriveStrategyStraight.lua"] (319): getDriveData
5: [string "dataS/scripts/vehicles/specializations/AIVehicle.lua"] (330): updateTick
6: [string "dataS/scripts/vehicles/Vehicle.lua"] (2689): updateTick
7: [string "dataS/scripts/network/Server.lua"] (68): update
8: [string "dataS/scripts/BaseMission.lua"] (1509): update
9: [string "dataS/scripts/FSBaseMission.lua"] (2159): update
10: [string "dataS/scripts/missions/mission00.lua"] (333): update
11: [string "dataS/scripts/main.lua"] (1862): <???>
------------------------------------------------------------------------
Stop AI Vehicle: 2
------------------------------------------------------------------------
2: C:/Users/BlackWolve/Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (2463): newFunc
3: [string "dataS/scripts/utils/Utils.lua"] (1857): stopAIVehicle
4: [string "dataS/scripts/vehicles/ai/AIDriveStrategyStraight.lua"] (288): getDriveData
5: [string "dataS/scripts/vehicles/specializations/AIVehicle.lua"] (330): updateTick
6: [string "dataS/scripts/vehicles/Vehicle.lua"] (2689): updateTick
7: [string "dataS/scripts/network/Server.lua"] (68): update
8: [string "dataS/scripts/BaseMission.lua"] (1509): update
9: [string "dataS/scripts/FSBaseMission.lua"] (2159): update
10: [string "dataS/scripts/missions/mission00.lua"] (333): update
11: [string "dataS/scripts/main.lua"] (1862): <???>
------------------------------------------------------------------------
isSendEvent
isSendEvent
isSendEvent
isSendEvent
isSendEvent
isSendEvent
isSendEvent

Zudem ist es auch nicht möglich zwischen dem alternativen und normalem Helfer zu switchen, man kann den Helfer nur starten und hoffen, dass dieser im gewünschten Modus startet.
Gruß
BlackWolve

**Comment by Dzi4d3k** [comment]
I suggest you to read:
https://github.com/Mogli12/AIVehicleExtension/issues/28

**Comment by Mogli12** [comment]
Hallo,

Du schreibst: "bei mir läuft seit der letzten Version ... ein Lua **Fehler** auf:" Wo bitte steht denn in der log.txt das Schlüsselwort "**Error**"??? 

Gruß, Stefan
