### ISSUE TITLE
Combine does not lower header...

### ISSUE THREAD

**Issue by sootysax** [Mogli12/AIVehicleExtension#34]
I'm having a repeated problem with the Case Axial Flow harvester..  it will repeatetly forget to lower the header, and just drive over and destroy the crop after a turn..

**Comment by spectrum69** [comment]
ce sont les barres de coupe qui merde pas le mod ou le vehicule prends les madcon et sa iras tous seul

**Comment by sootysax** [comment]
?

**Comment by Mogli12** [comment]
I changed the checks when to lower the implement. It should be fixed with v1.0 beta 1. Please re-open if not.
