### ISSUE TITLE
AITractor läd im Spiel nicht

### ISSUE THREAD

**Issue by Stefan197** [Mogli12/AIVehicleExtension#36]
Ich hab das problem dass der Mod bei mir im Spiel nicht läd.
Log bringt mir diesen Fehler:
Load mod: FS17_AIVehicleExtension
Error: Unsupported mod description version in mod FS17_AIVehicleExtension

**Comment by Mogli12** [comment]
Wenn Du das komplette Repository lädst, dann ist in der ZIP-Datei die ZIP-Datei AI_VehicleExtesion.zip. Die muss in den Mods-Ordern.
Noch einfacher lädt man die ZIP-Datei direkt aus dem Abschnitt <>Code:
https://github.com/Mogli12/AIVehicleExtension/blob/master/FS17_AIVehicleExtension.zip?raw=true

**Comment by Dzi4d3k** [comment]
The same error will be displayed if you don't have latest patch 1.3.1 installed, as this mod require it.

**Comment by Stefan197** [comment]
Genau diese hab ich ja runtegeladen und auch im Mods Ordner

**Comment by Mogli12** [comment]
Dann hast Du ziemlich sicher nicht Patch 1.3.1 installiert.

**Comment by Stefan197** [comment]
Japp, das war das Problem.
