### ISSUE TITLE
Project stopped

### ISSUE THREAD

**Issue by Mogli12** [Mogli12/AIVehicleExtension#37]
Hello everybody,

Yesterday I installed FS17 patch 1.4. What I saw made me really sad. The AIVehicleUtil.getFruitArea does not work consistently anymore. I slept over it and decided to stop this project.

I even have an idea why Giants destroyed the AIVehicle specialization. It is because of the Kuhn DLC. It will be a lot of work to get a plough, a cultivator and a sowing machine working correct at the same tractor. And I do not want to do this anymore. I am tired.

Regards, Stefan

**Comment by Dzi4d3k** [comment]
That's a great shame :(

**Comment by cabmac** [comment]
good morning i think, this is a logic consequence, even  the original helper is not working correctly...  :(

**Comment by Meckel34** [comment]
Hello Mogli.
Turn around you directly to Giants - which actually help with such problems. Just write Stegei an PM ...

Translated by google

**Comment by cabmac** [comment]
hopefully we can reach something with this:

https://forum.giants-software.com/viewtopic.php?f=886&t=107994&p=834329#p834329

o like Meckel posting: contact tu Stegei, he will be helpfull in those projects like this i think...

**Comment by Clemens76** [comment]
Please don't stop that Project. It's one of the important mods.

**Comment by Mogli12** [comment]
Good new! Giants contacted me and helped me fix the problem. We are back!

**Comment by Dzi4d3k** [comment]
Indeed great news!

**Comment by Meckel34** [comment]
Great!

**Comment by BrandonD01** [comment]
Whew, had me scarred for a bit there.  Without this mod the game would not be the same.  The current Louisiana map I am working on has very few square fields, without this mod it would be a real pain.  Thank you Mogli12 for all your hard work!
