### ISSUE TITLE
Drescher/Traktoren fahren zu weit aus dem Feld

### ISSUE THREAD

**Issue by cabmac** [Mogli12/AIVehicleExtension#39]
Hi,
mMn schiessen die Fahrzeuge zu weit ueber die Kante des Feldes:

http://www.imagehub.de/display-i4501be0zhl.html

Erstens gibts bei manchen, engeren  Feldern Probleme und zweitens ist der Anschluss danach nicht sauber, jedenfalls bei diesem Gespann.

Beim Traktor z.B. beim Maehen ists aehnlich. Ausserdem passierts haeufig, dass wenn man irgendwo am Ende oder am Rand etwas stehen laesst,  der Traktor auf einmal "abbiegt" um einen Rest zu maehen...hoffe ich hab mich einigermassen ausgedrueckt...kann auch mal ein vid machen.

Gruesse, Claudio

edit: ich seh grad, dass das letzte auch bei Dreschern passiert. Er sollte ja eigentlich an der Kante weiterfahren, statt dessen, faehrt er geradeaus bzw. biegt ab und sucht das stehen gelassene:

http://www.imagehub.de/display-i4502buscka.html
http://www.imagehub.de/display-i4503b5akn1.html

**Comment by Mogli12** [comment]
Hallo Claudio,

nimm mal das L-Wendemanöver. Es sollte ab 6m oder 7,5m Breite einigermaßen funkltionieren. Damit verlässt der Drescher das Feld praktisch gar nicht.

Viele Grüße, Stefan

**Comment by cabmac** [comment]
Moin, hmm, jetzt mal einiges durchgespielt, aber immer das gleiche: sieht er 10 meter voraus einen Bestand (entweder wie hier in den screens oder ein Rest im Falle des Autotractors), haelt er sich nicht an die Schnittkante sondern faehrt in den Bestand. Ich haeng mal noch ein paar screens an, wo er anscheinend einfach geradeaus faehrt statt zu wenden, dann gibts fps-Einbrueche und bleibt stehen.

http://www.imagehub.de/display-i4504bkpsig.html
http://www.imagehub.de/display-i4505bp0n4b.html
http://www.imagehub.de/display-i4506boteai.html
http://www.imagehub.de/display-i4507b0wvn1.html
http://www.imagehub.de/display-i4508bbug3d.html

**Comment by AlexStephenLytton** [comment]
Hallöle zusammen :)

Habe mit den gleichen Symptomen zu kämpfen wie Claudio. Auf einigen Feldern (bei Mod Maps) habe ich zusätzlich das Problem, das - egal ob Drescher oder Traktor mit Anbau hinten - Das Wendemanöver 10 - 20 m vor Feldrand beginnt. Teilweise auch in die falsche Richtung (bei der Aussaat z.B. in den bereits bestellten Teil statt in den noch nicht bearbeiteten)

Grüße,

Alex

**Comment by Mogli12** [comment]
Hallo Alex,

Es steht doch in der Beschreibung extra drin: **"This project is still in a very early beta stage.".** Es wird noch Monate dauern, bis ich eventuell mal dazu komme, die Abstände beim Wendemanöver zu optimieren. 

Gruß, Stefan

**Comment by AlexStephenLytton** [comment]
Heya... das war auch nicht als "jammern" gedacht, sondern als "vielleicht Hilfestellung" um ein Problem zu erkennen, bzw. einen Fehler auszumachen :)
