### ISSUE TITLE
Translation clarification

### ISSUE THREAD

**Issue by Dzi4d3k** [Mogli12/AIVehicleExtension#4]
Hello,

Regarding following comments:
````xml
<text name="AUTO_TRACTOR_HIRE_ON" text="zużywanie nasion [wył.]" /> <!--Shouldn't be replaced with below?-->
<text name="AUTO_TRACTOR_HIRE_OFF" text="zużywanie nasion [wł.]" /> <!--Shouldn't be replaced with above?-->
<text name="AUTO_TRACTOR_TURN_MODE_O" text="nawrót bez cofania" />
<text name="AUTO_TRACTOR_TURN_MODE_8" text="nawrót bez cofania" /> <!--The same description as MODE 0?-->
````
Suggestion are indeed correct, however I based on English translation, which is following accordingly:
````xml
<text name="AUTO_TRACTOR_HIRE_ON" text="seed usage [off]" />
<text name="AUTO_TRACTOR_HIRE_OFF" text="seed usage [on]" />
<text name="AUTO_TRACTOR_TURN_MODE_O" text="U-turn without going back" />
<text name="AUTO_TRACTOR_TURN_MODE_8" text="U-turn without going back" />
````
As far as my understating goes the same is also in German translation. Maybe some correction is needed?

**Comment by Mogli12** [comment]
Hi,

I think it is still too early to translate this mod into many languages. The texts are just copied from AutoTractor.

Regards, Stefan

**Comment by Dzi4d3k** [comment]
Well, I realized that, but there is my bad that I didn't saw your comments under AutoTractor translation.

**Comment by Mogli12** [comment]
I close all FS17 problems.
