### ISSUE TITLE
Erweiterter Helfer BPG

### ISSUE THREAD

**Issue by max0069** [Mogli12/AIVehicleExtension#42]
Hallo Mogli
Ich nutze sehr gerne den Erweiterter Helfer von BlackPantherGroup (Blacky)
http://www.blackpanthergroup.de/forum/viewtopic.php?f=24&t=591
In der AI Extension V3.0 war das noch kompatible wie beim Standarthelfer.
Jetzt nimmt er einfach irgendeinen Helfer der gerade frei ist.

Kann ich die V3.0 noch irgendwo downloaden oder lässt sich die Kompatibilität wieder herstellen?

Würde mich freuen wenn du mir helfen könntest

Schöne Grüße
Markus

**Comment by Mogli12** [comment]
Hallo Markus,

ich kenne den erweiterten Helfer nicht.

Viele Grüße, Stefan

**Comment by max0069** [comment]
Dann war es wohl Zufall das dies kompatibel war.
Ich habe oben den link dazugegeben, vielleicht lässt sich da ja was machen ohne allzuviel Aufwand. Könnte sein das man angemeldet sein muss um das zu lesen. 

Kann ich sonst bitte die V3.0 noch irgendwo herbekommen?

Schöne Grüße
Markus

**Comment by max0069** [comment]
Danke es funktioniert wieder. 

Noch eine blöde Frage: gibt hier wo ein changelog zum nachlesen, ich hab leider nichts gefunden. 

Schöne Grüße 
max
