### ISSUE TITLE
Claas Dominator 88s funzt nicht mit AI

### ISSUE THREAD

**Issue by Fjalding** [Mogli12/AIVehicleExtension#43]
Hallo Mogli,

ich setze auf meiner Map den Claas Dominator 88s als Mähdrescher ein. Weil das Originalschneidwerk des Dreschers nur 4,2 m hat habe ich mir das klappbare Geringhoff gekauft. Wenn ich dresche und das AI Hud mit Shift/5 starte, wird der Startbutton für den Helfer nicht angezeigt. Das Feld ist dunkelgrau und ohne Funktion. Hast Du eine Idee woran das liegen kann? 

Grüße aus dem Norden

Fjalding

**Comment by Mogli12** [comment]
Hallo Fjalding,

Die Marker für den Helfer sind ohnehin im Schneidwerk und nicht im Drescher. Der Class mit dem normalen Schneidwerk klappt ohne Problem. Ich denke dass es am Geringhoff liegt.

Viele Grüße

**Comment by Fjalding** [comment]
Hallo Stefan,Danke für die Info.Herzliche GrüßeMartinStefan Biedenstein <notifications@github.com> hat am 15. März 2017 um 22:40 geschrieben:Hallo Fjalding,Die Marker für den Helfer sind ohnehin im Schneidwerk und nicht im Drescher. Der Class mit dem normalen Schneidwerk klappt ohne Problem. Ich denke dass es am Geringhoff liegt.Viele Grüße—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
