### ISSUE TITLE
MP v0.3.1.3: Errors on clients side - tractor with front loader

### ISSUE THREAD

**Issue by Dzi4d3k** [Mogli12/AIVehicleExtension#44]
Hi,

I got following errors counting (not excessive but added one by one) on client:
`Error: Running LUA method 'update'.
C:/.../mods/FS17_AIVehicleExtension/AutoSteeringEngine.lua:1090: bad argument #1 to 'pairs' (table expected, got nil)`

when tabbing for the first time to tractor with front loader attached. Detaching and attaching front loader caused that errors where not appearing.

Machines involved:
- FS17_valtraTSeriesCowEdition
- stollFrontLoaderFZ60 (vanilla game)
- FS17_BiobeltzManureFork (ModHUb)

We are also using manual attaching mod form ModHub, which can influence I suppose.

**Comment by Mogli12** [comment]
It should be fix...
