### ISSUE TITLE
Warning on files names

### ISSUE THREAD

**Issue by Dzi4d3k** [Mogli12/AIVehicleExtension#46]
Can these be actually deleted?
Their names generate (cosmetic) warnings on dedicated server.

_not use del AutoTractor.dds
_not use del AutoTractorHud.dds
_not use del_empty.dds

**Comment by Mogli12** [comment]
I think I can delete them. But I am still not finished with the new UI.

**Comment by Dzi4d3k** [comment]
Ok, then this issue can stay as a remainder.

**Comment by Mogli12** [comment]
I deleted the files
