### ISSUE TITLE
0.4.0.8: Probleme mit dem Grimme Tectron

### ISSUE THREAD

**Issue by SuperMaic** [Mogli12/AIVehicleExtension#49]
Moin!

Erstmal vielen Dank, das es das AIVehicleExtension gibt, darauf habe ich gewartet!!!

Aktuell habe ich das Problem, das wenn ich im Grimme Tectron sitze und das AI-Menü über Umschalt-H aufrufe, nichts mehr passiert. Die Maus funktioniert dann nicht mehr oder nur halb, ich kann in den Feldern in der Mitte Werte verändern und das war es dann. Aus dem Menü komme ich nicht mehr zurück ins Spiel und muss es über den Taskmanager beenden.

Meine Logdatei habe ich mit beigefügt, da werd' ich sowieso nicht schlau draus...

Ansonsten funktioniert es (für mich) super, ch würde es vielleicht noch begrüssen, wenn der Drescher sein Abtankrohr bereits bei einem Füllstand von 80 oder 90% automatisch ausfahren würde und nicht erst, wenn man mit dem Schlepper direkt daneben steht. Das wäre klasse!

Gruss
Maic
[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/849961/log.txt)

**Comment by Mogli12** [comment]
Hallo,

der Grimme Tectron sollte jetzt auch funktionieren. Es scheint momentan das einzige Fahrzeug mit Helfer zu sein, welches kein weiteres Anbaugerät benötigt.

Viele Grüße, Stefan
