### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by Dzi4d3k** [Mogli12/AIVehicleExtension#5]
Just a warnings, but better not to have them also:

Load mod: FS17_AIVehicleExtension
Warning: Missing l10n for button AUTO_TRACTOR_UTURN_ON_OFF in FS17_AIVehicleExtension
Warning: Missing l10n for button AUTO_TRACTOR_STEERING in FS17_AIVehicleExtension
Warning: Missing l10n for button AUTO_TRACTOR_RAISE in FS17_AIVehicleExtension
Warning: Missing l10n for button AUTO_TRACTOR_START_AIVE in FS17_AIVehicleExtension

**Comment by Mogli12** [comment]
Hi, this is fixed with 0.1.0.5.
