### ISSUE TITLE
hallo mogli

### ISSUE THREAD

**Issue by iceman234de** [Mogli12/AIVehicleExtension#50]
teste gerade deine version 0.4.0.9 , die drescher bleiben stehen, nur der standart helfer vom spiel funktioniert.  spiele damit auf einem dediserver

gruß Iceman

**Comment by Mogli12** [comment]
Hallo Iceman,
mit dieser kurzen Beschreibung kann ich leider gar nichts anfangen. Eventuell hat ja jemand die 3 gedrückt?
Viele Grüße

**Comment by iceman234de** [comment]
hallo, es scheint auf dem dediserver die pausetaste zu sein, im singleplayer da ging die taste 3 und die drescher fuhren los, auf dem dediserver tut sich mit der taste 3 garnix auch ist die kontourenanzeige am schneidwerk  nicht vorhanden wie im singleplayer . 

gruß Iceman
