### ISSUE TITLE
Test status

### ISSUE THREAD

**Issue by Mogli12** [Mogli12/AIVehicleExtension#51]
Hello everybody,

I want to release AIVehicleExtension in the next days or weeks. Please help and test it with many different vehicles. Please add a comment for every test if:
- there is a problem
- there is no problem and there is no previous comment about the same vehicles

Many Thanks, Stefan

**Comment by Mogli12** [comment]
Case IH 1660 Axial Flow with 1040 cutter:
- Goldcrest field 15 (wheat)
- circular & up'n down

no problems

**Comment by Mogli12** [comment]
NH 8340 with Kuhn Cultimer L300:
- Goldcrest field 14
- up'n down with curved backwards turn

No big problems, but
- The tractor starts with a nearly straight border but with every lane it will add more curves

=> Use standard AI for rectangular fields

**Comment by Mogli12** [comment]
Valtra S374 with Vogel&Noot TerraDisc 600
- Goldcrest field 17
- circular and up'n down
no problems

**Comment by Mogli12** [comment]
Two NH 10.90 with SuperFlex Draper 45ft:
- Goldcrest field 20
- circular with straight backwards turn

no problems, if the 1st vehicle slows down the 2nd will keep its distance

**Comment by cabmac** [comment]
Fendt 700, NH T6 with Mowers (Kuhn,Lely,Poettinger):

-Gemeinde Rade
-circular and up and down,

working realy fine now...and without fps-drops...

**Comment by Mogli12** [comment]
Fendt 700 (AGO) with Vogel&Noot TerraDisc 600
- Sosnovka Not V2 field 14
- up and down

After increasing chain2step0 it stopped oscillating and works fine now

**Comment by Mogli12** [comment]
JD 8530 with 
- Sosnovka Not V2 field 14
- up and down, turn with straight backwards (T)

1. Tractor is turning to inside at the end
2. Detection starts too early at the end of the turn

**Comment by cabmac** [comment]
Case 1455 with Kuhn DC 401 (v1.0 beta 21):

Dreht auf einmal einfach herumm, wenn man den Helfer einstellt, vorherige Version klappt einwandfrei:

http://www.imagehub.de/display-i4549bqdui3.html

**Comment by crab453** [comment]
Having a problem with the mod crashing the server after joining a game for just a few minutes. Issue disappears if AI Extension is removed. I cannot find anything in the logs, unfortunately. 

Forgive me if this is the wrong place to post this, I love this mod.

**Comment by Asghan86** [comment]
WHen will 1.0.0.4 be released to modhub?
