### ISSUE TITLE
hallo

### ISSUE THREAD

**Issue by iceman234de** [Mogli12/AIVehicleExtension#52]

**Comment by iceman234de** [comment]
hallo, funzt alles soweit super, nur hab ich jetzt das problem, wenn die drescher voll sind , dann weiß der helfer nicht ob er das schneidwerk hoch machen soll oder runter und das geht im sekundentakt auch im singleplayer ist das so .

gruß iceman

**Comment by Mogli12** [comment]
AIVehicleExtension Version? Welcher Drescher und welches Schneidwerk?

Gruß, Stefan

**Comment by iceman234de** [comment]
hallo stefan,

aivehicleextension version v1.0 beta1

das war im multiplayer dediserver der newholland cr1090 und das SuperFlexDraper45FT ( mod drescher +schneidwerk )

im singleplayer test war es der case ih 1660 axialflow und das schneidwerk case ih 103014ft ( giants spiel drescher und schneidwerk )

Gruß Andy alias iceman
