### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Zoomi** [Mogli12/AIVehicleExtension#57]
Hallo Mogli,

ich kann leider nur ohne Maus spielen. Zum Einstellen des Mods ist es kein Problem.
seitdem ich neuere Versionen versuche, bleibe ich im Ladebildschirm hängen, da ich Start nicht  auswählen kann. Bei der Version v0.3.1.3 wurde Start immer direkt markiert, bei der aktuellen Version nicht mehr.

Lg Zoomi

**Comment by Mogli12** [comment]
Hallo Zoomi,

mit LShift+H kannst Du den Einstellungsdialog öffenen. Dort kannst Du ab v1.0 beta 4 (nimm aber besser gleich beta 5 wg. #58) mit den Tasten hoch und runter zwischen den verschiedenen Elementen springen. Mit den Tasten rechts und links kann man die Werte ändern.

Viele Grüße, Stefan

**Comment by Mogli12** [comment]
Hallo Zoomi,

kannst Du mir die log.txt schicken? Benutze dazu am besten https://gist.github.com/.

Vielen Dank

**Comment by Zoomi** [comment]
https://gist.github.com/Zoomi/dc21e70dbb92bb283e33c488e5ba5ecc

Ich kann hier aber nichts feststellen. Ich sehe nur eine Warnung.

**Comment by Zoomi** [comment]
bei der  Version v0.3.1.3 ist keine Warnung
