### ISSUE TITLE
V1.0 beta 3

### ISSUE THREAD

**Issue by cabmac** [Mogli12/AIVehicleExtension#58]
Hi, with latest version, mowing (NH T6, Lely and Kuhn) the same field it produces a crash:

Error: Running LUA method 'update'.
C:/Users/Claudio/Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AITurnStrategyMogli_C_R.lua:80: attempt to perform arithmetic on field 'maxLookingAngle' (a nil value)

**Comment by cabmac** [comment]
hi, gerade mit beta 5 gemaeht, auf den "Wendebutton" (wo mann den Wendemodus einstellt) geklickt  und Spiel eingefroren....

**Comment by Mogli12** [comment]
Ich kann das nicht reproduzieren. Allerdings wird das Gras in der Weise am Hof vom Mähwerk auch gar nicht erkannt.

**Comment by cabmac** [comment]
hi, ich kanns auch nicht mehr reproduzieren...keine Ahnung, was das falsch gelaufen ist...war eine modmap....

**Comment by Mogli12** [comment]
Auszug aus dem Changelog der Gemeinde Rade v2.0:
-NaviMesh der Kühe geändert (Map friert nicht mehr ein)
