### ISSUE TITLE
Courseplay

### ISSUE THREAD

**Issue by Paul2510** [Mogli12/AIVehicleExtension#59]
Hi! Erstmal ein grosses Danke das due das Script nach LS17 gebracht hast! Funktioniert schon sehr gut! Ich hab zur zeit nur das Problem das wenn ich mit Courseplay Häcksel das der Häcksler am ende nicht mehr wendet! 

Lg

**Comment by Mogli12** [comment]
Hallo Paul,

mit den normalen Helfer funktioniert es?

Viele Grüße, Stefan

**Comment by Paul2510** [comment]
Hi! Tut mir leid war unterwegs! Ja der normale Helfer arbeitet einwandfrei und wenn ich Ai Vehicle aus dem Modsordn´ner nehme gehts auch mit Courseplay! 

LG

**Comment by Mogli12** [comment]
Gibt es dazu Einträge in der log.txt.

**Comment by Paul2510** [comment]
Guten Morgen! 

Nein hab keine gefunden! Aber ich häng sie an!

LG und schönen Tag!
[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/866971/log.txt)

**Comment by Mogli12** [comment]
Hallo,

Da Courseplay beim Wenden weit vom Drescher weg fährt, klappt die Wende für Kreisfahrt nicht. Das endet in einer Pattsituation: der Drescher wartet auf den Abfahrer und der Abfahrer wartet, dass der Drescher endlich wendet. 

Ich habe Courseplay jetzt nur einmal bei Feld 15 in Goldcrest probiert. Es ist schon unglaublich, wie zielsicher Courseplay sich hier festfährt. Vor allem der Berg unten links in der Ecke scheint den Abfahrer magsich anzuziehen. Ich habe leider keine einzige Wende hinbekommen, ohne dass sich der Abfahrer festgefahren hätte.

Aber mit AIVehicleExtension v1.0 beta 9 sollte der Drescher nicht mehr auf den Abfahrer warten.

Viele Grüße, Stefan

**Comment by Paul2510** [comment]
Vielen Dank! Und danke für deine tolle Arbeit!
