### ISSUE TITLE
Errors on dedicated server with harvesting

### ISSUE THREAD

**Issue by Dzi4d3k** [Mogli12/AIVehicleExtension#6]
Trying to start auto harvesting (couple of times) on multiplayer game (dedicated server) cused lots of errors on both sides:

Server:
https://gist.github.com/Dzi4d3k/a04659d986cea2c3d416883c43f54089

Client:
https://gist.github.com/Dzi4d3k/bf5e184ff21b0fbf01d104516ab346e9

**Comment by Mogli12** [comment]
I hope that this is fixed with 0.1.0.5.

**Comment by Mogli12** [comment]
I assume that this is fixed
