### ISSUE TITLE
beta 5 ,butterfly mowers

### ISSUE THREAD

**Issue by cabmac** [Mogli12/AIVehicleExtension#61]
Hi Stefan,

wenn nach der Wende (egal welcher) der Trecker neu ansetzt, kommt er nicht auf Zielgeschwindigkeit, er kommt ueber 5km/h nicht raus....NUR bei butterfly-MW:

http://www.imagehub.de/display-i4530bpypj1.html

**Comment by Mogli12** [comment]
Hi Claudio,

die Wenden passen noch gar nicht mit 2 Mähwerken. Die entsprechende Funktion zum Aufzeichnen des Wiederaufsetztpunkts konnte ich bislang nahezu unverändert aus AutoTractor übernehmen. 

Aber der Rest sollte jetzt einigermaßen funktionieren.

Viele Grüße, Stefan

**Comment by cabmac** [comment]
Moin, 2 Bahnen hat er einwandfrei gemaeht, bei der naechsten Wende stehen geblieben. Hab ihn  dann manuell wieder angesetzt und dann ist das Spiel eingefroren:

Error: Running LUA method 'update'.
C:/Users/Claudio/Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AutoSteeringEngine.lua:2179: attempt to perform arithmetic on field 'x' (a nil value)

**Comment by cabmac** [comment]
seems to be perfect now.... :)
