### ISSUE TITLE
Courseplay

### ISSUE THREAD

**Issue by Ridlerr** [Mogli12/AIVehicleExtension#65]
Hello

In FS2015 I used to use the autoconbine to mow the fields and the courseplay to unload the mowers and to carry the grain and it worked very well. I tried to do the same, but I came across a problem, the AIV does not release the tractor, after the threshing is based the tractor continues to walk next, the barrel closes but the tractor does not leave there, if I am on the tractor And the stop I do not have problems, being in the harvester I can send the tractor to the route and without problems being in another machine, when the reaper reaches the end of the line and has to turn, the game crashes, doing the same with the helpers of the Giants works no problem. In terms of programming I am a 0 but there it seems that the problem is the harvester does not release the tractor, as it happened in autocombine in FS2015 and in the 1st AIV
Still thank you for the script.

**Comment by Mogli12** [comment]
Hello,

This seems to be a courseplay issue. AIVE does not occupy or release tractors. It just controls the harvester and that's it.

Regards, Stefan

**Comment by Ridlerr** [comment]
Ok Stefan, thanks

**Comment by Mogli12** [comment]
Please feel free to reference the courseplay issue number here and vice versa.

**Comment by Mogli12** [comment]
Hi,

Please check v1.0 beta 9.

Regards, Stefan

**Comment by pops64** [comment]
@Mogli12 I am working on updating CP to work with the current version of AIVE. So I have one bug I can't figure out what is going. If I allow CP to pass  acIsCPStopped true when the tipper and the combine arrive at the field edge at the same time AIVE turns off and leaves the cruise control set. If I prohibit acIsCPStopped from being set to true using guesses at the turn stage that causes this behavior AIVE will stop but when the tipper finishes unloading to go park AIVE will turn of with a helper block message. The other bug which I have seen once is when it is unloading and arrives at field edge the tipper will drive off but then AIVE will drive foward some amount of distance before turning. acIsCPStopped I think was passed true in this case. 

A list of variables that were updated and just wanting to confirming correct updating
```
acDirectionBeforeTurn.traceIndex+1 = aiveChain.trace.traceIndex+1
acDirectionBeforeTurn.trace = aiveChain.trace.trace
acDirectionBeforeTurn.trace[index].dx = aiveChain.trace.trace[index].dx
acDirectionBeforeTurn.trace[index].dz = aiveChain.trace.trace[index].dz 
```

Thanks for reading this. I just wanted to hear your thoughts on how to correct this. Like is there a set of variables that have to be passed to AIVE to tell it to resume if I avoided the situations that cause the behavior of acIsCPStopped or this something that you can fix on your end. Check out my fork of CP it is under AC-Support branch if you need a working copy of CP with AIVE to help with this. Thanks again

**Comment by pops64** [comment]
I hate asking cause I know we are super busy as well. Have you had a chance to look at this? I would like to get this pushed out to the CP master branch. Thanks

**Comment by Mogli12** [comment]
Hi, the renaming of variables is correct. But why do you access them?

**Comment by pops64** [comment]
They are used to tell the tipper  unloading the combine where he is so the tipper knows where to park. Have you any thoughts on the other issue. I have played àround with it and it seems the helper blocked message might be because AIVe doesnt see the fruit any more.

**Comment by Mogli12** [comment]
Can specify what you really need from AIVE? I could create the necessary functions to GET or SET something in AIVE. Ok, starting from that CP version it would not work with the older (and already released) versions of AIVE. But that's all and we would have a clear interface between CP and AIVE.

**Comment by pops64** [comment]
Well it looks like CP was already setup to use acIsCPStopped. So was auto combine. The problem is when I pass acIsCPStopped = true to tell AIVE to stop it doesn't at certain turn stages. If I avoid passing that value to AIVE it will stop but doesn't resume work. [Video](https://www.dropbox.com/s/b88e12wxio4zud5/FarmingSimulator2017%2064bit%205_9_2017%201_09_31%20PM.mp4?dl=0) to show you what I am talking about. If it is possible I would like to keep using acIsCPStopped = true to stop AIVE when the turn stage is not 0. But if there are certain turn stages where this can't happen (41 and 21 I know don't work) is there a way to restart or resume AIVE

**Comment by Mogli12** [comment]
So it would be sufficient to react on acIsCPStopped?

**Comment by Mogli12** [comment]
Ok, the combine will not always stop if acIsCPStopped is true. Additionally, I create a function 
```lua
------------------------------------------------------------------------
-- AIVehicleExtension:stopCoursePlayMode2
------------------------------------------------------------------------
function AIVehicleExtension:stopCoursePlayMode2( stopCP )
	if      ( stopCP or self.acStopCP ) 
			and self.courseplayers       ~= nil
			and self.courseplayers[1]    ~= nil
			and self.courseplayers[1].cp ~= nil then
		
		if stopCP then
			if not ( self.courseplayers[1].cp.forcedToStop ) then
				self.courseplayers[1].cp.forcedToStop = true
				self.acStopCP = true
			end
		elseif self.acStopCP then
			self.acStopCP = nil
			self.courseplayers[1].cp.forcedToStop = false
		end
	end
end
```
I have a new turn mode for a combine in circular mode, which does not need much space. In this case I will stop the tractor, push back just a little and continue.

**Comment by pops64** [comment]
Seems to work. Saw only one weird behavior. AIVE was chasing down little strands of corn while CP was approaching in circular mode. And it forced CP to stop while it was within a few feet.  But this is not a major issue so I am not concerned about it and AIVE would need reset anyways in this case. I will test some more and hopefully push it out to CP master branch in a little bit. Thanks for the help.

**Comment by pops64** [comment]
I have played around with changing `self.courseplayers[1].cp.forcedToStop` in your function to `self.courseplayers[1].cp.isACStopped` and it is working as well as to be excepted in circular mode. Am going to test in up down mode but I don't expect to see any issues.

**Comment by pops64** [comment]
So I was testing choppers. And was wondering if there is a variable for telling if it is updown mode or circular? Are new tipper turn maneuvers don't work with circular so I have to tell it not to use them in that mode. Thanks

**Comment by pops64** [comment]
Hey I had some discussion with Thomas. And we would prefer it if not to have the new function and for acIsCPStopped to work all the time. We use if a) we are to close and want to move out of the way because we have finished unloading or b) we have gotten to close on approach that if the tractor turns CP will struggle to adjust to the new direction. It is still up to you. I have a temp fix for CP for the problem I mentioned above that I am going to test and if it is good I will release it to CP master. Thanks again for all your.

**Comment by Mogli12** [comment]
I create the new function to stop CP because:
- the tractor has to stop before the combine starts to turn. Otherwise the tractor is too far in front
- the combine will push back and then turn right or left. Once the turn starts the tractor is released
- the tractor should not starts its turn maneuver. It needs way to much space. In fact I was not able to use AIVE and courseplay on a normal field in Goldcrest. I always ended with the tractor being somewhere stuck.

**Comment by pops64** [comment]
Yea sorry I was doing some more testing I was didn't know what turn mode 7 was. How it is setup is fine

**Comment by pops64** [comment]
Alright for those of you that use AIVE. CP has now been updated to be compatible with AIVE in version 139 or higher. Also **Requires AIVE Version 1.1 b3 or higher**

@Mogli12 Thanks for a the help and understanding in getting theses two great mods working with each other again.

**Comment by pops64** [comment]
@Mogli12 is there a variable that we could use to determine if AIVE is active? Atm I have `if tractor.acParameters ~= nil and tractor.acParameters.enabled and tractor.isHired then` this causes issues CP is running the combine and not AIVE until I turn off AIVE. Thanks
