### ISSUE TITLE
Warning in log

### ISSUE THREAD

**Issue by Dzi4d3k** [Mogli12/AIVehicleExtension#68]
Just a cosmetic one, but worth polishing out for final release:

`Warning: i3d contains non-binary indexed triangle sets: d:/.../mods/FS17_AIVehicleExtension/AutoCombine.i3d
d:/.../mods/FS17_AIVehicleExtension/AutoCombine.i3d (0.47) ms
`

I think saving in GE as binary .i3d (creating .shapes file) will solve issue.

**Comment by Mogli12** [comment]
Hi, I want to keep it non-binary so I can edit the triangles with notepad++

**Comment by Dzi4d3k** [comment]
Oh, that's clear now :)

**Comment by Mogli12** [comment]
Normal saving in GE does not create a shape file. And I did not find a save as binary. So how can I convert it to binary format?

**Comment by Dzi4d3k** [comment]
In fact can be missed, but please look on attached screenshoot:
![save_as_binary_i3d](https://cloud.githubusercontent.com/assets/12050055/24513672/1402d83c-1572-11e7-94ac-fbb4b95f3354.png)
