### ISSUE TITLE
log warnings seit v1.0 beta

### ISSUE THREAD

**Issue by mngrazy** [Mogli12/AIVehicleExtension#69]
servus stefan

ich schreib heut ma auf deutsch ^^

seit der v1.0 beta hab ich log warnungen wenn ich das spiel beende / fahrzeug verkaufe oder missionen beende

Warning: Deleting object 'otherCombColliTriggerL' before all triggers are removed.
Warning: Deleting object 'otherCombColliTriggerR' before all triggers are removed.

zuletzt mit der Beta 9 getestet 

grüsse grazy

**Comment by mngrazy** [comment]
thx stefan

die warnings sind nun weg , nur noch eine wegen der missing shapes von deiner i3d
aber denke mal das wird mit der release version dann noch beseitigt werden

danke und grüsse

**Comment by Mogli12** [comment]
Hallo,

dazu gibt es bereits #68. Ich werde den Abstandshalter und damit die Trigger und die i3d wieder ausbauen. Zusätzliche Funktionen sollen Probleme lösen und nicht neue schaffen (#47).

Viele Grüsse
