### ISSUE TITLE
Want to join the Chinese language

### ISSUE THREAD

**Issue by Simba76** [Mogli12/AIVehicleExtension#7]
@Mogli12  Hello.
         First of all thank you for your work and dedication, bring us great MOD.
I am a player from China, we have a lot of players like you MOD, I hope this MOD can support Chinese language.
You can create a 'modDesc_l10n_ru.xml', I will do Chinese translation.
Thanks again @Mogli12 .

**Comment by Mogli12** [comment]
Hi Simba76,

the modDesc_I10n_ru.xml is there:
https://github.com/Mogli12/AIVehicleExtension/blob/master/FS17_AIVehicleExtension/modDesc_l10n_ru.xml

But I think it is much too early to translate it now. Please notify the version number 0.1. 

Regards, Stefan
