### ISSUE TITLE
Dedi server , AutoSteeringEngine.initSteering called at client

### ISSUE THREAD

**Issue by mngrazy** [Mogli12/AIVehicleExtension#72]
tach stefan

sobald ich auf dem dedi server ein gerät anhänge , kommt folgender fehler

ERROR: AutoSteeringEngine.initSteering called at client

oder auch

ERROR: AutoSteeringEngine.setChainStatus called at client

zudem wenn ich vom dedi server gehe kommt folgendes

Warning (LUA): 'unlink': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType
LUA call stack:
  =D:/_FS17_Play_Mods_MP_/FS17_AIVehicleExtension/AutoSteeringEngine.lua (6274) : unlink
  =[C] (4294967295)
  =D:/_FS17_Play_Mods_MP_/FS17_AIVehicleExtension/AutoSteeringEngine.lua (6311) : deleteNode
  =D:/_FS17_Play_Mods_MP_/FS17_AIVehicleExtension/AIVehicleExtension.lua (293) : deleteChain
  dataS/scripts/vehicles/Vehicle.lua (1490) : preDelete
  dataS/scripts/network/NetworkNode.lua (70) : delete
  dataS/scripts/network/Client.lua (48) : delete
  dataS/scripts/BaseMission.lua (298) : delete
  dataS/scripts/FSBaseMission.lua (535) : delete
  dataS/scripts/missions/mission00.lua (84) : delete
  dataS/scripts/events.lua (125) : delete
  dataS/scripts/gui/InGameMenu.lua (446) : OnInGameMenuMenu
  dataS/scripts/gui/InGameMenu.lua (603) : leaveCurrentGame
  dataS/scripts/gui/elements/ButtonElement.lua (319) : raiseCallback
  dataS/scripts/gui/elements/FocusManager.lua (254) : onFocusActivate
  dataS/scripts/gui/elements/GuiElement.lua (304) : checkElement
  dataS/scripts/gui/elements/GuiElement.lua (319) : update
  dataS/scripts/gui/elements/GuiElement.lua (319) : update
  dataS/scripts/gui/elements/GuiElement.lua (319) : update
  dataS/scripts/gui/elements/GuiElement.lua (319) : update
  dataS/scripts/gui/elements/Gui.lua (303) : update
  dataS/scripts/main.lua (1872) : update

log vom server is clean ,,,, nur client log enthält diese fehler

grüsse grazy

**Comment by Mogli12** [comment]
Hallo Grazy,

Ok, alle 3 Probleme sind nicht so kritisch, dass ich sofort eine neue Version dafür machen müsste. Ich werde es versuchen mit der nächsten Version zu beheben.

Viele Grüße, Stefan

**Comment by mngrazy** [comment]
Error: Running LUA method 'loadSharedI3DFileFinished'.
D:/home/sid_169796/farmingSim_2017/profile/mods/FS17_AIVehicleExtension/AIVehicleExtension.lua:1633: attempt to index global 'veh' (a nil value)

mit Beta 13 startet der dedi server nicht mehr

**Comment by Mogli12** [comment]
v1.0 beta 13 => das musste ja schief gehen. Wenigstens ist heute nicht Freitag.

**Comment by mngrazy** [comment]
hehe , kleine fehler können passieren stefan :)

alles fein nun auf dem dedi server ! das kleine HUD erscheint nun auch wieder und alles funzt

THX , hier kann dann geschlossen werden 

grüsse grazy
