### ISSUE TITLE
works for few meters

### ISSUE THREAD

**Issue by simonebrunori** [Mogli12/AIVehicleExtension#73]
the AIVE work for only few meters, then stop and go ahead and back in loop.
Sorry for my bad english

**Comment by Mogli12** [comment]
Hi,
I do not have a problem with bad English. I am not a native English speaker. But could you please describe the problem in more details?
- tractor
- tool
- map
- field number
If possible please add a screen shot and the log.txt (in gist, the link is at the top)
Thanks, Stefan

**Comment by simonebrunori** [comment]
![fsscreen_2017_03_27_19_16_24](https://cloud.githubusercontent.com/assets/26582370/24369462/5e6844f2-1324-11e7-933e-b506728b534b.png)
![fsscreen_2017_03_27_19_26_44](https://cloud.githubusercontent.com/assets/26582370/24369521/94778dfa-1324-11e7-8c86-341aa2855dc4.png)
![fsscreen_2017_03_27_19_16_28](https://cloud.githubusercontent.com/assets/26582370/24369520/94771226-1324-11e7-8e90-3437df1cd8b8.png)
![fsscreen_2017_03_27_19_16_35](https://cloud.githubusercontent.com/assets/26582370/24369522/9477c7c0-1324-11e7-946d-919d6aae64e9.png)
![fsscreen_2017_03_27_19_16_49](https://cloud.githubusercontent.com/assets/26582370/24369524/947d8d90-1324-11e7-861d-33fc348d9b68.png)
![fsscreen_2017_03_27_19_19_43](https://cloud.githubusercontent.com/assets/26582370/24369523/947c6636-1324-11e7-80dd-6f542e49fbee.png)
![fsscreen_2017_03_27_19_19_54](https://cloud.githubusercontent.com/assets/26582370/24369525/94818e54-1324-11e7-978b-9e441921e72e.png)
![fsscreen_2017_03_27_19_19_56](https://cloud.githubusercontent.com/assets/26582370/24369526/94921d82-1324-11e7-8e59-137ecb6a5f83.png)
![fsscreen_2017_03_27_19_20_02](https://cloud.githubusercontent.com/assets/26582370/24369527/949319b2-1324-11e7-9fbb-b4885d887886.png)
![fsscreen_2017_03_27_19_20_17](https://cloud.githubusercontent.com/assets/26582370/24369528/9495e840-1324-11e7-9193-8645489b85d5.png)

**Comment by simonebrunori** [comment]
log: https://gist.github.com/simonebrunori/5c714c16b28689c65a1b5d510f3337f7
I am playing in Old Stream Map V2.
I noticed that I have this problem only in the same point, It is likely to be the field slope?

**Comment by Mogli12** [comment]
Hi,
If this happens you can only stop the hired worker, navigate to the best position and restart it.
Regards, Stefan

**Comment by Mogli12** [comment]
Does it work for you with the latest version?

**Comment by simonebrunori** [comment]
I will tra it this evening

**Comment by Mogli12** [comment]
Does it work?

**Comment by simonebrunori** [comment]
Thanks, now it is working perfectly
