### ISSUE TITLE
aive und ölrettich

### ISSUE THREAD

**Issue by iceman234de** [Mogli12/AIVehicleExtension#75]
Hallo stefan,
Folgendes habe die horsch pronto 9dc und den aive 1.0 beta 15 mir ist aufgefallen wenn ich ölrettich pflanze dann fährt der aive immer nur aussen ums feld herum fährt aber nie in die 2. Reihe . Trekker hatte ich verschiedene sowohl auch mod trekker oder spiele trekker immer das selbe aufm dediserver 

Gruß Andy

**Comment by iceman234de** [comment]
hi nochmal

so, habe jetzt ölrettich selber gepflanzt und nun säht er auf die selbe art anderes getreide an, auch nur aussen rum, kommt nicht in die nächste spur

gruß Andy

**Comment by Mogli12** [comment]
Hallo,
probier mal eine andere Sämaschine ohne Direktsaat aus.
Gruß, Stefan

**Comment by Mogli12** [comment]
Oder nimm die v1.0 beta 18...

**Comment by Mogli12** [comment]
Hallo Andy,

kannst Du es bitte nochmal mit v1.0 beta 22 testen?

Danke, Stefan

**Comment by iceman234de** [comment]
Klar stefan kann ich machen , gebe dann bescheid . Gruß Andy

**Comment by iceman234de** [comment]
hi stefan, das ölrettich säen funktioniert recht gut, fährt jetzt schön im kreis und setzt tadellos in die 2. reihe ein .

gruß andy
