### ISSUE TITLE
One combine per field??

### ISSUE THREAD

**Issue by Stepa27** [Mogli12/AIVehicleExtension#77]
Hello, i am testing beta19 version and noticed that only 1 combine can be on the field. Other combines work than stop. Its all confusing to me.

Is there any chance to practically conver AuytoCombine 4.1 from FS15?

**Comment by Mogli12** [comment]
Yes, only one hired worker per field. But in AutoCombine it was not different.

And no, it is not possible to convert AutoCombine to FS17: https://github.com/Mogli12/AutoCombine/issues/18.

**Comment by Stepa27** [comment]
Its not true, it was possible to hire at least 3 workers, i personally tested and played like that!

If you can hire only one worker per field, than your mode is useless! I don't see the point.

**Comment by Stepa27** [comment]
And stop closing subjects when they are not closed. Stop hiding from real problems.

**Comment by sootysax** [comment]
where's the mods that you created and put out into the community Stepa?

**Comment by Mogli12** [comment]
I do not want to support one than one hired work per field. There is no need for further discussions or to keep this ticked open. Not to support one than one worker is not a bug. It is just a missing feature. And I decided not to implement this feature.

**Comment by omegaMV6** [comment]
@Mogli12, first many thanks for your great work! I´m only a little user and don´t know how much work it is to implement the feature to hired more than one worker. But I can understand Stepa27. 

In FS15 on a large Field I´ve hired two workers for Harvester (for example one started in north-west, one in south-east). Than i´ve hired four or maybe five workers with Coursplay to drive the harvest to Farmsilo. So I can play maps like the "Altkirch im Elsass" or the "DonDiego map" as a single player. Now in FS17 with one Harvester it takes too much time to play such maps. Now you can say play maps with smaller fields but I love to play maps with large fields and two or if possible three Harvester that working with your AIVehicleExtension aka Autocombine. 

So maybe you thinking about to implement the feature for two or three workers. I´m sure many users wouldt thank you for this. This is just my opinion! It´s your mod and you have to decide. Thank you for reading.

Sorry for my bad english, i´m from germany. (Und ja, ich weiß Du auch. Aber dies ist ein internationales Forum, also sollten möglichst viele User dies hier lesen können ;)   )

Greetings
omegaMV6
