### ISSUE TITLE
Multiplayer 

### ISSUE THREAD

**Issue by Ibizahansi** [Mogli12/AIVehicleExtension#78]
Hallo Mogli, 
Ich bzw wir haben das Problem das meine Kollegen nicht auf mein Spiel kommen können wenn ich den AIVE drin habe. Obwohl sie die gleiche Version haben. Woran kann das liegen? 
Sollte ja eigentlich MP tauglich sein oder? 

Danke für deine Hilfe im voraus. 
Gruss Hansi

**Comment by Mogli12** [comment]
Hallo Hansi,

Mit der Problembeschreibung kann ich leider so nichts anfangen. Gibt es Log-Meldungen am Server oder Client? Oder haben die Kollegen einfach nur die falsche Version von FS17_AIVehicleExtension?

Gruß, Stefan

**Comment by Ibizahansi** [comment]
Keine Fehlermeldung, nix dergleichen sie können meinem spiel nicht beitreten. Ich habe ihnen die gleiche Datei geschickt wie ich sie im Mod ordner habe.

**Comment by Ibizahansi** [comment]
Kann es vielleicht am follow me Mod liegen?

**Comment by Mogli12** [comment]
Hallo,

Wenn die Kollegen Dein Spiel nicht betreten können, dann kann es meiner Ansicht nach nur an fehlenden oder unterschiedlichen Mods liegen. Zu diesem Zeitpunkt werden nur die Hash-Werte der ZIP-Dateien überprüft, aber nicht der Inhalt.

Viele Grüße, Stefan

**Comment by Ibizahansi** [comment]
Ja das stimmt schon, es wird aber nur angezeigt das der AIVE nicht stimmt obwohl es der gleiche ist. Sobald ich das spiel starte ohne den AIVE können sie beitreten

**Comment by Mogli12** [comment]
Wenn da steht, dass es nicht gleich ist, dann ist es auch nicht gleich.
