### ISSUE TITLE
Case 1455 with Kuhn DC 401 (v1.0 beta 21):

### ISSUE THREAD

**Issue by Mogli12** [Mogli12/AIVehicleExtension#79]
from @cabmac:

Case 1455 with Kuhn DC 401 (v1.0 beta 21):

Dreht auf einmal einfach herumm, wenn man den Helfer einstellt, vorherige Version klappt einwandfrei:

http://www.imagehub.de/display-i4549bqdui3.html

**Comment by cabmac** [comment]
perfect now...
