### ISSUE TITLE
Callstack beim Pflügen

### ISSUE THREAD

**Issue by Echelon2k** [Mogli12/AIVehicleExtension#80]
Habe eben auf die neueste Version geupdated (beta 23) und mein Server hatte mehrfach abstürze beim pflügen. Könnte auch am hoster gelegen haben aber beim log anschaun fielen mir callstacks auf.

Habe nun die vorrige Version (beta 22) installiert. Callstacks sind zwar noch da, aber der Server läuft zumindest wieder rund.

[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/933491/log.txt)

**Comment by Mogli12** [comment]
Hallo,
das sind Warnungen und können ignoriert werden. Daran kann es nicht liegen.
Viele Grüße, Stefan

**Comment by Echelon2k** [comment]
war im urlaub und hab vergessen bescheid zu geben. Die "Abstürze" lagen daran, dass der Hoster technische probleme hatte. Kann also als erledigt betrachtet werden.
