### ISSUE TITLE
Release notes please

### ISSUE THREAD

**Issue by BigBud1100** [Mogli12/AIVehicleExtension#81]
Hallo Mogli
Can you please write release notes when you make update. What was changed in beta 23 from beta 22?
Good job on b22, thank you.

**Comment by Dzi4d3k** [comment]
Did you missed commit comment:
"Different algorithm to check if hired worker is finished"?

**Comment by Mogli12** [comment]
I write a short note in the commit.

**Comment by BigBud1100** [comment]
ahhh, i finally faound commits.. sorry
