### ISSUE TITLE
G27/G29 Shifter Sequential Mode

### ISSUE THREAD

**Issue by Tanglewolf** [Mogli12/AIVehicleExtension#82]
Hi, im really enjoying the mod and its adding a lot of immersion to my gameplay, iv specifically purchased the shifter for the g29 wheel to work alongside to get the full experience you have brought to the game

As a possible feature for the future, would it be possible to select a mode for the shifter? from manual to auto mode.

Where in manual mode it would select individual gears, as it currently does, but in auto mode it would work as a sequencial shifter, 

buttons 2+3  = gear up/ gear down    1+2 = range up/rangedown      5+6 = forward/backward 

just a thought, thanks for sharing what you have done so far

 dave

**Comment by Dzi4d3k** [comment]
Shoudn't this been opened under GearboxAddon mod?
https://github.com/Mogli12/GearboxAddon

**Comment by Mogli12** [comment]
Hi,

This issue is at the wrong repository. But I think this is too complicated.

Regards, Stefan
