### ISSUE TITLE
headlands

### ISSUE THREAD

**Issue by Maogami** [Mogli12/AIVehicleExtension#83]
Hello, how to do headlands with AiVehicleExtension? 
I'm posting this as Issue because I can't find this option, atm  I can only harvest in circles or normal zig-zag without headlands. I would really get use of this option.

**Comment by Mogli12** [comment]
Rshift-H opens the options dialog.

**Comment by Maogami** [comment]
yes i know but i dont see any headlands option :x

**Comment by Mogli12** [comment]
Middle column, the 4th button from top / 2nd button from bottom.

**Comment by Maogami** [comment]
Is this option my mouse is placed? If yes, this translation from eng to pl is wrong. It means (as i thought) space between combines, if you set 2 combines in 1 field then this second combine with this option enabled will be moved to the left or right by this distance.

Instead of "odstęp" there should be something like "zatoka" 

Anyway thanks for help :)

**Comment by Maogami** [comment]
Your suggested option doesn't work :/

**Comment by Mogli12** [comment]
What does not work?

**Comment by Maogami** [comment]
Ok, let's try another way.
How does your mod work? Can it do 2-3 headlands and then zig'zag harvesting or I have manually to set him up for 2-3 headlands and then reset him to zig'zag?

**Comment by Mogli12** [comment]
For harvesting I would first go in circles and switch it manually to "zig-zag". The headland setting is for ploughing, seeding, etc.

**Comment by Maogami** [comment]
Thanks for info
