### ISSUE TITLE
The helper suddenly stopped working - unknown reason

### ISSUE THREAD

**Issue by MAOGAMI** [Mogli12/AIVehicleExtension#84]
Hey, its me again. Now I have problem stricte with helper. Its all ok when helper drives straight, but when it comes to corrner he just stop in place. Here is explanation video below

https://youtu.be/44VvIes3Ejk

**Comment by Mogli12** [comment]
stops in turn stage 94 - maybe a time out?

**Comment by Mogli12** [comment]
Hi,
Can you re-test it with Version 1.1 beta 01?
Regards, Stefan

**Comment by Maogami** [comment]
Sure, gonna try it today

**Comment by Maogami** [comment]
Hey Stefan, I haven't tried sowing after update but tried harvesting on irregular field.
 Here's the video. 

https://youtu.be/FCd5lOexJR4

Basically, helper is shortcutting his way, not following edge of the field. Which result is being stuck very often.

I don't really know if I'm doing something wrong all the time or all of my problems are bugs in code, but it would be cool if you could record tutorial video or something. :)

**Comment by Mogli12** [comment]
Hi,

Fields in inline corners (L-shape) will not work.

Regards, Stefan

**Comment by Maogami** [comment]
In order to make it work again, I have to follow steps shown in the picture, right?
Correct me if I'm wrong

 [http://imgur.com/a/PPwEs](url)

**Comment by Mogli12** [comment]
Hi, I cannot load the picture (HTTP 404)... :-(

**Comment by Maogami** [comment]
I hope this one wont disappear [https://p11i.imgup.net/Beztytuub5f6.png](url)

**Comment by Maogami** [comment]
![bez tytulu](https://cloud.githubusercontent.com/assets/28206886/25714972/11448c1e-30fa-11e7-82a1-929cc41a1743.png)

**Comment by Maogami** [comment]
Hey Stefan, I think there is something for you in this log

[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/980891/log.txt)

**Comment by Mogli12** [comment]
I did not check the log. Can you open a new issue and add some details how to got this log?

About the L or U shaped field. If you are sowing just circle manually around the area you want for work on. Now switch on the option in column 3 and row 4 and start working on the area in the inside and start the hired worker.
