### ISSUE TITLE
nice mod aber eine frage 

### ISSUE THREAD

**Issue by Lakto1220** [Mogli12/AIVehicleExtension#85]
ist es möglich die Geschwindigkeit der Helfer zu erhöhen?

mfg lakto1220

**Comment by Mogli12** [comment]
Hallo,
nein, AI Vehicle Extension ändert nichts an den Geschwindigkeitseinstellungen. Gerade bei schnelleren Tätigkeiten (z.B. Grubbern) macht es den Traktor sogar etwas langsam, weil der Mod ansonsten mit dem Lenken nicht nach kommt. Daher ist häufig schon bei 13 km/h Schluss.
Viele Grüße
