### ISSUE TITLE
Probleme im MP mit Dedi Server

### ISSUE THREAD

**Issue by Mortime2301** [Mogli12/AIVehicleExtension#86]
Guten Abend Stefan,

zunächhst mal großes Lob für diesen genialen Mod.
Ich würde ihn gerne nutzen. Leider gibt es Probleme auf meinem Dedi-Server (Gamed.de)
Ist der Mod aktiv passiert folgendes: Starte ich den Helfer (HelperAdvanced Mod), dann erkennt er zum einen den Feldrand nicht. Das Frontgerät (manchmal auch das Gerät hinten) bleibt einfach an der Stelle "kleben" und der Traktor fährt alleine weiter. Allerdings auch ohne den Rand zu erkennen (es ist auch keine Spur sichtbar). Deaktiviere ich den Helfer, dann springen die Geräte zurück an den Traktor. Das gleiche passiert auch beim Drescher. Das Schneidwerk bleibt einfach an der Startstelle kleben. Ich kann dann auch nicht mehr durch die Fahrzeuge springen. Im Singleplayer hab ich gar keine Probleme. Da funktioniert alles.
Ich benutze die Version 1.01. B01.
Spiel und Server ist auf 1.4.4. 
Im Log scheint es auch Fehler zu geben "Warning: Send called with unknown target address."
Im Client-Log: "Error: Running LUA method 'update'.
C:/Users/Mortime/Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AutoSteeringEngine.lua:464: attempt to compare nil with number"
Bei Bedarf kann ich gerne weitere Infos und Daten liefern (wie komplette Logs z.b.).
Ich hoffe du kannst damit schon was anfangen ?! Ich wäre dankbar für einen Tip oder eine Lösung, da ich den Mod wirklich gerne benutzen würde.
Danke im Voraus.

Beste Grüße
Guido

**Comment by Mogli12** [comment]
Hallo Guido,

die Meldung "Warning: Send called with unknown target address." kommt so eher nicht aus AIVehicleExtension. Ich vermute, dass hier ein eher generelles MP-Problem vorliegt. Es reicht, dass ein einziger MOD einmal ein Byte zu wenig oder zu viel überträgt, so dass im MP in anderen Mods ein Fehler auftritt.

Viele Grüße, Stefan

**Comment by Mortime2301** [comment]
Hallo Stefan, danke für die Rückmeldung. Das kann natürlich sein. Die Meldung "Error: Running LUA method 'update'. C:/Users/Mortime/Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AutoSteeringEngine.lua:464: attempt to compare nil with number" kommt jedoch von AIVE. Davon habe ich etliche im Client-Log. Ich habe nochmal geschaut. Die Meldung "Warning: Send called with unknown target address." kommt evtl. von AutoDrive Mod. 

Was kann ich denn machen um den Fehler weiter einzugrenzen ? Die anderen Mods laufen eigentlich ohne Probleme.
Beste Grüße
Guido

**Comment by Mogli12** [comment]
Hallo Guido,

keine Ahnung, wie Du im Client zur Coding-Zeile FS17_AIVehicleExtension/AutoSteeringEngine.lua:464 kommst. Die Funktion darf nur im Server gerufen werden. Aber bislang hatte auch noch niemand dieses Problem, auch Giants nicht. Daher gehe ich von einer Unverträglichkeit mit anderen Mods aus. Nur, wenn das Problem mit FS17_AIVehicleExtension und sonste keinem anderen Mod reproduzierbar wäre, würde ich es mir anschauen.

Viele Grüße, Stefan

**Comment by Mortime2301** [comment]
OK Ich teste es mal und melde mich wieder.

**Comment by Mortime2301** [comment]
Reicht es die Mods im Spiel zu deaktivieren oder müssen die komplett aus dem Ordner entfernt werden ?

**Comment by Mogli12** [comment]
Deaktivieren sollte reichen.

**Comment by Mortime2301** [comment]
Guten Morgen Stefan,
bin gestern Abend noch zum testen gekommen. Folgendes konnte ich ermitteln:
- Alle Mods (bis auf deinen) entfernt (musste ich komplett aus dem Ordner entfernen, da sie sonst geladen wurden)
- Komplett neuen Spielstand auf dem Dedi-Server angelegt (Goldcrest Val.)

Ergebnis:
Leider gleicher Fehler. Siehe Log-Datei
[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/988921/log.txt)

Nächster Test (ich hoste ein MP-Spiel):
- Alle Mods entfernt (bis auf deinen)
- Komplett neuen Spielstand auf dem Dedi-Server angelegt (Goldcrest Val.)

Ergebnis:
Alles läuft wie es soll. ;-)

 Im Single-Player mit allen Mods auch keine Probleme.

Ich wäre dir dankbar, wenn du dir das mal ansehen könntest. Ich bin auch gerne bereit dich zu unterstützen um eine Lösung zu finden.

Beste Grüße
Guido

**Comment by Mogli12** [comment]
Hallo Guido,

ich habe in v1.1 b02 zusätzliche Fehlermeldungen eingebaut. Kannst Du die Version mal probieren und mir dann die Log-Datei von Server und Client schicken?

Vielen Dank, Stefan

**Comment by Mortime2301** [comment]
> Mache ich gerne heute Abend. Melde mich...

**Comment by Mortime2301** [comment]
Hi Stefan,
sorry leider geht in der Version das HUD nicht auf wenn ich STRG+H drücke.

Gruß
Guido

**Comment by Mogli12** [comment]
Log?

**Comment by Mortime2301** [comment]
Guten Morgen Stefan,
im Log stand nichts drin, da ich den Aive auch nicht aktivieren konnte. Oder war das so beabsichtigt ?

Gruß Guido

**Comment by Mogli12** [comment]
Hallo Guido,

kannst Du mir trotzdem beide Logs schicken? Wenn STRG+H nicht klappt, dann scheint AIVE gar nicht zu laufen.

Viele Grüße, Stefan

**Comment by Mortime2301** [comment]
Klar kann ich die heute Abend schicken. OK dann prüfe ich nochmal. Evtl hat der Server den Mod nicht geladen. Melde mich heute Abend.

**Comment by Mortime2301** [comment]
Hallo Stefan,

so jetzt hat´s geklappt. Tatsächlich wurde der Mod nicht geladen. Sowas sollte man auch nicht machen, wenn man total müde ist. ;-)

Jetzt scheint es funktioniert zu haben. Allerdings fehlt immer noch die Spur und die Buttons sehen auch anders aus als im Singleplayer. Hab mal einen Screenshot gemacht. 
![fsscreen_2017_05_11_20_01_15](https://cloud.githubusercontent.com/assets/28511017/25964617/c9e22d72-3685-11e7-9fa3-e50a694e7975.png)
Jedenfalls scheint er sauber übers Feld zu fahren.

Hier die Logs:
Client: [log.txt](https://github.com/Mogli12/AIVehicleExtension/files/994016/log.txt)
Server: [log_srv.txt](https://github.com/Mogli12/AIVehicleExtension/files/994017/log_srv.txt)

Ich hoffe das hilft dir weiter ?!
Gruß
Guido

**Comment by Mogli12** [comment]
Hallo Guido,

Du hast "autoSteer" in MP getestet. Aber irgendwie klappt das so gar nicht. Ich werde es vorerst in MP deaktivieren.

Vielen Dank, Stefan

**Comment by Mortime2301** [comment]
Guten Morgen Stefan,

Ist das Autosteer denn Voraussetzung? Was macht das denn ?

Beste Grüße 
Guido

Von meinem iPhone gesendet

**Comment by Mogli12** [comment]
Hallo Guido,

ich denke, dass Du im Client auf den Button mit dem Lenkrad gedrückt hast (oder LAlt+H).

Viele Grüße, Stefan

**Comment by Mortime2301** [comment]
Ja habe ich. Ich dachte das ist nötig damit der auch lenkt ?! Scheinbar ist das wohl nicht nötig?! Was bewirkt diese Funktion denn ?

Von meinem iPhone gesendet

**Comment by Mogli12** [comment]
Damit übernimmt AIVE nur die Lenkung. Gasgeben, Wenden, etc. muss man aber selber machen. Also einfach erstmal den Button nicht drücken.

**Comment by Mortime2301** [comment]
Guten Morgen Stefan, so ich habe nochmal die B01 Version ohne Autosteer getestet. 

Funktioniert soweit. Was mir jedoch aufgefallen ist. Sobald ich mehr als einen Helfer gleichzeitig mit Aive fahren lasse fängt der Server stark an zu laggen. 

Hast du eine Idee woran das liegen könnte ? Es spielen 2 Spieler auf dem Server. 

Beste Grüße 
Guido 

Von meinem iPhone gesendet

**Comment by Mogli12** [comment]
Hallo Guido,

der Helfer benötigt relativ viel Rechenleistung. Wenn der Dedi-Server nicht sonderlich gut ist, dann wird es halt langsam.

Viele Grüße, Stefan

**Comment by Mortime2301** [comment]
Ok ich werde mir das nochmal ansehen wie die Auslastung ist. 
Ich bin bei Gamed.de. 

Kannst du einen Server empfehlen?

Von meinem iPhone gesendet

**Comment by Mortime2301** [comment]
Hallo Stefan,

also ich habe jetzt 2 Server probiert. Nitrado und gamed.de. Bei beiden ist die CPU Last (ca. 80-90%) so hoch das es praktisch nicht spielbar ist.
Was kann ich noch tun ? Ist dir ein Server bekannt, wo es gehen könnte ?

Gruß
Guido

**Comment by Mogli12** [comment]
Hallo Guido,

ich spiele eigentlich kaum noch wirklich FS17. Und wenn dann nur im Single Player.

Viele Grüße, Stefan
