### ISSUE TITLE
Train unload bug!!

### ISSUE THREAD

**Issue by SMDSY** [Mogli12/AIVehicleExtension#87]
Hi iv encounterd a error/bug and im pretty shore that AI VE is responible...

I have taken a cupple of pictures that displays the error and the prosses in whit im gone try to explain,,,

1. Only active mods are AI VE version 1.0.0.0 from ingame mod hub  and Courseplay 5.01.00131..

2. Standrad map and standard Veichels that are shown on the pictures..

3. What happens is that When i load the train whit grain(or enything ells) i get Unload allover the UI and somethimes it extends outside of the UI overand over again like in aloop and the game starts to lag like crazy...
![20170508184702_1](https://cloud.githubusercontent.com/assets/15175150/25815410/8f0ec8ca-3420-11e7-8426-7a5ae26e2365.jpg)
![20170508184725_1](https://cloud.githubusercontent.com/assets/15175150/25815411/8f111c2e-3420-11e7-81d2-426094cb7766.jpg)
![20170508184735_1](https://cloud.githubusercontent.com/assets/15175150/25815412/8f14589e-3420-11e7-8b98-43a1ba79f724.jpg)
![20170508184854_1](https://cloud.githubusercontent.com/assets/15175150/25815413/8f16408c-3420-11e7-89d9-859c1492a1fc.jpg)

As sone i unload the Train it goes away...

**Comment by Mogli12** [comment]
Hi, this has nothing to do with AIVE. Regards, Stefan
