### ISSUE TITLE
Big Bud

### ISSUE THREAD

**Issue by iwan4672** [Mogli12/AIVehicleExtension#88]
Not co-operate from Big Bud

**Comment by Mogli12** [comment]
???

**Comment by iwan4672** [comment]
It at all does not activate in official addition - tractor Big Bud.

2017-05-09 11:46 GMT+02:00 Stefan Biedenstein <notifications@github.com>:

**Comment by iwan4672** [comment]
OK understand

**Comment by dominiczeth** [comment]
There is a Problem with Tractors with articulated axels. They seem to scan a field when they just drive on it. Even when the normal Helper is activated. It also does not scan normal, it scans very slow and slows the game down for a whole time.

**Comment by Mogli12** [comment]
Please try version 1.1 b14.

**Comment by dominiczeth** [comment]
Yes its fixed :) Thanks, that was fast.
