### ISSUE TITLE
Framrate

### ISSUE THREAD

**Issue by Premiumlike** [Mogli12/AIVehicleExtension#89]
Hi Ich nutze Aktuell diesen Drescher https://www.modhoster.de/mods/claas-lexion-700-stage-iv-pack und habe beim Dreschen mit der AIVehicleExtension Framedrops wenn diese Kurven fährt oder wendet so wie beim Abladen

**Comment by Mogli12** [comment]
AIVE benötigt recht viel Rechenpower.
