### ISSUE TITLE
Combine drives off after unloading without lowering header

### ISSUE THREAD

**Issue by HJTLincs** [Mogli12/AIVehicleExtension#9]
When the combine hits 100% capacity and stops to be unloaded, after it is unloaded, it does not lower the header again and just drives through the crop in front of it.

**Comment by tjb8907** [comment]
@Mogli12 I'm sure you are smart enough to figure it out, and I probably didn't do it the best way, but I figured out this section of code in the AutoSteeringEngine (checkAllowedToDrive function) is what stops the combine when its full

`	if vehicle.driveStrategies ~= nil and #vehicle.driveStrategies > 0 then
		local vX,vY,vZ = getWorldTranslation(vehicle.aiVehicleDirectionNode);
		
		local tX, tZ, moveForwards, maxSpeed, distanceToStop;
		for i=1,#vehicle.driveStrategies do
			local driveStrategy = vehicle.driveStrategies[i];
			if not driveStrategy:isa(AIDriveStrategyStraight) then
				local tX, tZ, moveForwards, maxSpeed, distanceToStop = driveStrategy:getDriveData(dt, vX,vY,vZ)
				if tX ~= nil then
					if maxSpeed <= 0 then
						vehicle.lastNotAllowedToDrive = true
						return false
					end
					break
				end
			end
		end
	end`

I added the line after 'if maxSpeed <= 0 then'
so it would go through the elseif below the next time through: 

`	if not allowedToDrive then
		vehicle.lastNotAllowedToDrive = true
	elseif vehicle.lastNotAllowedToDrive then
		vehicle.lastNotAllowedToDrive = false
		print("test1");
		print(allowedToDrive);
		AutoSteeringEngine.setToolsAreLowered( vehicle, true, false )		
	end`

It looks like you have plans to use the "checkCombineAllowedToDrive" eventually, so 'm sure that isn't a permanent fix. Just thought I'd try to maybe save you some time. :)
