### ISSUE TITLE
'Start' button of the game gets deactivated when AIVehicleExtension is enabled

### ISSUE THREAD

**Issue by fdanapfel** [Mogli12/AIVehicleExtension#90]
As documented in https://forum.giants-software.com/viewtopic.php?f=940&t=112545&p=877855#p873789 the 'Start' button of the game is deactivated by default when the AIVehicleExtension is enabled.

A few posts later somebody has provided a solution for this issue: https://forum.giants-software.com/viewtopic.php?f=940&t=112545&p=877855#p877855

**Comment by joskuijpers** [comment]
Created a Pull Request for my proposed solution.

**Comment by Mogli12** [comment]
Hi, I almost never play MP. I hope that the fix provided by @joskuijpers works. I integrated it into 1.0.0.4.

**Comment by joskuijpers** [comment]
This is not an MP thing. It is just named the MP screen but that is also used for singleplayer loading.

You can try t yourself: load 1.0.0.3 and the start button after loading is not highlighted.
Do it with 1.0.0.4 and it is

**Comment by fdanapfel** [comment]
Thanks, I was able to verify that version 1.0.0.4 does not cause the 'Start' button to become deactivated anymore in SP. Therefore I'm closing this issue.
