### ISSUE TITLE
Krone Big X Cargo Support

### ISSUE THREAD

**Issue by Brzzl** [Mogli12/AIVehicleExtension#92]
Hi!
First let me say thank you for your great mod! :)
I downloaded above forage harvester from GIANTS ModHub and it seems not to be compatible with AIVE. 
(https://www.farming-simulator.com/mod.php?lang=de&country=ch&mod_id=79745&title=fs2017)
Any chance to get this running?

**Comment by Brzzl** [comment]
Hmm... hab gerade gesehen, dass es hier einen Kommentar von dir gab, der sich auf die BigBuds bezog. Denke mal, dass AIVE das Gerät nicht unterstützt, weil es auch wieder eine Gelenkachse hat, oder?

**Comment by Mogli12** [comment]
Hallo,
genau, derzeit werden Geräte mit Knicklenkung leider nicht unterstützt. Beim Lenken bewegen sich die Geräte, was AIVE derzeit nicht in die Berechnung mit einbezieht.
Viele Grüße, Stefan
