### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Cristiqss** [Mogli12/AIVehicleExtension#94]
Hello, my friends, i have some problems with ai vehicle. I tried to install it in all posible mods but didn`t work. Can you make a tutorial or something, please? I winrared it in mods(fs 17), i copied all files in mods, i put the arhive in mods but didn t work.. help me please.

**Comment by Dzi4d3k** [comment]
There is no need to modify vehicles. AIVehicleExtension is a standalone mod. Just put its zip file in your mods folder and it is ready to work.

**Comment by Mogli12** [comment]
But it does not work for vehicles with articulated axis, e.g. Big Bud.

**Comment by Cristiqss** [comment]
I put in the mods folder but didn`t work...

**Comment by Dzi4d3k** [comment]
Latest FS patch? Can you share you game log? Is it shows on mod list in game available to select? Have you activated worker in mod settings (Left shift + H)? Does hud show on bottom? More details are needed, because "didn't work" may mean a lot of things.

**Comment by Cristiqss** [comment]
I have fs17 from filelist, i have latest version on this site(1.3). Isn t showed on mod list to activate, doesn t hud show.

**Comment by Mogli12** [comment]
Last version of FS17 is 1.4.4. And AIVE will not work with older versions. This was propose by Giants.

**Comment by Cristiqss** [comment]
Ok man, thanks, i ll try to install if i find 1.4.4 and i ll say if work.

**Comment by Cristiqss** [comment]
I downloaded latest update version from farming simulator mod  hub, and when i try to install said that i don`t have farming simulator 2017(english) version

**Comment by Dzi4d3k** [comment]
@Cristiqss "I have fs17 from filelist"
Is it legal version? Because from your description it seems not, and your experience with official patch 1.4.4 seems to confirm that.

**Comment by Cristiqss** [comment]
@Dzi4d3k I don`t know what to say.. i think is legal..

**Comment by Dzi4d3k** [comment]
You think? What is that "filelist" site? Is it online shop selling games? The one which I know is far from serving legal software.

**Comment by Mogli12** [comment]
Hi, I think we better close this one...
