### ISSUE TITLE
FS17_manualAttaching mod compatibility issue?

### ISSUE THREAD

**Issue by Dzi4d3k** [Mogli12/AIVehicleExtension#95]
Hello,

I'm getting following errors on client on in MP (dedicated server) game

`------------------------------------------------------------------------`
`ERROR: AutoSteeringEngine.setChainStatus called at client`
`------------------------------------------------------------------------`
`2: .../mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (188): printCallstack
3: .../mods/FS17_AIVehicleExtension/AutoSteeringEngine.lua (211): skipIfNotServer
4: .../mods/FS17_AIVehicleExtension/AutoSteeringEngine.lua (5058): initSteering
5: .../mods/FS17_AIVehicleExtension/AutoSteeringEngine.lua (1786): initTools
6: .../mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (1256): checkState
7: .../mods/FS17_AIVehicleExtension/AIVehicleExtension.lua (2173): f
8: [string "dataS/scripts/utils/SpecializationUtil.lua"] (19): onAttachImplement
9: [string "dataS/scripts/vehicles/specializations/AttacherJoints.lua"] (803): attachImplement
10: .../mods/FS17_manualAttaching/scripts/ManualAttaching.lua (687): attachImplement
...`
`------------------------------------------------------------------------`

I thought I'll ask whatever this is issue or not, fortunately all functionality seems to work fine.

**Comment by Mogli12** [comment]
Hi,

Please check version 1.0.0.8.

Thanks!
