### ISSUE TITLE
AutoSteeringEngine.lua:7059: attempt to index global 'implement' (a nil value)

### ISSUE THREAD

**Issue by RuppMartin001** [Mogli12/AIVehicleExtension#96]
Hallo Stefan,

ich bekomme seit heute Fehlermeldungen und kann das Spiel nicht starten.

Ich glaube aber, dass es nicht direkt mit AIVehicleExtension zu tun, sondern eher mit einem anderen Mod, den ich heute auch installiert habe. Ich weiß aber leider nicht mit welchem es zu tun hat.

Ich habe heute die V1.0.0.7 von AIVehicleExtension eingespielt. Am Deutz D 80 hat sich seit gestern nichts verändert. Deshalb glaube ich auch nicht, dass es mit ihm zu tun hat.
Ich habe auch schon versucht die V1.0.0.6 zu verwenden, bekomme aber auch die gleiche Fehlermeldung.
Gestern konnte ich mit der V1.0.0.6 ohne Probleme spielen.

Hier der Bereich mit dem Fehler:

Error: Can't load resource 'C:/Daten/Landwirtschafts Simulator 17/Installed Mods/deutz_D_80_Remraf/lenkrad/deutzAgroStar661Interior_diffuse.png'.
Error: Can't load resource 'C:/Daten/Landwirtschafts Simulator 17/Installed Mods/deutz_D_80_Remraf/lenkrad/deutzAgroStar661Interior_normal.png'.
Error: Can't load resource 'C:/Daten/Landwirtschafts Simulator 17/Installed Mods/deutz_D_80_Remraf/lenkrad/deutzAgroStar661Interior_specular.png'.
C:/Daten/Landwirtschafts Simulator 17/Installed Mods/deutz_D_80/deutzD80.i3d (129.84) ms
FS17_GearboxAddon: looking for default configuration (defaultTractors)
realismUpdate_tractor load init
Error: Running LUA method 'loadSharedI3DFileFinished'.
C:/Daten/Landwirtschafts Simulator 17/Installed Mods/AIVehicleExtension_1_0_0_7/AutoSteeringEngine.lua:7059: attempt to index global 'implement' (a nil value)

[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/1149488/log.txt)

Nehme ich den Deutz D 80 aus der Liste der zu ladenden Mods und nehme ich die V1.0.0.6, sieht die Fehlermeldung so aus:

C:/Daten/Landwirtschafts Simulator 17/Installed Mods/Famulus_V3_5/Famulus_r_c.i3d (123.62) ms
FS17_GearboxAddon: looking for default configuration (defaultTractors)
realismUpdate_tractor load init
Error: Running LUA method 'loadSharedI3DFileFinished'.
C:/Daten/Landwirtschafts Simulator 17/Installed Mods/AIVehicleExtension_1_0_0_6/AutoSteeringEngine.lua:7058: attempt to index global 'implement' (a nil value)

Wie gesagt, gestern konnte ich mit der V1.0.0.6 ganz normal das Spiel starten.

Viele Grüße

Martin

**Comment by RuppMartin001** [comment]
Ich habe nun in Zeile: 7059 im if noch ein implement ~= nil AND hinzugefügt:

            if implement ~= nil AND refNode == object.attacherJoint.node then
				local jointDesc = object.attacherVehicle.attacherJoints[implement.jointDescIndex]
				rotMax = math.max(jointDesc.upperRotLimit[2], jointDesc.lowerRotLimit[2]) * object.attacherJoint.lowerRotLimitScale[2]
			else
				for _,compJoint in pairs(object.componentJoints) do
					if refNode == compJoint.jointNode then
						rotMax = compJoint.rotLimit[2]
						if object.aiVehicleDirectionNode ~= nil then
							cx,_,cz = localToLocal(object.aiVehicleDirectionNode, refNode, 0,0,0)
						end
						break
					end
				end
			end

Womöglich wird nun aber rotMax falsch berechnet.
Ich kann aber so das Spiel starten.

Viele Grüße

Martin

**Comment by RuppMartin001** [comment]
Hallo Stefan,		
	
ich habe in V1.0.0.6 folgendes hinzugefügt (implement ~= nil im darauffolgenden Block ist nicht in der V1.0.0.6 enthalten):

    if implement == nil then
         print("implement is nil - vehicle:"..vehicle.baseDirectory..vehicle.configFileName)   
    end   

Im Log erscheint dann das:

implement is nil - vehicle:data/vehicles/steerable/deutz/deutzAgroStar661.xml
Error: Running LUA method 'loadSharedI3DFileFinished'.
C:/Daten/Landwirtschafts Simulator 17/Installed Mods/AIVehicleExtension_1_0_0_6_with_print/AutoSteeringEngine.lua:7063: attempt to index global 'implement' (a nil value)

Viele Grüße

Martin

**Comment by Mogli12** [comment]
Hello,

Please check version 1.0.0.8.

Thanks!

**Comment by RuppMartin001** [comment]
Funktioniert prima!

Vielen Dank!

Viele Grüße

Martin
