### ISSUE TITLE
Error: Running LUA method 'update'

### ISSUE THREAD

**Issue by jensjcs** [Mogli12/AIVehicleExtension#97]
Hello,

i played a new map for testing and got an error. here a few lines from the log. the full log is attached.
i hope it wont be something bad to fix

greetings
jens

[log.txt](https://github.com/Mogli12/AIVehicleExtension/files/1151935/log.txt)

data/vehicles/steerable/newHolland/newHollandT7.i3d (385.12) ms
Error: Running LUA method 'update'.
C:/Users/Jens/Documents/My Games/FarmingSimulator2017/mods/FS17_bpg_AIVehicleExtension/AutoSteeringEngine.lua:7058: attempt to index global 'implement' (a nil value)
Error: Running LUA method 'mouseEvent'.
C:/Users/Jens/Documents/My Games/FarmingSimulator2017/mods/FS17_bpg_AIVehicleExtension/AutoSteeringEngine.lua:7058: attempt to index global 'implement' (a nil value)
Warning (Script): Unknown entity id 166639 in method 'worldToLocal'.
LUA call stack:
  =C:/Users/Jens/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/vehicles.lua (422) : worldToLocal
  =C:/Users/Jens/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/reverse.lua (405) : getRealTrailerDistanceToPivot
  =C:/Users/Jens/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/toolManager.lua (335) : getReverseProperties
  =C:/Users/Jens/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/toolManager.lua (358) : updateWorkTools
  =C:/Users/Jens/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/toolManager.lua (32) : updateWorkTools
  =C:/Users/Jens/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/base.lua (1042) : resetTools
  dataS/scripts/vehicles/Vehicle.lua (2708) : updateTick
  dataS/scripts/network/Server.lua (68) : updateTick
  dataS/scripts/BaseMission.lua (1508) : update
  dataS/scripts/FSBaseMission.lua (2171) : update
  dataS/scripts/missions/mission00.lua (333) : update
  dataS/scripts/main.lua (1876) : update
Warning (Script): Unknown entity id 141724 in method 'delete'.
LUA call stack:
  dataS/scripts/FSBaseMission.lua (526) : delete
  dataS/scripts/missions/mission00.lua (84) : delete
  dataS/scripts/events.lua (125) : delete
  dataS/scripts/gui/InGameMenu.lua (446) : OnInGameMenuMenu
  dataS/scripts/gui/InGameMenu.lua (704) : leaveCurrentGame
  dataS/scripts/gui/dialogs/YesNoDialog.lua (62) : callbackFunc
  dataS/scripts/gui/dialogs/YesNoDialog.lua (50) : sendCallback
  dataS/scripts/gui/elements/ButtonElement.lua (191) : raiseCallback
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/Gui.lua (270) : mouseEvent
  dataS/scripts/main.lua (1811) : mouseEvent
Warning (Script): Unknown entity id 141725 in method 'delete'.
LUA call stack:
  dataS/scripts/FSBaseMission.lua (530) : delete
  dataS/scripts/missions/mission00.lua (84) : delete
  dataS/scripts/events.lua (125) : delete
  dataS/scripts/gui/InGameMenu.lua (446) : OnInGameMenuMenu
  dataS/scripts/gui/InGameMenu.lua (704) : leaveCurrentGame
  dataS/scripts/gui/dialogs/YesNoDialog.lua (62) : callbackFunc
  dataS/scripts/gui/dialogs/YesNoDialog.lua (50) : sendCallback
  dataS/scripts/gui/elements/ButtonElement.lua (191) : raiseCallback
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/Gui.lua (270) : mouseEvent
  dataS/scripts/main.lua (1811) : mouseEvent
Error: Running LUA method 'mouseEvent'.
C:/Users/Jens/Documents/My Games/FarmingSimulator2017/mods/FS17_bpg_AIVehicleExtension/AutoSteeringEngine.lua:7058: attempt to index global 'implement' (a nil value)
Warning (Script): Unknown entity id 166639 in method 'worldToLocal'.
LUA call stack:
  =C:/Users/Jens/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/vehicles.lua (422) : worldToLocal
  =C:/Users/Jens/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/reverse.lua (405) : getRealTrailerDistanceToPivot
  =C:/Users/Jens/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/toolManager.lua (335) : getReverseProperties
  =C:/Users/Jens/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/toolManager.lua (358) : updateWorkTools
  =C:/Users/Jens/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/toolManager.lua (32) : updateWorkTools
  =C:/Users/Jens/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/base.lua (1042) : resetTools
  dataS/scripts/vehicles/Vehicle.lua (2708) : updateTick
  dataS/scripts/network/Server.lua (68) : updateTick
  dataS/scripts/BaseMission.lua (1508) : update
  dataS/scripts/FSBaseMission.lua (2171) : update
  dataS/scripts/missions/mission00.lua (333) : update
  dataS/scripts/main.lua (1876) : update
Warning (Script): Unknown entity id 141724 in method 'delete'.
LUA call stack:
  dataS/scripts/FSBaseMission.lua (526) : delete
  dataS/scripts/missions/mission00.lua (84) : delete
  dataS/scripts/events.lua (125) : delete
  dataS/scripts/gui/InGameMenu.lua (446) : OnInGameMenuMenu
  dataS/scripts/gui/InGameMenu.lua (704) : leaveCurrentGame
  dataS/scripts/gui/dialogs/YesNoDialog.lua (62) : callbackFunc
  dataS/scripts/gui/dialogs/YesNoDialog.lua (50) : sendCallback
  dataS/scripts/gui/elements/ButtonElement.lua (191) : raiseCallback
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/Gui.lua (270) : mouseEvent
  dataS/scripts/main.lua (1811) : mouseEvent
Warning (Script): Unknown entity id 141725 in method 'delete'.
LUA call stack:
  dataS/scripts/FSBaseMission.lua (530) : delete
  dataS/scripts/missions/mission00.lua (84) : delete
  dataS/scripts/events.lua (125) : delete
  dataS/scripts/gui/InGameMenu.lua (446) : OnInGameMenuMenu
  dataS/scripts/gui/InGameMenu.lua (704) : leaveCurrentGame
  dataS/scripts/gui/dialogs/YesNoDialog.lua (62) : callbackFunc
  dataS/scripts/gui/dialogs/YesNoDialog.lua (50) : sendCallback
  dataS/scripts/gui/elements/ButtonElement.lua (191) : raiseCallback
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/Gui.lua (270) : mouseEvent
  dataS/scripts/main.lua (1811) : mouseEvent
Error: Running LUA method 'mouseEvent'.
C:/Users/Jens/Documents/My Games/FarmingSimulator2017/mods/FS17_bpg_AIVehicleExtension/AutoSteeringEngine.lua:7058: attempt to index global 'implement' (a nil value)
Application exit request forced.

**Comment by Mogli12** [comment]
Hello,

Please check issue #96. Please check if a problem still exists in the lastest version (1.0.0.8) before you open a new issue.

Thanks!
