### ISSUE TITLE
Issue with Combine Signal Mod

### ISSUE THREAD

**Issue by therealcrow999** [Mogli12/AIVehicleExtension#98]
I reported this issue over on Combine Signal mod. I don't know who mod is causing it. This is what I wrote there, https://github.com/TyKonKet/FS17_CombineSignals :

If I use the AI from AI Vehicle Extension mod, the Beacons won't signal right or not at all. I can use the AI from FS17 website or use 1.0.0.8 from GitHub and still has issues. 
https://github.com/Mogli12/AIVehicleExtension

Combine Signal mod works fine if I don't use AI Vehicle Extension mod, if in game I select to use default AI with the mod. 

The sound and audio seem to be going off fine.

Thanks.

**Comment by Mogli12** [comment]
Hi,
I do not think that any of the TyKonKets mods are compatible with any of my mods.
Regards, Stefan

**Comment by therealcrow999** [comment]
Yeah, I reported the problem over there and he told me to message you, like he saying you need to fix it. It is fine I will not use that mod of his. 

Thanks.
