### ISSUE TITLE
Headland with Hired Worker

### ISSUE THREAD

**Issue by adamp1986** [Mogli12/AIVehicleExtension#99]
In FS15 I seem to remember that it was possible to set a headland on a standard worker (not AItractor), it doesn't seem to work in this version?

**Comment by Mogli12** [comment]
Please press LShift-H to open the settings dialog.

**Comment by Mogli12** [comment]
No, the headland option for the standard worker is not available anymore. But in FS17 the standard worker should check for collisions.
